/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MembershipInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MembershipInfo{}

// MembershipInfo struct for MembershipInfo
type MembershipInfo struct {
	Id         string `json:"id"`
	OrgId      string `json:"org_id"`
	OrgSlug    string `json:"org_slug"`
	OrgName    string `json:"org_name"`
	SchemaName string `json:"schema_name"`
	RoleId     string `json:"role_id"`
	Role       string `json:"role"`
	Status     string `json:"status"`
}

type _MembershipInfo MembershipInfo

// NewMembershipInfo instantiates a new MembershipInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMembershipInfo(id string, orgId string, orgSlug string, orgName string, schemaName string, roleId string, role string, status string) *MembershipInfo {
	this := MembershipInfo{}
	this.Id = id
	this.OrgId = orgId
	this.OrgSlug = orgSlug
	this.OrgName = orgName
	this.SchemaName = schemaName
	this.RoleId = roleId
	this.Role = role
	this.Status = status
	return &this
}

// NewMembershipInfoWithDefaults instantiates a new MembershipInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembershipInfoWithDefaults() *MembershipInfo {
	this := MembershipInfo{}
	return &this
}

// GetId returns the Id field value
func (o *MembershipInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MembershipInfo) SetId(v string) {
	o.Id = v
}

// GetOrgId returns the OrgId field value
func (o *MembershipInfo) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *MembershipInfo) SetOrgId(v string) {
	o.OrgId = v
}

// GetOrgSlug returns the OrgSlug field value
func (o *MembershipInfo) GetOrgSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgSlug
}

// GetOrgSlugOk returns a tuple with the OrgSlug field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetOrgSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgSlug, true
}

// SetOrgSlug sets field value
func (o *MembershipInfo) SetOrgSlug(v string) {
	o.OrgSlug = v
}

// GetOrgName returns the OrgName field value
func (o *MembershipInfo) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *MembershipInfo) SetOrgName(v string) {
	o.OrgName = v
}

// GetSchemaName returns the SchemaName field value
func (o *MembershipInfo) GetSchemaName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaName
}

// GetSchemaNameOk returns a tuple with the SchemaName field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetSchemaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaName, true
}

// SetSchemaName sets field value
func (o *MembershipInfo) SetSchemaName(v string) {
	o.SchemaName = v
}

// GetRoleId returns the RoleId field value
func (o *MembershipInfo) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *MembershipInfo) SetRoleId(v string) {
	o.RoleId = v
}

// GetRole returns the Role field value
func (o *MembershipInfo) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MembershipInfo) SetRole(v string) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *MembershipInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MembershipInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MembershipInfo) SetStatus(v string) {
	o.Status = v
}

func (o MembershipInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MembershipInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["org_id"] = o.OrgId
	toSerialize["org_slug"] = o.OrgSlug
	toSerialize["org_name"] = o.OrgName
	toSerialize["schema_name"] = o.SchemaName
	toSerialize["role_id"] = o.RoleId
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *MembershipInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"org_id",
		"org_slug",
		"org_name",
		"schema_name",
		"role_id",
		"role",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMembershipInfo := _MembershipInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMembershipInfo)

	if err != nil {
		return err
	}

	*o = MembershipInfo(varMembershipInfo)

	return err
}

type NullableMembershipInfo struct {
	value *MembershipInfo
	isSet bool
}

func (v NullableMembershipInfo) Get() *MembershipInfo {
	return v.value
}

func (v *NullableMembershipInfo) Set(val *MembershipInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMembershipInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMembershipInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMembershipInfo(val *MembershipInfo) *NullableMembershipInfo {
	return &NullableMembershipInfo{value: val, isSet: true}
}

func (v NullableMembershipInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMembershipInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
