/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseModuleBriefsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseModuleBriefsResponse{}

// CodebaseModuleBriefsResponse List of Module Brief artifacts for a snapshot.
type CodebaseModuleBriefsResponse struct {
	CodebaseId string `json:"codebase_id"`
	SnapshotId NullableString `json:"snapshot_id,omitempty"`
	Items []map[string]interface{} `json:"items,omitempty"`
}

type _CodebaseModuleBriefsResponse CodebaseModuleBriefsResponse

// NewCodebaseModuleBriefsResponse instantiates a new CodebaseModuleBriefsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseModuleBriefsResponse(codebaseId string) *CodebaseModuleBriefsResponse {
	this := CodebaseModuleBriefsResponse{}
	this.CodebaseId = codebaseId
	return &this
}

// NewCodebaseModuleBriefsResponseWithDefaults instantiates a new CodebaseModuleBriefsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseModuleBriefsResponseWithDefaults() *CodebaseModuleBriefsResponse {
	this := CodebaseModuleBriefsResponse{}
	return &this
}

// GetCodebaseId returns the CodebaseId field value
func (o *CodebaseModuleBriefsResponse) GetCodebaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodebaseId
}

// GetCodebaseIdOk returns a tuple with the CodebaseId field value
// and a boolean to check if the value has been set.
func (o *CodebaseModuleBriefsResponse) GetCodebaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodebaseId, true
}

// SetCodebaseId sets field value
func (o *CodebaseModuleBriefsResponse) SetCodebaseId(v string) {
	o.CodebaseId = v
}

// GetSnapshotId returns the SnapshotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseModuleBriefsResponse) GetSnapshotId() string {
	if o == nil || IsNil(o.SnapshotId.Get()) {
		var ret string
		return ret
	}
	return *o.SnapshotId.Get()
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseModuleBriefsResponse) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotId.Get(), o.SnapshotId.IsSet()
}

// HasSnapshotId returns a boolean if a field has been set.
func (o *CodebaseModuleBriefsResponse) HasSnapshotId() bool {
	if o != nil && o.SnapshotId.IsSet() {
		return true
	}

	return false
}

// SetSnapshotId gets a reference to the given NullableString and assigns it to the SnapshotId field.
func (o *CodebaseModuleBriefsResponse) SetSnapshotId(v string) {
	o.SnapshotId.Set(&v)
}
// SetSnapshotIdNil sets the value for SnapshotId to be an explicit nil
func (o *CodebaseModuleBriefsResponse) SetSnapshotIdNil() {
	o.SnapshotId.Set(nil)
}

// UnsetSnapshotId ensures that no value is present for SnapshotId, not even an explicit nil
func (o *CodebaseModuleBriefsResponse) UnsetSnapshotId() {
	o.SnapshotId.Unset()
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CodebaseModuleBriefsResponse) GetItems() []map[string]interface{} {
	if o == nil || IsNil(o.Items) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseModuleBriefsResponse) GetItemsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CodebaseModuleBriefsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []map[string]interface{} and assigns it to the Items field.
func (o *CodebaseModuleBriefsResponse) SetItems(v []map[string]interface{}) {
	o.Items = v
}

func (o CodebaseModuleBriefsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseModuleBriefsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codebase_id"] = o.CodebaseId
	if o.SnapshotId.IsSet() {
		toSerialize["snapshot_id"] = o.SnapshotId.Get()
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

func (o *CodebaseModuleBriefsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codebase_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseModuleBriefsResponse := _CodebaseModuleBriefsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseModuleBriefsResponse)

	if err != nil {
		return err
	}

	*o = CodebaseModuleBriefsResponse(varCodebaseModuleBriefsResponse)

	return err
}

type NullableCodebaseModuleBriefsResponse struct {
	value *CodebaseModuleBriefsResponse
	isSet bool
}

func (v NullableCodebaseModuleBriefsResponse) Get() *CodebaseModuleBriefsResponse {
	return v.value
}

func (v *NullableCodebaseModuleBriefsResponse) Set(val *CodebaseModuleBriefsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseModuleBriefsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseModuleBriefsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseModuleBriefsResponse(val *CodebaseModuleBriefsResponse) *NullableCodebaseModuleBriefsResponse {
	return &NullableCodebaseModuleBriefsResponse{value: val, isSet: true}
}

func (v NullableCodebaseModuleBriefsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseModuleBriefsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


