/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RetryOperationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetryOperationResponse{}

// RetryOperationResponse Response model for retry operation endpoint.
type RetryOperationResponse struct {
	Success                bool           `json:"success"`
	Message                string         `json:"message"`
	OperationId            string         `json:"operation_id"`
	RetriedFromOperationId string         `json:"retried_from_operation_id"`
	BankId                 string         `json:"bank_id"`
	OperationType          NullableString `json:"operation_type,omitempty"`
}

type _RetryOperationResponse RetryOperationResponse

// NewRetryOperationResponse instantiates a new RetryOperationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetryOperationResponse(success bool, message string, operationId string, retriedFromOperationId string, bankId string) *RetryOperationResponse {
	this := RetryOperationResponse{}
	this.Success = success
	this.Message = message
	this.OperationId = operationId
	this.RetriedFromOperationId = retriedFromOperationId
	this.BankId = bankId
	return &this
}

// NewRetryOperationResponseWithDefaults instantiates a new RetryOperationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetryOperationResponseWithDefaults() *RetryOperationResponse {
	this := RetryOperationResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *RetryOperationResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *RetryOperationResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *RetryOperationResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *RetryOperationResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *RetryOperationResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *RetryOperationResponse) SetMessage(v string) {
	o.Message = v
}

// GetOperationId returns the OperationId field value
func (o *RetryOperationResponse) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *RetryOperationResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *RetryOperationResponse) SetOperationId(v string) {
	o.OperationId = v
}

// GetRetriedFromOperationId returns the RetriedFromOperationId field value
func (o *RetryOperationResponse) GetRetriedFromOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RetriedFromOperationId
}

// GetRetriedFromOperationIdOk returns a tuple with the RetriedFromOperationId field value
// and a boolean to check if the value has been set.
func (o *RetryOperationResponse) GetRetriedFromOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetriedFromOperationId, true
}

// SetRetriedFromOperationId sets field value
func (o *RetryOperationResponse) SetRetriedFromOperationId(v string) {
	o.RetriedFromOperationId = v
}

// GetBankId returns the BankId field value
func (o *RetryOperationResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *RetryOperationResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *RetryOperationResponse) SetBankId(v string) {
	o.BankId = v
}

// GetOperationType returns the OperationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RetryOperationResponse) GetOperationType() string {
	if o == nil || IsNil(o.OperationType.Get()) {
		var ret string
		return ret
	}
	return *o.OperationType.Get()
}

// GetOperationTypeOk returns a tuple with the OperationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RetryOperationResponse) GetOperationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperationType.Get(), o.OperationType.IsSet()
}

// HasOperationType returns a boolean if a field has been set.
func (o *RetryOperationResponse) HasOperationType() bool {
	if o != nil && o.OperationType.IsSet() {
		return true
	}

	return false
}

// SetOperationType gets a reference to the given NullableString and assigns it to the OperationType field.
func (o *RetryOperationResponse) SetOperationType(v string) {
	o.OperationType.Set(&v)
}

// SetOperationTypeNil sets the value for OperationType to be an explicit nil
func (o *RetryOperationResponse) SetOperationTypeNil() {
	o.OperationType.Set(nil)
}

// UnsetOperationType ensures that no value is present for OperationType, not even an explicit nil
func (o *RetryOperationResponse) UnsetOperationType() {
	o.OperationType.Unset()
}

func (o RetryOperationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetryOperationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	toSerialize["operation_id"] = o.OperationId
	toSerialize["retried_from_operation_id"] = o.RetriedFromOperationId
	toSerialize["bank_id"] = o.BankId
	if o.OperationType.IsSet() {
		toSerialize["operation_type"] = o.OperationType.Get()
	}
	return toSerialize, nil
}

func (o *RetryOperationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
		"operation_id",
		"retried_from_operation_id",
		"bank_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRetryOperationResponse := _RetryOperationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRetryOperationResponse)

	if err != nil {
		return err
	}

	*o = RetryOperationResponse(varRetryOperationResponse)

	return err
}

type NullableRetryOperationResponse struct {
	value *RetryOperationResponse
	isSet bool
}

func (v NullableRetryOperationResponse) Get() *RetryOperationResponse {
	return v.value
}

func (v *NullableRetryOperationResponse) Set(val *RetryOperationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRetryOperationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRetryOperationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetryOperationResponse(val *RetryOperationResponse) *NullableRetryOperationResponse {
	return &NullableRetryOperationResponse{value: val, isSet: true}
}

func (v NullableRetryOperationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetryOperationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
