/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DreamStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DreamStatsResponse{}

// DreamStatsResponse struct for DreamStatsResponse
type DreamStatsResponse struct {
	BankId string `json:"bank_id"`
	TotalRuns int32 `json:"total_runs"`
	LastRunAt NullableString `json:"last_run_at"`
	AvgQuality float32 `json:"avg_quality"`
	AvgTokens float32 `json:"avg_tokens"`
	AvgOutputTokens float32 `json:"avg_output_tokens"`
	DistillationPassRate float32 `json:"distillation_pass_rate"`
	DistilledCount int32 `json:"distilled_count"`
	ValidationRate *float32 `json:"validation_rate,omitempty"`
	AvgNovelty *float32 `json:"avg_novelty,omitempty"`
	FailedRunCount *int32 `json:"failed_run_count,omitempty"`
	DuplicateSuppressionCount *int32 `json:"duplicate_suppression_count,omitempty"`
	PredictionConfirmationRate *float32 `json:"prediction_confirmation_rate,omitempty"`
	UnresolvedPredictionBacklog *int32 `json:"unresolved_prediction_backlog,omitempty"`
}

type _DreamStatsResponse DreamStatsResponse

// NewDreamStatsResponse instantiates a new DreamStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDreamStatsResponse(bankId string, totalRuns int32, lastRunAt NullableString, avgQuality float32, avgTokens float32, avgOutputTokens float32, distillationPassRate float32, distilledCount int32) *DreamStatsResponse {
	this := DreamStatsResponse{}
	this.BankId = bankId
	this.TotalRuns = totalRuns
	this.LastRunAt = lastRunAt
	this.AvgQuality = avgQuality
	this.AvgTokens = avgTokens
	this.AvgOutputTokens = avgOutputTokens
	this.DistillationPassRate = distillationPassRate
	this.DistilledCount = distilledCount
	var validationRate float32 = 0.0
	this.ValidationRate = &validationRate
	var avgNovelty float32 = 0.0
	this.AvgNovelty = &avgNovelty
	var failedRunCount int32 = 0
	this.FailedRunCount = &failedRunCount
	var duplicateSuppressionCount int32 = 0
	this.DuplicateSuppressionCount = &duplicateSuppressionCount
	var predictionConfirmationRate float32 = 0.0
	this.PredictionConfirmationRate = &predictionConfirmationRate
	var unresolvedPredictionBacklog int32 = 0
	this.UnresolvedPredictionBacklog = &unresolvedPredictionBacklog
	return &this
}

// NewDreamStatsResponseWithDefaults instantiates a new DreamStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDreamStatsResponseWithDefaults() *DreamStatsResponse {
	this := DreamStatsResponse{}
	var validationRate float32 = 0.0
	this.ValidationRate = &validationRate
	var avgNovelty float32 = 0.0
	this.AvgNovelty = &avgNovelty
	var failedRunCount int32 = 0
	this.FailedRunCount = &failedRunCount
	var duplicateSuppressionCount int32 = 0
	this.DuplicateSuppressionCount = &duplicateSuppressionCount
	var predictionConfirmationRate float32 = 0.0
	this.PredictionConfirmationRate = &predictionConfirmationRate
	var unresolvedPredictionBacklog int32 = 0
	this.UnresolvedPredictionBacklog = &unresolvedPredictionBacklog
	return &this
}

// GetBankId returns the BankId field value
func (o *DreamStatsResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *DreamStatsResponse) SetBankId(v string) {
	o.BankId = v
}

// GetTotalRuns returns the TotalRuns field value
func (o *DreamStatsResponse) GetTotalRuns() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalRuns
}

// GetTotalRunsOk returns a tuple with the TotalRuns field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetTotalRunsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRuns, true
}

// SetTotalRuns sets field value
func (o *DreamStatsResponse) SetTotalRuns(v int32) {
	o.TotalRuns = v
}

// GetLastRunAt returns the LastRunAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DreamStatsResponse) GetLastRunAt() string {
	if o == nil || o.LastRunAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastRunAt.Get()
}

// GetLastRunAtOk returns a tuple with the LastRunAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DreamStatsResponse) GetLastRunAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastRunAt.Get(), o.LastRunAt.IsSet()
}

// SetLastRunAt sets field value
func (o *DreamStatsResponse) SetLastRunAt(v string) {
	o.LastRunAt.Set(&v)
}

// GetAvgQuality returns the AvgQuality field value
func (o *DreamStatsResponse) GetAvgQuality() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AvgQuality
}

// GetAvgQualityOk returns a tuple with the AvgQuality field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetAvgQualityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvgQuality, true
}

// SetAvgQuality sets field value
func (o *DreamStatsResponse) SetAvgQuality(v float32) {
	o.AvgQuality = v
}

// GetAvgTokens returns the AvgTokens field value
func (o *DreamStatsResponse) GetAvgTokens() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AvgTokens
}

// GetAvgTokensOk returns a tuple with the AvgTokens field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetAvgTokensOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvgTokens, true
}

// SetAvgTokens sets field value
func (o *DreamStatsResponse) SetAvgTokens(v float32) {
	o.AvgTokens = v
}

// GetAvgOutputTokens returns the AvgOutputTokens field value
func (o *DreamStatsResponse) GetAvgOutputTokens() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AvgOutputTokens
}

// GetAvgOutputTokensOk returns a tuple with the AvgOutputTokens field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetAvgOutputTokensOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvgOutputTokens, true
}

// SetAvgOutputTokens sets field value
func (o *DreamStatsResponse) SetAvgOutputTokens(v float32) {
	o.AvgOutputTokens = v
}

// GetDistillationPassRate returns the DistillationPassRate field value
func (o *DreamStatsResponse) GetDistillationPassRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DistillationPassRate
}

// GetDistillationPassRateOk returns a tuple with the DistillationPassRate field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetDistillationPassRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistillationPassRate, true
}

// SetDistillationPassRate sets field value
func (o *DreamStatsResponse) SetDistillationPassRate(v float32) {
	o.DistillationPassRate = v
}

// GetDistilledCount returns the DistilledCount field value
func (o *DreamStatsResponse) GetDistilledCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DistilledCount
}

// GetDistilledCountOk returns a tuple with the DistilledCount field value
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetDistilledCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistilledCount, true
}

// SetDistilledCount sets field value
func (o *DreamStatsResponse) SetDistilledCount(v int32) {
	o.DistilledCount = v
}

// GetValidationRate returns the ValidationRate field value if set, zero value otherwise.
func (o *DreamStatsResponse) GetValidationRate() float32 {
	if o == nil || IsNil(o.ValidationRate) {
		var ret float32
		return ret
	}
	return *o.ValidationRate
}

// GetValidationRateOk returns a tuple with the ValidationRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetValidationRateOk() (*float32, bool) {
	if o == nil || IsNil(o.ValidationRate) {
		return nil, false
	}
	return o.ValidationRate, true
}

// HasValidationRate returns a boolean if a field has been set.
func (o *DreamStatsResponse) HasValidationRate() bool {
	if o != nil && !IsNil(o.ValidationRate) {
		return true
	}

	return false
}

// SetValidationRate gets a reference to the given float32 and assigns it to the ValidationRate field.
func (o *DreamStatsResponse) SetValidationRate(v float32) {
	o.ValidationRate = &v
}

// GetAvgNovelty returns the AvgNovelty field value if set, zero value otherwise.
func (o *DreamStatsResponse) GetAvgNovelty() float32 {
	if o == nil || IsNil(o.AvgNovelty) {
		var ret float32
		return ret
	}
	return *o.AvgNovelty
}

// GetAvgNoveltyOk returns a tuple with the AvgNovelty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetAvgNoveltyOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgNovelty) {
		return nil, false
	}
	return o.AvgNovelty, true
}

// HasAvgNovelty returns a boolean if a field has been set.
func (o *DreamStatsResponse) HasAvgNovelty() bool {
	if o != nil && !IsNil(o.AvgNovelty) {
		return true
	}

	return false
}

// SetAvgNovelty gets a reference to the given float32 and assigns it to the AvgNovelty field.
func (o *DreamStatsResponse) SetAvgNovelty(v float32) {
	o.AvgNovelty = &v
}

// GetFailedRunCount returns the FailedRunCount field value if set, zero value otherwise.
func (o *DreamStatsResponse) GetFailedRunCount() int32 {
	if o == nil || IsNil(o.FailedRunCount) {
		var ret int32
		return ret
	}
	return *o.FailedRunCount
}

// GetFailedRunCountOk returns a tuple with the FailedRunCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetFailedRunCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedRunCount) {
		return nil, false
	}
	return o.FailedRunCount, true
}

// HasFailedRunCount returns a boolean if a field has been set.
func (o *DreamStatsResponse) HasFailedRunCount() bool {
	if o != nil && !IsNil(o.FailedRunCount) {
		return true
	}

	return false
}

// SetFailedRunCount gets a reference to the given int32 and assigns it to the FailedRunCount field.
func (o *DreamStatsResponse) SetFailedRunCount(v int32) {
	o.FailedRunCount = &v
}

// GetDuplicateSuppressionCount returns the DuplicateSuppressionCount field value if set, zero value otherwise.
func (o *DreamStatsResponse) GetDuplicateSuppressionCount() int32 {
	if o == nil || IsNil(o.DuplicateSuppressionCount) {
		var ret int32
		return ret
	}
	return *o.DuplicateSuppressionCount
}

// GetDuplicateSuppressionCountOk returns a tuple with the DuplicateSuppressionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetDuplicateSuppressionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DuplicateSuppressionCount) {
		return nil, false
	}
	return o.DuplicateSuppressionCount, true
}

// HasDuplicateSuppressionCount returns a boolean if a field has been set.
func (o *DreamStatsResponse) HasDuplicateSuppressionCount() bool {
	if o != nil && !IsNil(o.DuplicateSuppressionCount) {
		return true
	}

	return false
}

// SetDuplicateSuppressionCount gets a reference to the given int32 and assigns it to the DuplicateSuppressionCount field.
func (o *DreamStatsResponse) SetDuplicateSuppressionCount(v int32) {
	o.DuplicateSuppressionCount = &v
}

// GetPredictionConfirmationRate returns the PredictionConfirmationRate field value if set, zero value otherwise.
func (o *DreamStatsResponse) GetPredictionConfirmationRate() float32 {
	if o == nil || IsNil(o.PredictionConfirmationRate) {
		var ret float32
		return ret
	}
	return *o.PredictionConfirmationRate
}

// GetPredictionConfirmationRateOk returns a tuple with the PredictionConfirmationRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetPredictionConfirmationRateOk() (*float32, bool) {
	if o == nil || IsNil(o.PredictionConfirmationRate) {
		return nil, false
	}
	return o.PredictionConfirmationRate, true
}

// HasPredictionConfirmationRate returns a boolean if a field has been set.
func (o *DreamStatsResponse) HasPredictionConfirmationRate() bool {
	if o != nil && !IsNil(o.PredictionConfirmationRate) {
		return true
	}

	return false
}

// SetPredictionConfirmationRate gets a reference to the given float32 and assigns it to the PredictionConfirmationRate field.
func (o *DreamStatsResponse) SetPredictionConfirmationRate(v float32) {
	o.PredictionConfirmationRate = &v
}

// GetUnresolvedPredictionBacklog returns the UnresolvedPredictionBacklog field value if set, zero value otherwise.
func (o *DreamStatsResponse) GetUnresolvedPredictionBacklog() int32 {
	if o == nil || IsNil(o.UnresolvedPredictionBacklog) {
		var ret int32
		return ret
	}
	return *o.UnresolvedPredictionBacklog
}

// GetUnresolvedPredictionBacklogOk returns a tuple with the UnresolvedPredictionBacklog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamStatsResponse) GetUnresolvedPredictionBacklogOk() (*int32, bool) {
	if o == nil || IsNil(o.UnresolvedPredictionBacklog) {
		return nil, false
	}
	return o.UnresolvedPredictionBacklog, true
}

// HasUnresolvedPredictionBacklog returns a boolean if a field has been set.
func (o *DreamStatsResponse) HasUnresolvedPredictionBacklog() bool {
	if o != nil && !IsNil(o.UnresolvedPredictionBacklog) {
		return true
	}

	return false
}

// SetUnresolvedPredictionBacklog gets a reference to the given int32 and assigns it to the UnresolvedPredictionBacklog field.
func (o *DreamStatsResponse) SetUnresolvedPredictionBacklog(v int32) {
	o.UnresolvedPredictionBacklog = &v
}

func (o DreamStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DreamStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	toSerialize["total_runs"] = o.TotalRuns
	toSerialize["last_run_at"] = o.LastRunAt.Get()
	toSerialize["avg_quality"] = o.AvgQuality
	toSerialize["avg_tokens"] = o.AvgTokens
	toSerialize["avg_output_tokens"] = o.AvgOutputTokens
	toSerialize["distillation_pass_rate"] = o.DistillationPassRate
	toSerialize["distilled_count"] = o.DistilledCount
	if !IsNil(o.ValidationRate) {
		toSerialize["validation_rate"] = o.ValidationRate
	}
	if !IsNil(o.AvgNovelty) {
		toSerialize["avg_novelty"] = o.AvgNovelty
	}
	if !IsNil(o.FailedRunCount) {
		toSerialize["failed_run_count"] = o.FailedRunCount
	}
	if !IsNil(o.DuplicateSuppressionCount) {
		toSerialize["duplicate_suppression_count"] = o.DuplicateSuppressionCount
	}
	if !IsNil(o.PredictionConfirmationRate) {
		toSerialize["prediction_confirmation_rate"] = o.PredictionConfirmationRate
	}
	if !IsNil(o.UnresolvedPredictionBacklog) {
		toSerialize["unresolved_prediction_backlog"] = o.UnresolvedPredictionBacklog
	}
	return toSerialize, nil
}

func (o *DreamStatsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"total_runs",
		"last_run_at",
		"avg_quality",
		"avg_tokens",
		"avg_output_tokens",
		"distillation_pass_rate",
		"distilled_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDreamStatsResponse := _DreamStatsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDreamStatsResponse)

	if err != nil {
		return err
	}

	*o = DreamStatsResponse(varDreamStatsResponse)

	return err
}

type NullableDreamStatsResponse struct {
	value *DreamStatsResponse
	isSet bool
}

func (v NullableDreamStatsResponse) Get() *DreamStatsResponse {
	return v.value
}

func (v *NullableDreamStatsResponse) Set(val *DreamStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDreamStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDreamStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDreamStatsResponse(val *DreamStatsResponse) *NullableDreamStatsResponse {
	return &NullableDreamStatsResponse{value: val, isSet: true}
}

func (v NullableDreamStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDreamStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


