/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseRouteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseRouteRequest{}

// CodebaseRouteRequest Bulk review-route update request.
type CodebaseRouteRequest struct {
	ItemIds []string `json:"item_ids"`
	Target string `json:"target"`
	QueueMemoryImport *bool `json:"queue_memory_import,omitempty"`
	MemoryIngestMode *string `json:"memory_ingest_mode,omitempty"`
}

type _CodebaseRouteRequest CodebaseRouteRequest

// NewCodebaseRouteRequest instantiates a new CodebaseRouteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseRouteRequest(itemIds []string, target string) *CodebaseRouteRequest {
	this := CodebaseRouteRequest{}
	this.ItemIds = itemIds
	this.Target = target
	return &this
}

// NewCodebaseRouteRequestWithDefaults instantiates a new CodebaseRouteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseRouteRequestWithDefaults() *CodebaseRouteRequest {
	this := CodebaseRouteRequest{}
	return &this
}

// GetItemIds returns the ItemIds field value
func (o *CodebaseRouteRequest) GetItemIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ItemIds
}

// GetItemIdsOk returns a tuple with the ItemIds field value
// and a boolean to check if the value has been set.
func (o *CodebaseRouteRequest) GetItemIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemIds, true
}

// SetItemIds sets field value
func (o *CodebaseRouteRequest) SetItemIds(v []string) {
	o.ItemIds = v
}

// GetTarget returns the Target field value
func (o *CodebaseRouteRequest) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *CodebaseRouteRequest) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *CodebaseRouteRequest) SetTarget(v string) {
	o.Target = v
}

// GetQueueMemoryImport returns the QueueMemoryImport field value if set, zero value otherwise.
func (o *CodebaseRouteRequest) GetQueueMemoryImport() bool {
	if o == nil || IsNil(o.QueueMemoryImport) {
		var ret bool
		return ret
	}
	return *o.QueueMemoryImport
}

// GetQueueMemoryImportOk returns a tuple with the QueueMemoryImport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseRouteRequest) GetQueueMemoryImportOk() (*bool, bool) {
	if o == nil || IsNil(o.QueueMemoryImport) {
		return nil, false
	}
	return o.QueueMemoryImport, true
}

// HasQueueMemoryImport returns a boolean if a field has been set.
func (o *CodebaseRouteRequest) HasQueueMemoryImport() bool {
	if o != nil && !IsNil(o.QueueMemoryImport) {
		return true
	}

	return false
}

// SetQueueMemoryImport gets a reference to the given bool and assigns it to the QueueMemoryImport field.
func (o *CodebaseRouteRequest) SetQueueMemoryImport(v bool) {
	o.QueueMemoryImport = &v
}

// GetMemoryIngestMode returns the MemoryIngestMode field value if set, zero value otherwise.
func (o *CodebaseRouteRequest) GetMemoryIngestMode() string {
	if o == nil || IsNil(o.MemoryIngestMode) {
		var ret string
		return ret
	}
	return *o.MemoryIngestMode
}

// GetMemoryIngestModeOk returns a tuple with the MemoryIngestMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseRouteRequest) GetMemoryIngestModeOk() (*string, bool) {
	if o == nil || IsNil(o.MemoryIngestMode) {
		return nil, false
	}
	return o.MemoryIngestMode, true
}

// HasMemoryIngestMode returns a boolean if a field has been set.
func (o *CodebaseRouteRequest) HasMemoryIngestMode() bool {
	if o != nil && !IsNil(o.MemoryIngestMode) {
		return true
	}

	return false
}

// SetMemoryIngestMode gets a reference to the given string and assigns it to the MemoryIngestMode field.
func (o *CodebaseRouteRequest) SetMemoryIngestMode(v string) {
	o.MemoryIngestMode = &v
}

func (o CodebaseRouteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseRouteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["item_ids"] = o.ItemIds
	toSerialize["target"] = o.Target
	if !IsNil(o.QueueMemoryImport) {
		toSerialize["queue_memory_import"] = o.QueueMemoryImport
	}
	if !IsNil(o.MemoryIngestMode) {
		toSerialize["memory_ingest_mode"] = o.MemoryIngestMode
	}
	return toSerialize, nil
}

func (o *CodebaseRouteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"item_ids",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseRouteRequest := _CodebaseRouteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseRouteRequest)

	if err != nil {
		return err
	}

	*o = CodebaseRouteRequest(varCodebaseRouteRequest)

	return err
}

type NullableCodebaseRouteRequest struct {
	value *CodebaseRouteRequest
	isSet bool
}

func (v NullableCodebaseRouteRequest) Get() *CodebaseRouteRequest {
	return v.value
}

func (v *NullableCodebaseRouteRequest) Set(val *CodebaseRouteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseRouteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseRouteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseRouteRequest(val *CodebaseRouteRequest) *NullableCodebaseRouteRequest {
	return &NullableCodebaseRouteRequest{value: val, isSet: true}
}

func (v NullableCodebaseRouteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseRouteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


