/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimelineEdgeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineEdgeResponse{}

// TimelineEdgeResponse struct for TimelineEdgeResponse
type TimelineEdgeResponse struct {
	Source string `json:"source"`
	Target string `json:"target"`
	EdgeKind string `json:"edge_kind"`
	Weight *float32 `json:"weight,omitempty"`
}

type _TimelineEdgeResponse TimelineEdgeResponse

// NewTimelineEdgeResponse instantiates a new TimelineEdgeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineEdgeResponse(source string, target string, edgeKind string) *TimelineEdgeResponse {
	this := TimelineEdgeResponse{}
	this.Source = source
	this.Target = target
	this.EdgeKind = edgeKind
	return &this
}

// NewTimelineEdgeResponseWithDefaults instantiates a new TimelineEdgeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineEdgeResponseWithDefaults() *TimelineEdgeResponse {
	this := TimelineEdgeResponse{}
	return &this
}

// GetSource returns the Source field value
func (o *TimelineEdgeResponse) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TimelineEdgeResponse) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TimelineEdgeResponse) SetSource(v string) {
	o.Source = v
}

// GetTarget returns the Target field value
func (o *TimelineEdgeResponse) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *TimelineEdgeResponse) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *TimelineEdgeResponse) SetTarget(v string) {
	o.Target = v
}

// GetEdgeKind returns the EdgeKind field value
func (o *TimelineEdgeResponse) GetEdgeKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EdgeKind
}

// GetEdgeKindOk returns a tuple with the EdgeKind field value
// and a boolean to check if the value has been set.
func (o *TimelineEdgeResponse) GetEdgeKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EdgeKind, true
}

// SetEdgeKind sets field value
func (o *TimelineEdgeResponse) SetEdgeKind(v string) {
	o.EdgeKind = v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *TimelineEdgeResponse) GetWeight() float32 {
	if o == nil || IsNil(o.Weight) {
		var ret float32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineEdgeResponse) GetWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *TimelineEdgeResponse) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float32 and assigns it to the Weight field.
func (o *TimelineEdgeResponse) SetWeight(v float32) {
	o.Weight = &v
}

func (o TimelineEdgeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineEdgeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["target"] = o.Target
	toSerialize["edge_kind"] = o.EdgeKind
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	return toSerialize, nil
}

func (o *TimelineEdgeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"target",
		"edge_kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimelineEdgeResponse := _TimelineEdgeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimelineEdgeResponse)

	if err != nil {
		return err
	}

	*o = TimelineEdgeResponse(varTimelineEdgeResponse)

	return err
}

type NullableTimelineEdgeResponse struct {
	value *TimelineEdgeResponse
	isSet bool
}

func (v NullableTimelineEdgeResponse) Get() *TimelineEdgeResponse {
	return v.value
}

func (v *NullableTimelineEdgeResponse) Set(val *TimelineEdgeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineEdgeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineEdgeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineEdgeResponse(val *TimelineEdgeResponse) *NullableTimelineEdgeResponse {
	return &NullableTimelineEdgeResponse{value: val, isSet: true}
}

func (v NullableTimelineEdgeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineEdgeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


