/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnomalyCorrectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnomalyCorrectionResponse{}

// AnomalyCorrectionResponse struct for AnomalyCorrectionResponse
type AnomalyCorrectionResponse struct {
	Id string `json:"id"`
	BankId string `json:"bank_id"`
	AnomalyId string `json:"anomaly_id"`
	CorrectionType string `json:"correction_type"`
	TargetUnitId NullableString `json:"target_unit_id,omitempty"`
	BeforeState map[string]interface{} `json:"before_state,omitempty"`
	AfterState map[string]interface{} `json:"after_state,omitempty"`
	ConfidenceDelta NullableFloat32 `json:"confidence_delta,omitempty"`
	AppliedAt NullableString `json:"applied_at,omitempty"`
	AppliedBy string `json:"applied_by"`
}

type _AnomalyCorrectionResponse AnomalyCorrectionResponse

// NewAnomalyCorrectionResponse instantiates a new AnomalyCorrectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnomalyCorrectionResponse(id string, bankId string, anomalyId string, correctionType string, appliedBy string) *AnomalyCorrectionResponse {
	this := AnomalyCorrectionResponse{}
	this.Id = id
	this.BankId = bankId
	this.AnomalyId = anomalyId
	this.CorrectionType = correctionType
	this.AppliedBy = appliedBy
	return &this
}

// NewAnomalyCorrectionResponseWithDefaults instantiates a new AnomalyCorrectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnomalyCorrectionResponseWithDefaults() *AnomalyCorrectionResponse {
	this := AnomalyCorrectionResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AnomalyCorrectionResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AnomalyCorrectionResponse) SetId(v string) {
	o.Id = v
}

// GetBankId returns the BankId field value
func (o *AnomalyCorrectionResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *AnomalyCorrectionResponse) SetBankId(v string) {
	o.BankId = v
}

// GetAnomalyId returns the AnomalyId field value
func (o *AnomalyCorrectionResponse) GetAnomalyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AnomalyId
}

// GetAnomalyIdOk returns a tuple with the AnomalyId field value
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetAnomalyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AnomalyId, true
}

// SetAnomalyId sets field value
func (o *AnomalyCorrectionResponse) SetAnomalyId(v string) {
	o.AnomalyId = v
}

// GetCorrectionType returns the CorrectionType field value
func (o *AnomalyCorrectionResponse) GetCorrectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CorrectionType
}

// GetCorrectionTypeOk returns a tuple with the CorrectionType field value
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetCorrectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorrectionType, true
}

// SetCorrectionType sets field value
func (o *AnomalyCorrectionResponse) SetCorrectionType(v string) {
	o.CorrectionType = v
}

// GetTargetUnitId returns the TargetUnitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyCorrectionResponse) GetTargetUnitId() string {
	if o == nil || IsNil(o.TargetUnitId.Get()) {
		var ret string
		return ret
	}
	return *o.TargetUnitId.Get()
}

// GetTargetUnitIdOk returns a tuple with the TargetUnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyCorrectionResponse) GetTargetUnitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetUnitId.Get(), o.TargetUnitId.IsSet()
}

// HasTargetUnitId returns a boolean if a field has been set.
func (o *AnomalyCorrectionResponse) HasTargetUnitId() bool {
	if o != nil && o.TargetUnitId.IsSet() {
		return true
	}

	return false
}

// SetTargetUnitId gets a reference to the given NullableString and assigns it to the TargetUnitId field.
func (o *AnomalyCorrectionResponse) SetTargetUnitId(v string) {
	o.TargetUnitId.Set(&v)
}
// SetTargetUnitIdNil sets the value for TargetUnitId to be an explicit nil
func (o *AnomalyCorrectionResponse) SetTargetUnitIdNil() {
	o.TargetUnitId.Set(nil)
}

// UnsetTargetUnitId ensures that no value is present for TargetUnitId, not even an explicit nil
func (o *AnomalyCorrectionResponse) UnsetTargetUnitId() {
	o.TargetUnitId.Unset()
}

// GetBeforeState returns the BeforeState field value if set, zero value otherwise.
func (o *AnomalyCorrectionResponse) GetBeforeState() map[string]interface{} {
	if o == nil || IsNil(o.BeforeState) {
		var ret map[string]interface{}
		return ret
	}
	return o.BeforeState
}

// GetBeforeStateOk returns a tuple with the BeforeState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetBeforeStateOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.BeforeState) {
		return map[string]interface{}{}, false
	}
	return o.BeforeState, true
}

// HasBeforeState returns a boolean if a field has been set.
func (o *AnomalyCorrectionResponse) HasBeforeState() bool {
	if o != nil && !IsNil(o.BeforeState) {
		return true
	}

	return false
}

// SetBeforeState gets a reference to the given map[string]interface{} and assigns it to the BeforeState field.
func (o *AnomalyCorrectionResponse) SetBeforeState(v map[string]interface{}) {
	o.BeforeState = v
}

// GetAfterState returns the AfterState field value if set, zero value otherwise.
func (o *AnomalyCorrectionResponse) GetAfterState() map[string]interface{} {
	if o == nil || IsNil(o.AfterState) {
		var ret map[string]interface{}
		return ret
	}
	return o.AfterState
}

// GetAfterStateOk returns a tuple with the AfterState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetAfterStateOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AfterState) {
		return map[string]interface{}{}, false
	}
	return o.AfterState, true
}

// HasAfterState returns a boolean if a field has been set.
func (o *AnomalyCorrectionResponse) HasAfterState() bool {
	if o != nil && !IsNil(o.AfterState) {
		return true
	}

	return false
}

// SetAfterState gets a reference to the given map[string]interface{} and assigns it to the AfterState field.
func (o *AnomalyCorrectionResponse) SetAfterState(v map[string]interface{}) {
	o.AfterState = v
}

// GetConfidenceDelta returns the ConfidenceDelta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyCorrectionResponse) GetConfidenceDelta() float32 {
	if o == nil || IsNil(o.ConfidenceDelta.Get()) {
		var ret float32
		return ret
	}
	return *o.ConfidenceDelta.Get()
}

// GetConfidenceDeltaOk returns a tuple with the ConfidenceDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyCorrectionResponse) GetConfidenceDeltaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfidenceDelta.Get(), o.ConfidenceDelta.IsSet()
}

// HasConfidenceDelta returns a boolean if a field has been set.
func (o *AnomalyCorrectionResponse) HasConfidenceDelta() bool {
	if o != nil && o.ConfidenceDelta.IsSet() {
		return true
	}

	return false
}

// SetConfidenceDelta gets a reference to the given NullableFloat32 and assigns it to the ConfidenceDelta field.
func (o *AnomalyCorrectionResponse) SetConfidenceDelta(v float32) {
	o.ConfidenceDelta.Set(&v)
}
// SetConfidenceDeltaNil sets the value for ConfidenceDelta to be an explicit nil
func (o *AnomalyCorrectionResponse) SetConfidenceDeltaNil() {
	o.ConfidenceDelta.Set(nil)
}

// UnsetConfidenceDelta ensures that no value is present for ConfidenceDelta, not even an explicit nil
func (o *AnomalyCorrectionResponse) UnsetConfidenceDelta() {
	o.ConfidenceDelta.Unset()
}

// GetAppliedAt returns the AppliedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnomalyCorrectionResponse) GetAppliedAt() string {
	if o == nil || IsNil(o.AppliedAt.Get()) {
		var ret string
		return ret
	}
	return *o.AppliedAt.Get()
}

// GetAppliedAtOk returns a tuple with the AppliedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnomalyCorrectionResponse) GetAppliedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppliedAt.Get(), o.AppliedAt.IsSet()
}

// HasAppliedAt returns a boolean if a field has been set.
func (o *AnomalyCorrectionResponse) HasAppliedAt() bool {
	if o != nil && o.AppliedAt.IsSet() {
		return true
	}

	return false
}

// SetAppliedAt gets a reference to the given NullableString and assigns it to the AppliedAt field.
func (o *AnomalyCorrectionResponse) SetAppliedAt(v string) {
	o.AppliedAt.Set(&v)
}
// SetAppliedAtNil sets the value for AppliedAt to be an explicit nil
func (o *AnomalyCorrectionResponse) SetAppliedAtNil() {
	o.AppliedAt.Set(nil)
}

// UnsetAppliedAt ensures that no value is present for AppliedAt, not even an explicit nil
func (o *AnomalyCorrectionResponse) UnsetAppliedAt() {
	o.AppliedAt.Unset()
}

// GetAppliedBy returns the AppliedBy field value
func (o *AnomalyCorrectionResponse) GetAppliedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppliedBy
}

// GetAppliedByOk returns a tuple with the AppliedBy field value
// and a boolean to check if the value has been set.
func (o *AnomalyCorrectionResponse) GetAppliedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppliedBy, true
}

// SetAppliedBy sets field value
func (o *AnomalyCorrectionResponse) SetAppliedBy(v string) {
	o.AppliedBy = v
}

func (o AnomalyCorrectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnomalyCorrectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["bank_id"] = o.BankId
	toSerialize["anomaly_id"] = o.AnomalyId
	toSerialize["correction_type"] = o.CorrectionType
	if o.TargetUnitId.IsSet() {
		toSerialize["target_unit_id"] = o.TargetUnitId.Get()
	}
	if !IsNil(o.BeforeState) {
		toSerialize["before_state"] = o.BeforeState
	}
	if !IsNil(o.AfterState) {
		toSerialize["after_state"] = o.AfterState
	}
	if o.ConfidenceDelta.IsSet() {
		toSerialize["confidence_delta"] = o.ConfidenceDelta.Get()
	}
	if o.AppliedAt.IsSet() {
		toSerialize["applied_at"] = o.AppliedAt.Get()
	}
	toSerialize["applied_by"] = o.AppliedBy
	return toSerialize, nil
}

func (o *AnomalyCorrectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"bank_id",
		"anomaly_id",
		"correction_type",
		"applied_by",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnomalyCorrectionResponse := _AnomalyCorrectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnomalyCorrectionResponse)

	if err != nil {
		return err
	}

	*o = AnomalyCorrectionResponse(varAnomalyCorrectionResponse)

	return err
}

type NullableAnomalyCorrectionResponse struct {
	value *AnomalyCorrectionResponse
	isSet bool
}

func (v NullableAnomalyCorrectionResponse) Get() *AnomalyCorrectionResponse {
	return v.value
}

func (v *NullableAnomalyCorrectionResponse) Set(val *AnomalyCorrectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnomalyCorrectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnomalyCorrectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnomalyCorrectionResponse(val *AnomalyCorrectionResponse) *NullableAnomalyCorrectionResponse {
	return &NullableAnomalyCorrectionResponse{value: val, isSet: true}
}

func (v NullableAnomalyCorrectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnomalyCorrectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


