/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrgResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgResponse{}

// OrgResponse struct for OrgResponse
type OrgResponse struct {
	Id string `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
	SchemaName string `json:"schema_name"`
	Status string `json:"status"`
	CreatedAt string `json:"created_at"`
}

type _OrgResponse OrgResponse

// NewOrgResponse instantiates a new OrgResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgResponse(id string, slug string, name string, schemaName string, status string, createdAt string) *OrgResponse {
	this := OrgResponse{}
	this.Id = id
	this.Slug = slug
	this.Name = name
	this.SchemaName = schemaName
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewOrgResponseWithDefaults instantiates a new OrgResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgResponseWithDefaults() *OrgResponse {
	this := OrgResponse{}
	return &this
}

// GetId returns the Id field value
func (o *OrgResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrgResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrgResponse) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *OrgResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *OrgResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *OrgResponse) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *OrgResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrgResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrgResponse) SetName(v string) {
	o.Name = v
}

// GetSchemaName returns the SchemaName field value
func (o *OrgResponse) GetSchemaName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaName
}

// GetSchemaNameOk returns a tuple with the SchemaName field value
// and a boolean to check if the value has been set.
func (o *OrgResponse) GetSchemaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaName, true
}

// SetSchemaName sets field value
func (o *OrgResponse) SetSchemaName(v string) {
	o.SchemaName = v
}

// GetStatus returns the Status field value
func (o *OrgResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OrgResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OrgResponse) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrgResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrgResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrgResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o OrgResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name
	toSerialize["schema_name"] = o.SchemaName
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *OrgResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"name",
		"schema_name",
		"status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgResponse := _OrgResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgResponse)

	if err != nil {
		return err
	}

	*o = OrgResponse(varOrgResponse)

	return err
}

type NullableOrgResponse struct {
	value *OrgResponse
	isSet bool
}

func (v NullableOrgResponse) Get() *OrgResponse {
	return v.value
}

func (v *NullableOrgResponse) Set(val *OrgResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgResponse(val *OrgResponse) *NullableOrgResponse {
	return &NullableOrgResponse{value: val, isSet: true}
}

func (v NullableOrgResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
