/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DirectGrantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectGrantRequest{}

// DirectGrantRequest struct for DirectGrantRequest
type DirectGrantRequest struct {
	PrincipalId string `json:"principal_id"`
	Action      string `json:"action"`
	ScopeType   string `json:"scope_type"`
	ScopeId     string `json:"scope_id"`
}

type _DirectGrantRequest DirectGrantRequest

// NewDirectGrantRequest instantiates a new DirectGrantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectGrantRequest(principalId string, action string, scopeType string, scopeId string) *DirectGrantRequest {
	this := DirectGrantRequest{}
	this.PrincipalId = principalId
	this.Action = action
	this.ScopeType = scopeType
	this.ScopeId = scopeId
	return &this
}

// NewDirectGrantRequestWithDefaults instantiates a new DirectGrantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectGrantRequestWithDefaults() *DirectGrantRequest {
	this := DirectGrantRequest{}
	return &this
}

// GetPrincipalId returns the PrincipalId field value
func (o *DirectGrantRequest) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *DirectGrantRequest) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *DirectGrantRequest) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetAction returns the Action field value
func (o *DirectGrantRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *DirectGrantRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *DirectGrantRequest) SetAction(v string) {
	o.Action = v
}

// GetScopeType returns the ScopeType field value
func (o *DirectGrantRequest) GetScopeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeType
}

// GetScopeTypeOk returns a tuple with the ScopeType field value
// and a boolean to check if the value has been set.
func (o *DirectGrantRequest) GetScopeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeType, true
}

// SetScopeType sets field value
func (o *DirectGrantRequest) SetScopeType(v string) {
	o.ScopeType = v
}

// GetScopeId returns the ScopeId field value
func (o *DirectGrantRequest) GetScopeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value
// and a boolean to check if the value has been set.
func (o *DirectGrantRequest) GetScopeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeId, true
}

// SetScopeId sets field value
func (o *DirectGrantRequest) SetScopeId(v string) {
	o.ScopeId = v
}

func (o DirectGrantRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectGrantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principal_id"] = o.PrincipalId
	toSerialize["action"] = o.Action
	toSerialize["scope_type"] = o.ScopeType
	toSerialize["scope_id"] = o.ScopeId
	return toSerialize, nil
}

func (o *DirectGrantRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principal_id",
		"action",
		"scope_type",
		"scope_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectGrantRequest := _DirectGrantRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectGrantRequest)

	if err != nil {
		return err
	}

	*o = DirectGrantRequest(varDirectGrantRequest)

	return err
}

type NullableDirectGrantRequest struct {
	value *DirectGrantRequest
	isSet bool
}

func (v NullableDirectGrantRequest) Get() *DirectGrantRequest {
	return v.value
}

func (v *NullableDirectGrantRequest) Set(val *DirectGrantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectGrantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectGrantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectGrantRequest(val *DirectGrantRequest) *NullableDirectGrantRequest {
	return &NullableDirectGrantRequest{value: val, isSet: true}
}

func (v NullableDirectGrantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectGrantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
