/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InternetResearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternetResearchRequest{}

// InternetResearchRequest Request live-web research (optional SearXNG + Firecrawl stack). Does not use bank memory as context.
type InternetResearchRequest struct {
	// Question to answer using the public web only
	Query string `json:"query"`
	Budget *Budget `json:"budget,omitempty"`
	// Max completion tokens for each LLM step where supported
	MaxTokens *int32 `json:"max_tokens,omitempty"`
	// Optional tool trace (include.facts is ignored).
	Include *ReflectIncludeOptions `json:"include,omitempty"`
}

type _InternetResearchRequest InternetResearchRequest

// NewInternetResearchRequest instantiates a new InternetResearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternetResearchRequest(query string) *InternetResearchRequest {
	this := InternetResearchRequest{}
	this.Query = query
	return &this
}

// NewInternetResearchRequestWithDefaults instantiates a new InternetResearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternetResearchRequestWithDefaults() *InternetResearchRequest {
	this := InternetResearchRequest{}
	return &this
}

// GetQuery returns the Query field value
func (o *InternetResearchRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *InternetResearchRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *InternetResearchRequest) SetQuery(v string) {
	o.Query = v
}

// GetBudget returns the Budget field value if set, zero value otherwise.
func (o *InternetResearchRequest) GetBudget() Budget {
	if o == nil || IsNil(o.Budget) {
		var ret Budget
		return ret
	}
	return *o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternetResearchRequest) GetBudgetOk() (*Budget, bool) {
	if o == nil || IsNil(o.Budget) {
		return nil, false
	}
	return o.Budget, true
}

// HasBudget returns a boolean if a field has been set.
func (o *InternetResearchRequest) HasBudget() bool {
	if o != nil && !IsNil(o.Budget) {
		return true
	}

	return false
}

// SetBudget gets a reference to the given Budget and assigns it to the Budget field.
func (o *InternetResearchRequest) SetBudget(v Budget) {
	o.Budget = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *InternetResearchRequest) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternetResearchRequest) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *InternetResearchRequest) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *InternetResearchRequest) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetInclude returns the Include field value if set, zero value otherwise.
func (o *InternetResearchRequest) GetInclude() ReflectIncludeOptions {
	if o == nil || IsNil(o.Include) {
		var ret ReflectIncludeOptions
		return ret
	}
	return *o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternetResearchRequest) GetIncludeOk() (*ReflectIncludeOptions, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *InternetResearchRequest) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given ReflectIncludeOptions and assigns it to the Include field.
func (o *InternetResearchRequest) SetInclude(v ReflectIncludeOptions) {
	o.Include = &v
}

func (o InternetResearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternetResearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Budget) {
		toSerialize["budget"] = o.Budget
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if !IsNil(o.Include) {
		toSerialize["include"] = o.Include
	}
	return toSerialize, nil
}

func (o *InternetResearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInternetResearchRequest := _InternetResearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInternetResearchRequest)

	if err != nil {
		return err
	}

	*o = InternetResearchRequest(varInternetResearchRequest)

	return err
}

type NullableInternetResearchRequest struct {
	value *InternetResearchRequest
	isSet bool
}

func (v NullableInternetResearchRequest) Get() *InternetResearchRequest {
	return v.value
}

func (v *NullableInternetResearchRequest) Set(val *InternetResearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInternetResearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInternetResearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternetResearchRequest(val *InternetResearchRequest) *NullableInternetResearchRequest {
	return &NullableInternetResearchRequest{value: val, isSet: true}
}

func (v NullableInternetResearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternetResearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


