/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
)

// checks if the DreamSubmitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DreamSubmitRequest{}

// DreamSubmitRequest struct for DreamSubmitRequest
type DreamSubmitRequest struct {
	// manual | event | cron
	TriggerSource *string `json:"trigger_source,omitempty"`
	// dream | trance
	RunType *string `json:"run_type,omitempty"`
}

// NewDreamSubmitRequest instantiates a new DreamSubmitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDreamSubmitRequest() *DreamSubmitRequest {
	this := DreamSubmitRequest{}
	return &this
}

// NewDreamSubmitRequestWithDefaults instantiates a new DreamSubmitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDreamSubmitRequestWithDefaults() *DreamSubmitRequest {
	this := DreamSubmitRequest{}
	return &this
}

// GetTriggerSource returns the TriggerSource field value if set, zero value otherwise.
func (o *DreamSubmitRequest) GetTriggerSource() string {
	if o == nil || IsNil(o.TriggerSource) {
		var ret string
		return ret
	}
	return *o.TriggerSource
}

// GetTriggerSourceOk returns a tuple with the TriggerSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamSubmitRequest) GetTriggerSourceOk() (*string, bool) {
	if o == nil || IsNil(o.TriggerSource) {
		return nil, false
	}
	return o.TriggerSource, true
}

// HasTriggerSource returns a boolean if a field has been set.
func (o *DreamSubmitRequest) HasTriggerSource() bool {
	if o != nil && !IsNil(o.TriggerSource) {
		return true
	}

	return false
}

// SetTriggerSource gets a reference to the given string and assigns it to the TriggerSource field.
func (o *DreamSubmitRequest) SetTriggerSource(v string) {
	o.TriggerSource = &v
}

// GetRunType returns the RunType field value if set, zero value otherwise.
func (o *DreamSubmitRequest) GetRunType() string {
	if o == nil || IsNil(o.RunType) {
		var ret string
		return ret
	}
	return *o.RunType
}

// GetRunTypeOk returns a tuple with the RunType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DreamSubmitRequest) GetRunTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RunType) {
		return nil, false
	}
	return o.RunType, true
}

// HasRunType returns a boolean if a field has been set.
func (o *DreamSubmitRequest) HasRunType() bool {
	if o != nil && !IsNil(o.RunType) {
		return true
	}

	return false
}

// SetRunType gets a reference to the given string and assigns it to the RunType field.
func (o *DreamSubmitRequest) SetRunType(v string) {
	o.RunType = &v
}

func (o DreamSubmitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DreamSubmitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TriggerSource) {
		toSerialize["trigger_source"] = o.TriggerSource
	}
	if !IsNil(o.RunType) {
		toSerialize["run_type"] = o.RunType
	}
	return toSerialize, nil
}

type NullableDreamSubmitRequest struct {
	value *DreamSubmitRequest
	isSet bool
}

func (v NullableDreamSubmitRequest) Get() *DreamSubmitRequest {
	return v.value
}

func (v *NullableDreamSubmitRequest) Set(val *DreamSubmitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDreamSubmitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDreamSubmitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDreamSubmitRequest(val *DreamSubmitRequest) *NullableDreamSubmitRequest {
	return &NullableDreamSubmitRequest{value: val, isSet: true}
}

func (v NullableDreamSubmitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDreamSubmitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


