/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GraphSummaryEdgeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphSummaryEdgeResponse{}

// GraphSummaryEdgeResponse struct for GraphSummaryEdgeResponse
type GraphSummaryEdgeResponse struct {
	Id string `json:"id"`
	SourceId string `json:"source_id"`
	TargetId string `json:"target_id"`
	Weight float32 `json:"weight"`
	Label NullableString `json:"label,omitempty"`
}

type _GraphSummaryEdgeResponse GraphSummaryEdgeResponse

// NewGraphSummaryEdgeResponse instantiates a new GraphSummaryEdgeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphSummaryEdgeResponse(id string, sourceId string, targetId string, weight float32) *GraphSummaryEdgeResponse {
	this := GraphSummaryEdgeResponse{}
	this.Id = id
	this.SourceId = sourceId
	this.TargetId = targetId
	this.Weight = weight
	return &this
}

// NewGraphSummaryEdgeResponseWithDefaults instantiates a new GraphSummaryEdgeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphSummaryEdgeResponseWithDefaults() *GraphSummaryEdgeResponse {
	this := GraphSummaryEdgeResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GraphSummaryEdgeResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GraphSummaryEdgeResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GraphSummaryEdgeResponse) SetId(v string) {
	o.Id = v
}

// GetSourceId returns the SourceId field value
func (o *GraphSummaryEdgeResponse) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *GraphSummaryEdgeResponse) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *GraphSummaryEdgeResponse) SetSourceId(v string) {
	o.SourceId = v
}

// GetTargetId returns the TargetId field value
func (o *GraphSummaryEdgeResponse) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *GraphSummaryEdgeResponse) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *GraphSummaryEdgeResponse) SetTargetId(v string) {
	o.TargetId = v
}

// GetWeight returns the Weight field value
func (o *GraphSummaryEdgeResponse) GetWeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *GraphSummaryEdgeResponse) GetWeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *GraphSummaryEdgeResponse) SetWeight(v float32) {
	o.Weight = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GraphSummaryEdgeResponse) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GraphSummaryEdgeResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *GraphSummaryEdgeResponse) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *GraphSummaryEdgeResponse) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *GraphSummaryEdgeResponse) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *GraphSummaryEdgeResponse) UnsetLabel() {
	o.Label.Unset()
}

func (o GraphSummaryEdgeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphSummaryEdgeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["source_id"] = o.SourceId
	toSerialize["target_id"] = o.TargetId
	toSerialize["weight"] = o.Weight
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	return toSerialize, nil
}

func (o *GraphSummaryEdgeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"source_id",
		"target_id",
		"weight",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGraphSummaryEdgeResponse := _GraphSummaryEdgeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGraphSummaryEdgeResponse)

	if err != nil {
		return err
	}

	*o = GraphSummaryEdgeResponse(varGraphSummaryEdgeResponse)

	return err
}

type NullableGraphSummaryEdgeResponse struct {
	value *GraphSummaryEdgeResponse
	isSet bool
}

func (v NullableGraphSummaryEdgeResponse) Get() *GraphSummaryEdgeResponse {
	return v.value
}

func (v *NullableGraphSummaryEdgeResponse) Set(val *GraphSummaryEdgeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphSummaryEdgeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphSummaryEdgeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphSummaryEdgeResponse(val *GraphSummaryEdgeResponse) *NullableGraphSummaryEdgeResponse {
	return &NullableGraphSummaryEdgeResponse{value: val, isSet: true}
}

func (v NullableGraphSummaryEdgeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphSummaryEdgeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


