/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemoryRepoForkBankResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryRepoForkBankResponse{}

// MemoryRepoForkBankResponse struct for MemoryRepoForkBankResponse
type MemoryRepoForkBankResponse struct {
	BankId string `json:"bank_id"`
	BankName NullableString `json:"bank_name,omitempty"`
	SourceRepoId string `json:"source_repo_id"`
	SourceRef string `json:"source_ref"`
	SourceBranch NullableString `json:"source_branch,omitempty"`
	SourceCommitId NullableString `json:"source_commit_id,omitempty"`
	IncludeWorkspace bool `json:"include_workspace"`
	RepoEnabled bool `json:"repo_enabled"`
	Repo NullableMemoryRepoSummaryResponse `json:"repo,omitempty"`
}

type _MemoryRepoForkBankResponse MemoryRepoForkBankResponse

// NewMemoryRepoForkBankResponse instantiates a new MemoryRepoForkBankResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryRepoForkBankResponse(bankId string, sourceRepoId string, sourceRef string, includeWorkspace bool, repoEnabled bool) *MemoryRepoForkBankResponse {
	this := MemoryRepoForkBankResponse{}
	this.BankId = bankId
	this.SourceRepoId = sourceRepoId
	this.SourceRef = sourceRef
	this.IncludeWorkspace = includeWorkspace
	this.RepoEnabled = repoEnabled
	return &this
}

// NewMemoryRepoForkBankResponseWithDefaults instantiates a new MemoryRepoForkBankResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryRepoForkBankResponseWithDefaults() *MemoryRepoForkBankResponse {
	this := MemoryRepoForkBankResponse{}
	return &this
}

// GetBankId returns the BankId field value
func (o *MemoryRepoForkBankResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoForkBankResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *MemoryRepoForkBankResponse) SetBankId(v string) {
	o.BankId = v
}

// GetBankName returns the BankName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryRepoForkBankResponse) GetBankName() string {
	if o == nil || IsNil(o.BankName.Get()) {
		var ret string
		return ret
	}
	return *o.BankName.Get()
}

// GetBankNameOk returns a tuple with the BankName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRepoForkBankResponse) GetBankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BankName.Get(), o.BankName.IsSet()
}

// HasBankName returns a boolean if a field has been set.
func (o *MemoryRepoForkBankResponse) HasBankName() bool {
	if o != nil && o.BankName.IsSet() {
		return true
	}

	return false
}

// SetBankName gets a reference to the given NullableString and assigns it to the BankName field.
func (o *MemoryRepoForkBankResponse) SetBankName(v string) {
	o.BankName.Set(&v)
}
// SetBankNameNil sets the value for BankName to be an explicit nil
func (o *MemoryRepoForkBankResponse) SetBankNameNil() {
	o.BankName.Set(nil)
}

// UnsetBankName ensures that no value is present for BankName, not even an explicit nil
func (o *MemoryRepoForkBankResponse) UnsetBankName() {
	o.BankName.Unset()
}

// GetSourceRepoId returns the SourceRepoId field value
func (o *MemoryRepoForkBankResponse) GetSourceRepoId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRepoId
}

// GetSourceRepoIdOk returns a tuple with the SourceRepoId field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoForkBankResponse) GetSourceRepoIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRepoId, true
}

// SetSourceRepoId sets field value
func (o *MemoryRepoForkBankResponse) SetSourceRepoId(v string) {
	o.SourceRepoId = v
}

// GetSourceRef returns the SourceRef field value
func (o *MemoryRepoForkBankResponse) GetSourceRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRef
}

// GetSourceRefOk returns a tuple with the SourceRef field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoForkBankResponse) GetSourceRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRef, true
}

// SetSourceRef sets field value
func (o *MemoryRepoForkBankResponse) SetSourceRef(v string) {
	o.SourceRef = v
}

// GetSourceBranch returns the SourceBranch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryRepoForkBankResponse) GetSourceBranch() string {
	if o == nil || IsNil(o.SourceBranch.Get()) {
		var ret string
		return ret
	}
	return *o.SourceBranch.Get()
}

// GetSourceBranchOk returns a tuple with the SourceBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRepoForkBankResponse) GetSourceBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceBranch.Get(), o.SourceBranch.IsSet()
}

// HasSourceBranch returns a boolean if a field has been set.
func (o *MemoryRepoForkBankResponse) HasSourceBranch() bool {
	if o != nil && o.SourceBranch.IsSet() {
		return true
	}

	return false
}

// SetSourceBranch gets a reference to the given NullableString and assigns it to the SourceBranch field.
func (o *MemoryRepoForkBankResponse) SetSourceBranch(v string) {
	o.SourceBranch.Set(&v)
}
// SetSourceBranchNil sets the value for SourceBranch to be an explicit nil
func (o *MemoryRepoForkBankResponse) SetSourceBranchNil() {
	o.SourceBranch.Set(nil)
}

// UnsetSourceBranch ensures that no value is present for SourceBranch, not even an explicit nil
func (o *MemoryRepoForkBankResponse) UnsetSourceBranch() {
	o.SourceBranch.Unset()
}

// GetSourceCommitId returns the SourceCommitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryRepoForkBankResponse) GetSourceCommitId() string {
	if o == nil || IsNil(o.SourceCommitId.Get()) {
		var ret string
		return ret
	}
	return *o.SourceCommitId.Get()
}

// GetSourceCommitIdOk returns a tuple with the SourceCommitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRepoForkBankResponse) GetSourceCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceCommitId.Get(), o.SourceCommitId.IsSet()
}

// HasSourceCommitId returns a boolean if a field has been set.
func (o *MemoryRepoForkBankResponse) HasSourceCommitId() bool {
	if o != nil && o.SourceCommitId.IsSet() {
		return true
	}

	return false
}

// SetSourceCommitId gets a reference to the given NullableString and assigns it to the SourceCommitId field.
func (o *MemoryRepoForkBankResponse) SetSourceCommitId(v string) {
	o.SourceCommitId.Set(&v)
}
// SetSourceCommitIdNil sets the value for SourceCommitId to be an explicit nil
func (o *MemoryRepoForkBankResponse) SetSourceCommitIdNil() {
	o.SourceCommitId.Set(nil)
}

// UnsetSourceCommitId ensures that no value is present for SourceCommitId, not even an explicit nil
func (o *MemoryRepoForkBankResponse) UnsetSourceCommitId() {
	o.SourceCommitId.Unset()
}

// GetIncludeWorkspace returns the IncludeWorkspace field value
func (o *MemoryRepoForkBankResponse) GetIncludeWorkspace() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeWorkspace
}

// GetIncludeWorkspaceOk returns a tuple with the IncludeWorkspace field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoForkBankResponse) GetIncludeWorkspaceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeWorkspace, true
}

// SetIncludeWorkspace sets field value
func (o *MemoryRepoForkBankResponse) SetIncludeWorkspace(v bool) {
	o.IncludeWorkspace = v
}

// GetRepoEnabled returns the RepoEnabled field value
func (o *MemoryRepoForkBankResponse) GetRepoEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RepoEnabled
}

// GetRepoEnabledOk returns a tuple with the RepoEnabled field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoForkBankResponse) GetRepoEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoEnabled, true
}

// SetRepoEnabled sets field value
func (o *MemoryRepoForkBankResponse) SetRepoEnabled(v bool) {
	o.RepoEnabled = v
}

// GetRepo returns the Repo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryRepoForkBankResponse) GetRepo() MemoryRepoSummaryResponse {
	if o == nil || IsNil(o.Repo.Get()) {
		var ret MemoryRepoSummaryResponse
		return ret
	}
	return *o.Repo.Get()
}

// GetRepoOk returns a tuple with the Repo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRepoForkBankResponse) GetRepoOk() (*MemoryRepoSummaryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Repo.Get(), o.Repo.IsSet()
}

// HasRepo returns a boolean if a field has been set.
func (o *MemoryRepoForkBankResponse) HasRepo() bool {
	if o != nil && o.Repo.IsSet() {
		return true
	}

	return false
}

// SetRepo gets a reference to the given NullableMemoryRepoSummaryResponse and assigns it to the Repo field.
func (o *MemoryRepoForkBankResponse) SetRepo(v MemoryRepoSummaryResponse) {
	o.Repo.Set(&v)
}
// SetRepoNil sets the value for Repo to be an explicit nil
func (o *MemoryRepoForkBankResponse) SetRepoNil() {
	o.Repo.Set(nil)
}

// UnsetRepo ensures that no value is present for Repo, not even an explicit nil
func (o *MemoryRepoForkBankResponse) UnsetRepo() {
	o.Repo.Unset()
}

func (o MemoryRepoForkBankResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryRepoForkBankResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bank_id"] = o.BankId
	if o.BankName.IsSet() {
		toSerialize["bank_name"] = o.BankName.Get()
	}
	toSerialize["source_repo_id"] = o.SourceRepoId
	toSerialize["source_ref"] = o.SourceRef
	if o.SourceBranch.IsSet() {
		toSerialize["source_branch"] = o.SourceBranch.Get()
	}
	if o.SourceCommitId.IsSet() {
		toSerialize["source_commit_id"] = o.SourceCommitId.Get()
	}
	toSerialize["include_workspace"] = o.IncludeWorkspace
	toSerialize["repo_enabled"] = o.RepoEnabled
	if o.Repo.IsSet() {
		toSerialize["repo"] = o.Repo.Get()
	}
	return toSerialize, nil
}

func (o *MemoryRepoForkBankResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"source_repo_id",
		"source_ref",
		"include_workspace",
		"repo_enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryRepoForkBankResponse := _MemoryRepoForkBankResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryRepoForkBankResponse)

	if err != nil {
		return err
	}

	*o = MemoryRepoForkBankResponse(varMemoryRepoForkBankResponse)

	return err
}

type NullableMemoryRepoForkBankResponse struct {
	value *MemoryRepoForkBankResponse
	isSet bool
}

func (v NullableMemoryRepoForkBankResponse) Get() *MemoryRepoForkBankResponse {
	return v.value
}

func (v *NullableMemoryRepoForkBankResponse) Set(val *MemoryRepoForkBankResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryRepoForkBankResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryRepoForkBankResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryRepoForkBankResponse(val *MemoryRepoForkBankResponse) *NullableMemoryRepoForkBankResponse {
	return &NullableMemoryRepoForkBankResponse{value: val, isSet: true}
}

func (v NullableMemoryRepoForkBankResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryRepoForkBankResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


