/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseRefreshResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseRefreshResponse{}

// CodebaseRefreshResponse Explicit codebase refresh response.
type CodebaseRefreshResponse struct {
	SnapshotId NullableString `json:"snapshot_id,omitempty"`
	OperationId NullableString `json:"operation_id,omitempty"`
	Status string `json:"status"`
	ChangedFiles *int32 `json:"changed_files,omitempty"`
	AddedFiles *int32 `json:"added_files,omitempty"`
	DeletedFiles *int32 `json:"deleted_files,omitempty"`
	Noop *bool `json:"noop,omitempty"`
}

type _CodebaseRefreshResponse CodebaseRefreshResponse

// NewCodebaseRefreshResponse instantiates a new CodebaseRefreshResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseRefreshResponse(status string) *CodebaseRefreshResponse {
	this := CodebaseRefreshResponse{}
	this.Status = status
	return &this
}

// NewCodebaseRefreshResponseWithDefaults instantiates a new CodebaseRefreshResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseRefreshResponseWithDefaults() *CodebaseRefreshResponse {
	this := CodebaseRefreshResponse{}
	return &this
}

// GetSnapshotId returns the SnapshotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseRefreshResponse) GetSnapshotId() string {
	if o == nil || IsNil(o.SnapshotId.Get()) {
		var ret string
		return ret
	}
	return *o.SnapshotId.Get()
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseRefreshResponse) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotId.Get(), o.SnapshotId.IsSet()
}

// HasSnapshotId returns a boolean if a field has been set.
func (o *CodebaseRefreshResponse) HasSnapshotId() bool {
	if o != nil && o.SnapshotId.IsSet() {
		return true
	}

	return false
}

// SetSnapshotId gets a reference to the given NullableString and assigns it to the SnapshotId field.
func (o *CodebaseRefreshResponse) SetSnapshotId(v string) {
	o.SnapshotId.Set(&v)
}
// SetSnapshotIdNil sets the value for SnapshotId to be an explicit nil
func (o *CodebaseRefreshResponse) SetSnapshotIdNil() {
	o.SnapshotId.Set(nil)
}

// UnsetSnapshotId ensures that no value is present for SnapshotId, not even an explicit nil
func (o *CodebaseRefreshResponse) UnsetSnapshotId() {
	o.SnapshotId.Unset()
}

// GetOperationId returns the OperationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseRefreshResponse) GetOperationId() string {
	if o == nil || IsNil(o.OperationId.Get()) {
		var ret string
		return ret
	}
	return *o.OperationId.Get()
}

// GetOperationIdOk returns a tuple with the OperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseRefreshResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperationId.Get(), o.OperationId.IsSet()
}

// HasOperationId returns a boolean if a field has been set.
func (o *CodebaseRefreshResponse) HasOperationId() bool {
	if o != nil && o.OperationId.IsSet() {
		return true
	}

	return false
}

// SetOperationId gets a reference to the given NullableString and assigns it to the OperationId field.
func (o *CodebaseRefreshResponse) SetOperationId(v string) {
	o.OperationId.Set(&v)
}
// SetOperationIdNil sets the value for OperationId to be an explicit nil
func (o *CodebaseRefreshResponse) SetOperationIdNil() {
	o.OperationId.Set(nil)
}

// UnsetOperationId ensures that no value is present for OperationId, not even an explicit nil
func (o *CodebaseRefreshResponse) UnsetOperationId() {
	o.OperationId.Unset()
}

// GetStatus returns the Status field value
func (o *CodebaseRefreshResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CodebaseRefreshResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CodebaseRefreshResponse) SetStatus(v string) {
	o.Status = v
}

// GetChangedFiles returns the ChangedFiles field value if set, zero value otherwise.
func (o *CodebaseRefreshResponse) GetChangedFiles() int32 {
	if o == nil || IsNil(o.ChangedFiles) {
		var ret int32
		return ret
	}
	return *o.ChangedFiles
}

// GetChangedFilesOk returns a tuple with the ChangedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseRefreshResponse) GetChangedFilesOk() (*int32, bool) {
	if o == nil || IsNil(o.ChangedFiles) {
		return nil, false
	}
	return o.ChangedFiles, true
}

// HasChangedFiles returns a boolean if a field has been set.
func (o *CodebaseRefreshResponse) HasChangedFiles() bool {
	if o != nil && !IsNil(o.ChangedFiles) {
		return true
	}

	return false
}

// SetChangedFiles gets a reference to the given int32 and assigns it to the ChangedFiles field.
func (o *CodebaseRefreshResponse) SetChangedFiles(v int32) {
	o.ChangedFiles = &v
}

// GetAddedFiles returns the AddedFiles field value if set, zero value otherwise.
func (o *CodebaseRefreshResponse) GetAddedFiles() int32 {
	if o == nil || IsNil(o.AddedFiles) {
		var ret int32
		return ret
	}
	return *o.AddedFiles
}

// GetAddedFilesOk returns a tuple with the AddedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseRefreshResponse) GetAddedFilesOk() (*int32, bool) {
	if o == nil || IsNil(o.AddedFiles) {
		return nil, false
	}
	return o.AddedFiles, true
}

// HasAddedFiles returns a boolean if a field has been set.
func (o *CodebaseRefreshResponse) HasAddedFiles() bool {
	if o != nil && !IsNil(o.AddedFiles) {
		return true
	}

	return false
}

// SetAddedFiles gets a reference to the given int32 and assigns it to the AddedFiles field.
func (o *CodebaseRefreshResponse) SetAddedFiles(v int32) {
	o.AddedFiles = &v
}

// GetDeletedFiles returns the DeletedFiles field value if set, zero value otherwise.
func (o *CodebaseRefreshResponse) GetDeletedFiles() int32 {
	if o == nil || IsNil(o.DeletedFiles) {
		var ret int32
		return ret
	}
	return *o.DeletedFiles
}

// GetDeletedFilesOk returns a tuple with the DeletedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseRefreshResponse) GetDeletedFilesOk() (*int32, bool) {
	if o == nil || IsNil(o.DeletedFiles) {
		return nil, false
	}
	return o.DeletedFiles, true
}

// HasDeletedFiles returns a boolean if a field has been set.
func (o *CodebaseRefreshResponse) HasDeletedFiles() bool {
	if o != nil && !IsNil(o.DeletedFiles) {
		return true
	}

	return false
}

// SetDeletedFiles gets a reference to the given int32 and assigns it to the DeletedFiles field.
func (o *CodebaseRefreshResponse) SetDeletedFiles(v int32) {
	o.DeletedFiles = &v
}

// GetNoop returns the Noop field value if set, zero value otherwise.
func (o *CodebaseRefreshResponse) GetNoop() bool {
	if o == nil || IsNil(o.Noop) {
		var ret bool
		return ret
	}
	return *o.Noop
}

// GetNoopOk returns a tuple with the Noop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseRefreshResponse) GetNoopOk() (*bool, bool) {
	if o == nil || IsNil(o.Noop) {
		return nil, false
	}
	return o.Noop, true
}

// HasNoop returns a boolean if a field has been set.
func (o *CodebaseRefreshResponse) HasNoop() bool {
	if o != nil && !IsNil(o.Noop) {
		return true
	}

	return false
}

// SetNoop gets a reference to the given bool and assigns it to the Noop field.
func (o *CodebaseRefreshResponse) SetNoop(v bool) {
	o.Noop = &v
}

func (o CodebaseRefreshResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseRefreshResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SnapshotId.IsSet() {
		toSerialize["snapshot_id"] = o.SnapshotId.Get()
	}
	if o.OperationId.IsSet() {
		toSerialize["operation_id"] = o.OperationId.Get()
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.ChangedFiles) {
		toSerialize["changed_files"] = o.ChangedFiles
	}
	if !IsNil(o.AddedFiles) {
		toSerialize["added_files"] = o.AddedFiles
	}
	if !IsNil(o.DeletedFiles) {
		toSerialize["deleted_files"] = o.DeletedFiles
	}
	if !IsNil(o.Noop) {
		toSerialize["noop"] = o.Noop
	}
	return toSerialize, nil
}

func (o *CodebaseRefreshResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseRefreshResponse := _CodebaseRefreshResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseRefreshResponse)

	if err != nil {
		return err
	}

	*o = CodebaseRefreshResponse(varCodebaseRefreshResponse)

	return err
}

type NullableCodebaseRefreshResponse struct {
	value *CodebaseRefreshResponse
	isSet bool
}

func (v NullableCodebaseRefreshResponse) Get() *CodebaseRefreshResponse {
	return v.value
}

func (v *NullableCodebaseRefreshResponse) Set(val *CodebaseRefreshResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseRefreshResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseRefreshResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseRefreshResponse(val *CodebaseRefreshResponse) *NullableCodebaseRefreshResponse {
	return &NullableCodebaseRefreshResponse{value: val, isSet: true}
}

func (v NullableCodebaseRefreshResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseRefreshResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


