/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LLMRequestStatsBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMRequestStatsBucket{}

// LLMRequestStatsBucket A single bucket of LLM request statistics.
type LLMRequestStatsBucket struct {
	Bucket       string `json:"bucket"`
	Status       string `json:"status"`
	Count        int32  `json:"count"`
	InputTokens  *int32 `json:"input_tokens,omitempty"`
	OutputTokens *int32 `json:"output_tokens,omitempty"`
	CachedTokens *int32 `json:"cached_tokens,omitempty"`
	TotalTokens  *int32 `json:"total_tokens,omitempty"`
}

type _LLMRequestStatsBucket LLMRequestStatsBucket

// NewLLMRequestStatsBucket instantiates a new LLMRequestStatsBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMRequestStatsBucket(bucket string, status string, count int32) *LLMRequestStatsBucket {
	this := LLMRequestStatsBucket{}
	this.Bucket = bucket
	this.Status = status
	this.Count = count
	var inputTokens int32 = 0
	this.InputTokens = &inputTokens
	var outputTokens int32 = 0
	this.OutputTokens = &outputTokens
	var cachedTokens int32 = 0
	this.CachedTokens = &cachedTokens
	var totalTokens int32 = 0
	this.TotalTokens = &totalTokens
	return &this
}

// NewLLMRequestStatsBucketWithDefaults instantiates a new LLMRequestStatsBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMRequestStatsBucketWithDefaults() *LLMRequestStatsBucket {
	this := LLMRequestStatsBucket{}
	var inputTokens int32 = 0
	this.InputTokens = &inputTokens
	var outputTokens int32 = 0
	this.OutputTokens = &outputTokens
	var cachedTokens int32 = 0
	this.CachedTokens = &cachedTokens
	var totalTokens int32 = 0
	this.TotalTokens = &totalTokens
	return &this
}

// GetBucket returns the Bucket field value
func (o *LLMRequestStatsBucket) GetBucket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *LLMRequestStatsBucket) SetBucket(v string) {
	o.Bucket = v
}

// GetStatus returns the Status field value
func (o *LLMRequestStatsBucket) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LLMRequestStatsBucket) SetStatus(v string) {
	o.Status = v
}

// GetCount returns the Count field value
func (o *LLMRequestStatsBucket) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *LLMRequestStatsBucket) SetCount(v int32) {
	o.Count = v
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise.
func (o *LLMRequestStatsBucket) GetInputTokens() int32 {
	if o == nil || IsNil(o.InputTokens) {
		var ret int32
		return ret
	}
	return *o.InputTokens
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetInputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.InputTokens) {
		return nil, false
	}
	return o.InputTokens, true
}

// HasInputTokens returns a boolean if a field has been set.
func (o *LLMRequestStatsBucket) HasInputTokens() bool {
	if o != nil && !IsNil(o.InputTokens) {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given int32 and assigns it to the InputTokens field.
func (o *LLMRequestStatsBucket) SetInputTokens(v int32) {
	o.InputTokens = &v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise.
func (o *LLMRequestStatsBucket) GetOutputTokens() int32 {
	if o == nil || IsNil(o.OutputTokens) {
		var ret int32
		return ret
	}
	return *o.OutputTokens
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetOutputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputTokens) {
		return nil, false
	}
	return o.OutputTokens, true
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *LLMRequestStatsBucket) HasOutputTokens() bool {
	if o != nil && !IsNil(o.OutputTokens) {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given int32 and assigns it to the OutputTokens field.
func (o *LLMRequestStatsBucket) SetOutputTokens(v int32) {
	o.OutputTokens = &v
}

// GetCachedTokens returns the CachedTokens field value if set, zero value otherwise.
func (o *LLMRequestStatsBucket) GetCachedTokens() int32 {
	if o == nil || IsNil(o.CachedTokens) {
		var ret int32
		return ret
	}
	return *o.CachedTokens
}

// GetCachedTokensOk returns a tuple with the CachedTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetCachedTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.CachedTokens) {
		return nil, false
	}
	return o.CachedTokens, true
}

// HasCachedTokens returns a boolean if a field has been set.
func (o *LLMRequestStatsBucket) HasCachedTokens() bool {
	if o != nil && !IsNil(o.CachedTokens) {
		return true
	}

	return false
}

// SetCachedTokens gets a reference to the given int32 and assigns it to the CachedTokens field.
func (o *LLMRequestStatsBucket) SetCachedTokens(v int32) {
	o.CachedTokens = &v
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise.
func (o *LLMRequestStatsBucket) GetTotalTokens() int32 {
	if o == nil || IsNil(o.TotalTokens) {
		var ret int32
		return ret
	}
	return *o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LLMRequestStatsBucket) GetTotalTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTokens) {
		return nil, false
	}
	return o.TotalTokens, true
}

// HasTotalTokens returns a boolean if a field has been set.
func (o *LLMRequestStatsBucket) HasTotalTokens() bool {
	if o != nil && !IsNil(o.TotalTokens) {
		return true
	}

	return false
}

// SetTotalTokens gets a reference to the given int32 and assigns it to the TotalTokens field.
func (o *LLMRequestStatsBucket) SetTotalTokens(v int32) {
	o.TotalTokens = &v
}

func (o LLMRequestStatsBucket) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMRequestStatsBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bucket"] = o.Bucket
	toSerialize["status"] = o.Status
	toSerialize["count"] = o.Count
	if !IsNil(o.InputTokens) {
		toSerialize["input_tokens"] = o.InputTokens
	}
	if !IsNil(o.OutputTokens) {
		toSerialize["output_tokens"] = o.OutputTokens
	}
	if !IsNil(o.CachedTokens) {
		toSerialize["cached_tokens"] = o.CachedTokens
	}
	if !IsNil(o.TotalTokens) {
		toSerialize["total_tokens"] = o.TotalTokens
	}
	return toSerialize, nil
}

func (o *LLMRequestStatsBucket) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bucket",
		"status",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMRequestStatsBucket := _LLMRequestStatsBucket{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMRequestStatsBucket)

	if err != nil {
		return err
	}

	*o = LLMRequestStatsBucket(varLLMRequestStatsBucket)

	return err
}

type NullableLLMRequestStatsBucket struct {
	value *LLMRequestStatsBucket
	isSet bool
}

func (v NullableLLMRequestStatsBucket) Get() *LLMRequestStatsBucket {
	return v.value
}

func (v *NullableLLMRequestStatsBucket) Set(val *LLMRequestStatsBucket) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMRequestStatsBucket) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMRequestStatsBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMRequestStatsBucket(val *LLMRequestStatsBucket) *NullableLLMRequestStatsBucket {
	return &NullableLLMRequestStatsBucket{value: val, isSet: true}
}

func (v NullableLLMRequestStatsBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMRequestStatsBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
