/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemoryRepoLogResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryRepoLogResponse{}

// MemoryRepoLogResponse struct for MemoryRepoLogResponse
type MemoryRepoLogResponse struct {
	Commits []map[string]interface{} `json:"commits"`
}

type _MemoryRepoLogResponse MemoryRepoLogResponse

// NewMemoryRepoLogResponse instantiates a new MemoryRepoLogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryRepoLogResponse(commits []map[string]interface{}) *MemoryRepoLogResponse {
	this := MemoryRepoLogResponse{}
	this.Commits = commits
	return &this
}

// NewMemoryRepoLogResponseWithDefaults instantiates a new MemoryRepoLogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryRepoLogResponseWithDefaults() *MemoryRepoLogResponse {
	this := MemoryRepoLogResponse{}
	return &this
}

// GetCommits returns the Commits field value
func (o *MemoryRepoLogResponse) GetCommits() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Commits
}

// GetCommitsOk returns a tuple with the Commits field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoLogResponse) GetCommitsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Commits, true
}

// SetCommits sets field value
func (o *MemoryRepoLogResponse) SetCommits(v []map[string]interface{}) {
	o.Commits = v
}

func (o MemoryRepoLogResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryRepoLogResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commits"] = o.Commits
	return toSerialize, nil
}

func (o *MemoryRepoLogResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"commits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryRepoLogResponse := _MemoryRepoLogResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryRepoLogResponse)

	if err != nil {
		return err
	}

	*o = MemoryRepoLogResponse(varMemoryRepoLogResponse)

	return err
}

type NullableMemoryRepoLogResponse struct {
	value *MemoryRepoLogResponse
	isSet bool
}

func (v NullableMemoryRepoLogResponse) Get() *MemoryRepoLogResponse {
	return v.value
}

func (v *NullableMemoryRepoLogResponse) Set(val *MemoryRepoLogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryRepoLogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryRepoLogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryRepoLogResponse(val *MemoryRepoLogResponse) *NullableMemoryRepoLogResponse {
	return &NullableMemoryRepoLogResponse{value: val, isSet: true}
}

func (v NullableMemoryRepoLogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryRepoLogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


