/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SignupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupRequest{}

// SignupRequest struct for SignupRequest
type SignupRequest struct {
	OrgSlug       string `json:"org_slug"`
	OrgName       string `json:"org_name"`
	OwnerEmail    string `json:"owner_email"`
	OwnerName     string `json:"owner_name"`
	OwnerPassword string `json:"owner_password"`
}

type _SignupRequest SignupRequest

// NewSignupRequest instantiates a new SignupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupRequest(orgSlug string, orgName string, ownerEmail string, ownerName string, ownerPassword string) *SignupRequest {
	this := SignupRequest{}
	this.OrgSlug = orgSlug
	this.OrgName = orgName
	this.OwnerEmail = ownerEmail
	this.OwnerName = ownerName
	this.OwnerPassword = ownerPassword
	return &this
}

// NewSignupRequestWithDefaults instantiates a new SignupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupRequestWithDefaults() *SignupRequest {
	this := SignupRequest{}
	return &this
}

// GetOrgSlug returns the OrgSlug field value
func (o *SignupRequest) GetOrgSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgSlug
}

// GetOrgSlugOk returns a tuple with the OrgSlug field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetOrgSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgSlug, true
}

// SetOrgSlug sets field value
func (o *SignupRequest) SetOrgSlug(v string) {
	o.OrgSlug = v
}

// GetOrgName returns the OrgName field value
func (o *SignupRequest) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *SignupRequest) SetOrgName(v string) {
	o.OrgName = v
}

// GetOwnerEmail returns the OwnerEmail field value
func (o *SignupRequest) GetOwnerEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerEmail
}

// GetOwnerEmailOk returns a tuple with the OwnerEmail field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetOwnerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerEmail, true
}

// SetOwnerEmail sets field value
func (o *SignupRequest) SetOwnerEmail(v string) {
	o.OwnerEmail = v
}

// GetOwnerName returns the OwnerName field value
func (o *SignupRequest) GetOwnerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerName
}

// GetOwnerNameOk returns a tuple with the OwnerName field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetOwnerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerName, true
}

// SetOwnerName sets field value
func (o *SignupRequest) SetOwnerName(v string) {
	o.OwnerName = v
}

// GetOwnerPassword returns the OwnerPassword field value
func (o *SignupRequest) GetOwnerPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerPassword
}

// GetOwnerPasswordOk returns a tuple with the OwnerPassword field value
// and a boolean to check if the value has been set.
func (o *SignupRequest) GetOwnerPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerPassword, true
}

// SetOwnerPassword sets field value
func (o *SignupRequest) SetOwnerPassword(v string) {
	o.OwnerPassword = v
}

func (o SignupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["org_slug"] = o.OrgSlug
	toSerialize["org_name"] = o.OrgName
	toSerialize["owner_email"] = o.OwnerEmail
	toSerialize["owner_name"] = o.OwnerName
	toSerialize["owner_password"] = o.OwnerPassword
	return toSerialize, nil
}

func (o *SignupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_slug",
		"org_name",
		"owner_email",
		"owner_name",
		"owner_password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignupRequest := _SignupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignupRequest)

	if err != nil {
		return err
	}

	*o = SignupRequest(varSignupRequest)

	return err
}

type NullableSignupRequest struct {
	value *SignupRequest
	isSet bool
}

func (v NullableSignupRequest) Get() *SignupRequest {
	return v.value
}

func (v *NullableSignupRequest) Set(val *SignupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupRequest(val *SignupRequest) *NullableSignupRequest {
	return &NullableSignupRequest{value: val, isSet: true}
}

func (v NullableSignupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
