/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemoryRepoStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryRepoStatusResponse{}

// MemoryRepoStatusResponse struct for MemoryRepoStatusResponse
type MemoryRepoStatusResponse struct {
	RepoId string `json:"repo_id"`
	BranchName string `json:"branch_name"`
	WorkspaceBankId string `json:"workspace_bank_id"`
	HeadCommitId NullableString `json:"head_commit_id,omitempty"`
	Dirty bool `json:"dirty"`
	ChangedComponents []string `json:"changed_components"`
	TableDeltas map[string]map[string]int32 `json:"table_deltas"`
}

type _MemoryRepoStatusResponse MemoryRepoStatusResponse

// NewMemoryRepoStatusResponse instantiates a new MemoryRepoStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryRepoStatusResponse(repoId string, branchName string, workspaceBankId string, dirty bool, changedComponents []string, tableDeltas map[string]map[string]int32) *MemoryRepoStatusResponse {
	this := MemoryRepoStatusResponse{}
	this.RepoId = repoId
	this.BranchName = branchName
	this.WorkspaceBankId = workspaceBankId
	this.Dirty = dirty
	this.ChangedComponents = changedComponents
	this.TableDeltas = tableDeltas
	return &this
}

// NewMemoryRepoStatusResponseWithDefaults instantiates a new MemoryRepoStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryRepoStatusResponseWithDefaults() *MemoryRepoStatusResponse {
	this := MemoryRepoStatusResponse{}
	return &this
}

// GetRepoId returns the RepoId field value
func (o *MemoryRepoStatusResponse) GetRepoId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoId
}

// GetRepoIdOk returns a tuple with the RepoId field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoStatusResponse) GetRepoIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoId, true
}

// SetRepoId sets field value
func (o *MemoryRepoStatusResponse) SetRepoId(v string) {
	o.RepoId = v
}

// GetBranchName returns the BranchName field value
func (o *MemoryRepoStatusResponse) GetBranchName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BranchName
}

// GetBranchNameOk returns a tuple with the BranchName field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoStatusResponse) GetBranchNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BranchName, true
}

// SetBranchName sets field value
func (o *MemoryRepoStatusResponse) SetBranchName(v string) {
	o.BranchName = v
}

// GetWorkspaceBankId returns the WorkspaceBankId field value
func (o *MemoryRepoStatusResponse) GetWorkspaceBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceBankId
}

// GetWorkspaceBankIdOk returns a tuple with the WorkspaceBankId field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoStatusResponse) GetWorkspaceBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceBankId, true
}

// SetWorkspaceBankId sets field value
func (o *MemoryRepoStatusResponse) SetWorkspaceBankId(v string) {
	o.WorkspaceBankId = v
}

// GetHeadCommitId returns the HeadCommitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryRepoStatusResponse) GetHeadCommitId() string {
	if o == nil || IsNil(o.HeadCommitId.Get()) {
		var ret string
		return ret
	}
	return *o.HeadCommitId.Get()
}

// GetHeadCommitIdOk returns a tuple with the HeadCommitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRepoStatusResponse) GetHeadCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HeadCommitId.Get(), o.HeadCommitId.IsSet()
}

// HasHeadCommitId returns a boolean if a field has been set.
func (o *MemoryRepoStatusResponse) HasHeadCommitId() bool {
	if o != nil && o.HeadCommitId.IsSet() {
		return true
	}

	return false
}

// SetHeadCommitId gets a reference to the given NullableString and assigns it to the HeadCommitId field.
func (o *MemoryRepoStatusResponse) SetHeadCommitId(v string) {
	o.HeadCommitId.Set(&v)
}
// SetHeadCommitIdNil sets the value for HeadCommitId to be an explicit nil
func (o *MemoryRepoStatusResponse) SetHeadCommitIdNil() {
	o.HeadCommitId.Set(nil)
}

// UnsetHeadCommitId ensures that no value is present for HeadCommitId, not even an explicit nil
func (o *MemoryRepoStatusResponse) UnsetHeadCommitId() {
	o.HeadCommitId.Unset()
}

// GetDirty returns the Dirty field value
func (o *MemoryRepoStatusResponse) GetDirty() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Dirty
}

// GetDirtyOk returns a tuple with the Dirty field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoStatusResponse) GetDirtyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dirty, true
}

// SetDirty sets field value
func (o *MemoryRepoStatusResponse) SetDirty(v bool) {
	o.Dirty = v
}

// GetChangedComponents returns the ChangedComponents field value
func (o *MemoryRepoStatusResponse) GetChangedComponents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ChangedComponents
}

// GetChangedComponentsOk returns a tuple with the ChangedComponents field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoStatusResponse) GetChangedComponentsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangedComponents, true
}

// SetChangedComponents sets field value
func (o *MemoryRepoStatusResponse) SetChangedComponents(v []string) {
	o.ChangedComponents = v
}

// GetTableDeltas returns the TableDeltas field value
func (o *MemoryRepoStatusResponse) GetTableDeltas() map[string]map[string]int32 {
	if o == nil {
		var ret map[string]map[string]int32
		return ret
	}

	return o.TableDeltas
}

// GetTableDeltasOk returns a tuple with the TableDeltas field value
// and a boolean to check if the value has been set.
func (o *MemoryRepoStatusResponse) GetTableDeltasOk() (map[string]map[string]int32, bool) {
	if o == nil {
		return map[string]map[string]int32{}, false
	}
	return o.TableDeltas, true
}

// SetTableDeltas sets field value
func (o *MemoryRepoStatusResponse) SetTableDeltas(v map[string]map[string]int32) {
	o.TableDeltas = v
}

func (o MemoryRepoStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryRepoStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["repo_id"] = o.RepoId
	toSerialize["branch_name"] = o.BranchName
	toSerialize["workspace_bank_id"] = o.WorkspaceBankId
	if o.HeadCommitId.IsSet() {
		toSerialize["head_commit_id"] = o.HeadCommitId.Get()
	}
	toSerialize["dirty"] = o.Dirty
	toSerialize["changed_components"] = o.ChangedComponents
	toSerialize["table_deltas"] = o.TableDeltas
	return toSerialize, nil
}

func (o *MemoryRepoStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"repo_id",
		"branch_name",
		"workspace_bank_id",
		"dirty",
		"changed_components",
		"table_deltas",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryRepoStatusResponse := _MemoryRepoStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryRepoStatusResponse)

	if err != nil {
		return err
	}

	*o = MemoryRepoStatusResponse(varMemoryRepoStatusResponse)

	return err
}

type NullableMemoryRepoStatusResponse struct {
	value *MemoryRepoStatusResponse
	isSet bool
}

func (v NullableMemoryRepoStatusResponse) Get() *MemoryRepoStatusResponse {
	return v.value
}

func (v *NullableMemoryRepoStatusResponse) Set(val *MemoryRepoStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryRepoStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryRepoStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryRepoStatusResponse(val *MemoryRepoStatusResponse) *NullableMemoryRepoStatusResponse {
	return &NullableMemoryRepoStatusResponse{value: val, isSet: true}
}

func (v NullableMemoryRepoStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryRepoStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


