/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseChunkDetailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseChunkDetailResponse{}

// CodebaseChunkDetailResponse Detailed chunk review payload.
type CodebaseChunkDetailResponse struct {
	Id string `json:"id"`
	ChunkKey string `json:"chunk_key"`
	Path string `json:"path"`
	Language NullableString `json:"language,omitempty"`
	Kind string `json:"kind"`
	Label string `json:"label"`
	PreviewText string `json:"preview_text"`
	StartLine int32 `json:"start_line"`
	EndLine int32 `json:"end_line"`
	Container NullableString `json:"container,omitempty"`
	ParentSymbol NullableString `json:"parent_symbol,omitempty"`
	ParentFqName NullableString `json:"parent_fq_name,omitempty"`
	ParseConfidence *float32 `json:"parse_confidence,omitempty"`
	ClusterId NullableString `json:"cluster_id,omitempty"`
	ClusterLabel NullableString `json:"cluster_label,omitempty"`
	RouteTarget string `json:"route_target"`
	RouteSource NullableString `json:"route_source,omitempty"`
	ChangeKind string `json:"change_kind"`
	RelatedCount *int32 `json:"related_count,omitempty"`
	DocumentId NullableString `json:"document_id,omitempty"`
	SignificanceScore *float32 `json:"significance_score,omitempty"`
	SignificanceComponents map[string]interface{} `json:"significance_components,omitempty"`
	FileRole NullableString `json:"file_role,omitempty"`
	AutoRouteReason NullableString `json:"auto_route_reason,omitempty"`
	ComplexityScore NullableFloat32 `json:"complexity_score,omitempty"`
	SafetyTags []string `json:"safety_tags,omitempty"`
	PagerankCentrality NullableFloat32 `json:"pagerank_centrality,omitempty"`
	FaninCount *int32 `json:"fanin_count,omitempty"`
	SnapshotId string `json:"snapshot_id"`
	ContentText string `json:"content_text"`
	RelatedChunks []CodebaseChunkRelatedItemResponse `json:"related_chunks,omitempty"`
	Symbols []CodebaseSymbolMatchResponse `json:"symbols,omitempty"`
	ImpactEdges []CodebaseImpactEdgeResponse `json:"impact_edges,omitempty"`
	ClusterMembers []CodebaseChunkRelatedItemResponse `json:"cluster_members,omitempty"`
}

type _CodebaseChunkDetailResponse CodebaseChunkDetailResponse

// NewCodebaseChunkDetailResponse instantiates a new CodebaseChunkDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseChunkDetailResponse(id string, chunkKey string, path string, kind string, label string, previewText string, startLine int32, endLine int32, routeTarget string, changeKind string, snapshotId string, contentText string) *CodebaseChunkDetailResponse {
	this := CodebaseChunkDetailResponse{}
	this.Id = id
	this.ChunkKey = chunkKey
	this.Path = path
	this.Kind = kind
	this.Label = label
	this.PreviewText = previewText
	this.StartLine = startLine
	this.EndLine = endLine
	var parseConfidence float32 = 0.0
	this.ParseConfidence = &parseConfidence
	this.RouteTarget = routeTarget
	this.ChangeKind = changeKind
	var relatedCount int32 = 0
	this.RelatedCount = &relatedCount
	var significanceScore float32 = 0.0
	this.SignificanceScore = &significanceScore
	var faninCount int32 = 0
	this.FaninCount = &faninCount
	this.SnapshotId = snapshotId
	this.ContentText = contentText
	return &this
}

// NewCodebaseChunkDetailResponseWithDefaults instantiates a new CodebaseChunkDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseChunkDetailResponseWithDefaults() *CodebaseChunkDetailResponse {
	this := CodebaseChunkDetailResponse{}
	var parseConfidence float32 = 0.0
	this.ParseConfidence = &parseConfidence
	var relatedCount int32 = 0
	this.RelatedCount = &relatedCount
	var significanceScore float32 = 0.0
	this.SignificanceScore = &significanceScore
	var faninCount int32 = 0
	this.FaninCount = &faninCount
	return &this
}

// GetId returns the Id field value
func (o *CodebaseChunkDetailResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CodebaseChunkDetailResponse) SetId(v string) {
	o.Id = v
}

// GetChunkKey returns the ChunkKey field value
func (o *CodebaseChunkDetailResponse) GetChunkKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChunkKey
}

// GetChunkKeyOk returns a tuple with the ChunkKey field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetChunkKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkKey, true
}

// SetChunkKey sets field value
func (o *CodebaseChunkDetailResponse) SetChunkKey(v string) {
	o.ChunkKey = v
}

// GetPath returns the Path field value
func (o *CodebaseChunkDetailResponse) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *CodebaseChunkDetailResponse) SetPath(v string) {
	o.Path = v
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetLanguage() string {
	if o == nil || IsNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *CodebaseChunkDetailResponse) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetLanguage() {
	o.Language.Unset()
}

// GetKind returns the Kind field value
func (o *CodebaseChunkDetailResponse) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CodebaseChunkDetailResponse) SetKind(v string) {
	o.Kind = v
}

// GetLabel returns the Label field value
func (o *CodebaseChunkDetailResponse) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *CodebaseChunkDetailResponse) SetLabel(v string) {
	o.Label = v
}

// GetPreviewText returns the PreviewText field value
func (o *CodebaseChunkDetailResponse) GetPreviewText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreviewText
}

// GetPreviewTextOk returns a tuple with the PreviewText field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetPreviewTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviewText, true
}

// SetPreviewText sets field value
func (o *CodebaseChunkDetailResponse) SetPreviewText(v string) {
	o.PreviewText = v
}

// GetStartLine returns the StartLine field value
func (o *CodebaseChunkDetailResponse) GetStartLine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartLine
}

// GetStartLineOk returns a tuple with the StartLine field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetStartLineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartLine, true
}

// SetStartLine sets field value
func (o *CodebaseChunkDetailResponse) SetStartLine(v int32) {
	o.StartLine = v
}

// GetEndLine returns the EndLine field value
func (o *CodebaseChunkDetailResponse) GetEndLine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndLine
}

// GetEndLineOk returns a tuple with the EndLine field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetEndLineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndLine, true
}

// SetEndLine sets field value
func (o *CodebaseChunkDetailResponse) SetEndLine(v int32) {
	o.EndLine = v
}

// GetContainer returns the Container field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetContainer() string {
	if o == nil || IsNil(o.Container.Get()) {
		var ret string
		return ret
	}
	return *o.Container.Get()
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetContainerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Container.Get(), o.Container.IsSet()
}

// HasContainer returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasContainer() bool {
	if o != nil && o.Container.IsSet() {
		return true
	}

	return false
}

// SetContainer gets a reference to the given NullableString and assigns it to the Container field.
func (o *CodebaseChunkDetailResponse) SetContainer(v string) {
	o.Container.Set(&v)
}
// SetContainerNil sets the value for Container to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetContainerNil() {
	o.Container.Set(nil)
}

// UnsetContainer ensures that no value is present for Container, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetContainer() {
	o.Container.Unset()
}

// GetParentSymbol returns the ParentSymbol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetParentSymbol() string {
	if o == nil || IsNil(o.ParentSymbol.Get()) {
		var ret string
		return ret
	}
	return *o.ParentSymbol.Get()
}

// GetParentSymbolOk returns a tuple with the ParentSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetParentSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentSymbol.Get(), o.ParentSymbol.IsSet()
}

// HasParentSymbol returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasParentSymbol() bool {
	if o != nil && o.ParentSymbol.IsSet() {
		return true
	}

	return false
}

// SetParentSymbol gets a reference to the given NullableString and assigns it to the ParentSymbol field.
func (o *CodebaseChunkDetailResponse) SetParentSymbol(v string) {
	o.ParentSymbol.Set(&v)
}
// SetParentSymbolNil sets the value for ParentSymbol to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetParentSymbolNil() {
	o.ParentSymbol.Set(nil)
}

// UnsetParentSymbol ensures that no value is present for ParentSymbol, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetParentSymbol() {
	o.ParentSymbol.Unset()
}

// GetParentFqName returns the ParentFqName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetParentFqName() string {
	if o == nil || IsNil(o.ParentFqName.Get()) {
		var ret string
		return ret
	}
	return *o.ParentFqName.Get()
}

// GetParentFqNameOk returns a tuple with the ParentFqName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetParentFqNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentFqName.Get(), o.ParentFqName.IsSet()
}

// HasParentFqName returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasParentFqName() bool {
	if o != nil && o.ParentFqName.IsSet() {
		return true
	}

	return false
}

// SetParentFqName gets a reference to the given NullableString and assigns it to the ParentFqName field.
func (o *CodebaseChunkDetailResponse) SetParentFqName(v string) {
	o.ParentFqName.Set(&v)
}
// SetParentFqNameNil sets the value for ParentFqName to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetParentFqNameNil() {
	o.ParentFqName.Set(nil)
}

// UnsetParentFqName ensures that no value is present for ParentFqName, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetParentFqName() {
	o.ParentFqName.Unset()
}

// GetParseConfidence returns the ParseConfidence field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetParseConfidence() float32 {
	if o == nil || IsNil(o.ParseConfidence) {
		var ret float32
		return ret
	}
	return *o.ParseConfidence
}

// GetParseConfidenceOk returns a tuple with the ParseConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetParseConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.ParseConfidence) {
		return nil, false
	}
	return o.ParseConfidence, true
}

// HasParseConfidence returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasParseConfidence() bool {
	if o != nil && !IsNil(o.ParseConfidence) {
		return true
	}

	return false
}

// SetParseConfidence gets a reference to the given float32 and assigns it to the ParseConfidence field.
func (o *CodebaseChunkDetailResponse) SetParseConfidence(v float32) {
	o.ParseConfidence = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetClusterId() string {
	if o == nil || IsNil(o.ClusterId.Get()) {
		var ret string
		return ret
	}
	return *o.ClusterId.Get()
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterId.Get(), o.ClusterId.IsSet()
}

// HasClusterId returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasClusterId() bool {
	if o != nil && o.ClusterId.IsSet() {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given NullableString and assigns it to the ClusterId field.
func (o *CodebaseChunkDetailResponse) SetClusterId(v string) {
	o.ClusterId.Set(&v)
}
// SetClusterIdNil sets the value for ClusterId to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetClusterIdNil() {
	o.ClusterId.Set(nil)
}

// UnsetClusterId ensures that no value is present for ClusterId, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetClusterId() {
	o.ClusterId.Unset()
}

// GetClusterLabel returns the ClusterLabel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetClusterLabel() string {
	if o == nil || IsNil(o.ClusterLabel.Get()) {
		var ret string
		return ret
	}
	return *o.ClusterLabel.Get()
}

// GetClusterLabelOk returns a tuple with the ClusterLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetClusterLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterLabel.Get(), o.ClusterLabel.IsSet()
}

// HasClusterLabel returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasClusterLabel() bool {
	if o != nil && o.ClusterLabel.IsSet() {
		return true
	}

	return false
}

// SetClusterLabel gets a reference to the given NullableString and assigns it to the ClusterLabel field.
func (o *CodebaseChunkDetailResponse) SetClusterLabel(v string) {
	o.ClusterLabel.Set(&v)
}
// SetClusterLabelNil sets the value for ClusterLabel to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetClusterLabelNil() {
	o.ClusterLabel.Set(nil)
}

// UnsetClusterLabel ensures that no value is present for ClusterLabel, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetClusterLabel() {
	o.ClusterLabel.Unset()
}

// GetRouteTarget returns the RouteTarget field value
func (o *CodebaseChunkDetailResponse) GetRouteTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RouteTarget
}

// GetRouteTargetOk returns a tuple with the RouteTarget field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetRouteTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouteTarget, true
}

// SetRouteTarget sets field value
func (o *CodebaseChunkDetailResponse) SetRouteTarget(v string) {
	o.RouteTarget = v
}

// GetRouteSource returns the RouteSource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetRouteSource() string {
	if o == nil || IsNil(o.RouteSource.Get()) {
		var ret string
		return ret
	}
	return *o.RouteSource.Get()
}

// GetRouteSourceOk returns a tuple with the RouteSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetRouteSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteSource.Get(), o.RouteSource.IsSet()
}

// HasRouteSource returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasRouteSource() bool {
	if o != nil && o.RouteSource.IsSet() {
		return true
	}

	return false
}

// SetRouteSource gets a reference to the given NullableString and assigns it to the RouteSource field.
func (o *CodebaseChunkDetailResponse) SetRouteSource(v string) {
	o.RouteSource.Set(&v)
}
// SetRouteSourceNil sets the value for RouteSource to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetRouteSourceNil() {
	o.RouteSource.Set(nil)
}

// UnsetRouteSource ensures that no value is present for RouteSource, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetRouteSource() {
	o.RouteSource.Unset()
}

// GetChangeKind returns the ChangeKind field value
func (o *CodebaseChunkDetailResponse) GetChangeKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeKind
}

// GetChangeKindOk returns a tuple with the ChangeKind field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetChangeKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeKind, true
}

// SetChangeKind sets field value
func (o *CodebaseChunkDetailResponse) SetChangeKind(v string) {
	o.ChangeKind = v
}

// GetRelatedCount returns the RelatedCount field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetRelatedCount() int32 {
	if o == nil || IsNil(o.RelatedCount) {
		var ret int32
		return ret
	}
	return *o.RelatedCount
}

// GetRelatedCountOk returns a tuple with the RelatedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetRelatedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RelatedCount) {
		return nil, false
	}
	return o.RelatedCount, true
}

// HasRelatedCount returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasRelatedCount() bool {
	if o != nil && !IsNil(o.RelatedCount) {
		return true
	}

	return false
}

// SetRelatedCount gets a reference to the given int32 and assigns it to the RelatedCount field.
func (o *CodebaseChunkDetailResponse) SetRelatedCount(v int32) {
	o.RelatedCount = &v
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentId.Get()
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentId.Get(), o.DocumentId.IsSet()
}

// HasDocumentId returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasDocumentId() bool {
	if o != nil && o.DocumentId.IsSet() {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given NullableString and assigns it to the DocumentId field.
func (o *CodebaseChunkDetailResponse) SetDocumentId(v string) {
	o.DocumentId.Set(&v)
}
// SetDocumentIdNil sets the value for DocumentId to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetDocumentIdNil() {
	o.DocumentId.Set(nil)
}

// UnsetDocumentId ensures that no value is present for DocumentId, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetDocumentId() {
	o.DocumentId.Unset()
}

// GetSignificanceScore returns the SignificanceScore field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetSignificanceScore() float32 {
	if o == nil || IsNil(o.SignificanceScore) {
		var ret float32
		return ret
	}
	return *o.SignificanceScore
}

// GetSignificanceScoreOk returns a tuple with the SignificanceScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetSignificanceScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.SignificanceScore) {
		return nil, false
	}
	return o.SignificanceScore, true
}

// HasSignificanceScore returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasSignificanceScore() bool {
	if o != nil && !IsNil(o.SignificanceScore) {
		return true
	}

	return false
}

// SetSignificanceScore gets a reference to the given float32 and assigns it to the SignificanceScore field.
func (o *CodebaseChunkDetailResponse) SetSignificanceScore(v float32) {
	o.SignificanceScore = &v
}

// GetSignificanceComponents returns the SignificanceComponents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetSignificanceComponents() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SignificanceComponents
}

// GetSignificanceComponentsOk returns a tuple with the SignificanceComponents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetSignificanceComponentsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SignificanceComponents) {
		return map[string]interface{}{}, false
	}
	return o.SignificanceComponents, true
}

// HasSignificanceComponents returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasSignificanceComponents() bool {
	if o != nil && !IsNil(o.SignificanceComponents) {
		return true
	}

	return false
}

// SetSignificanceComponents gets a reference to the given map[string]interface{} and assigns it to the SignificanceComponents field.
func (o *CodebaseChunkDetailResponse) SetSignificanceComponents(v map[string]interface{}) {
	o.SignificanceComponents = v
}

// GetFileRole returns the FileRole field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetFileRole() string {
	if o == nil || IsNil(o.FileRole.Get()) {
		var ret string
		return ret
	}
	return *o.FileRole.Get()
}

// GetFileRoleOk returns a tuple with the FileRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetFileRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileRole.Get(), o.FileRole.IsSet()
}

// HasFileRole returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasFileRole() bool {
	if o != nil && o.FileRole.IsSet() {
		return true
	}

	return false
}

// SetFileRole gets a reference to the given NullableString and assigns it to the FileRole field.
func (o *CodebaseChunkDetailResponse) SetFileRole(v string) {
	o.FileRole.Set(&v)
}
// SetFileRoleNil sets the value for FileRole to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetFileRoleNil() {
	o.FileRole.Set(nil)
}

// UnsetFileRole ensures that no value is present for FileRole, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetFileRole() {
	o.FileRole.Unset()
}

// GetAutoRouteReason returns the AutoRouteReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetAutoRouteReason() string {
	if o == nil || IsNil(o.AutoRouteReason.Get()) {
		var ret string
		return ret
	}
	return *o.AutoRouteReason.Get()
}

// GetAutoRouteReasonOk returns a tuple with the AutoRouteReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetAutoRouteReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AutoRouteReason.Get(), o.AutoRouteReason.IsSet()
}

// HasAutoRouteReason returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasAutoRouteReason() bool {
	if o != nil && o.AutoRouteReason.IsSet() {
		return true
	}

	return false
}

// SetAutoRouteReason gets a reference to the given NullableString and assigns it to the AutoRouteReason field.
func (o *CodebaseChunkDetailResponse) SetAutoRouteReason(v string) {
	o.AutoRouteReason.Set(&v)
}
// SetAutoRouteReasonNil sets the value for AutoRouteReason to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetAutoRouteReasonNil() {
	o.AutoRouteReason.Set(nil)
}

// UnsetAutoRouteReason ensures that no value is present for AutoRouteReason, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetAutoRouteReason() {
	o.AutoRouteReason.Unset()
}

// GetComplexityScore returns the ComplexityScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetComplexityScore() float32 {
	if o == nil || IsNil(o.ComplexityScore.Get()) {
		var ret float32
		return ret
	}
	return *o.ComplexityScore.Get()
}

// GetComplexityScoreOk returns a tuple with the ComplexityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetComplexityScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ComplexityScore.Get(), o.ComplexityScore.IsSet()
}

// HasComplexityScore returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasComplexityScore() bool {
	if o != nil && o.ComplexityScore.IsSet() {
		return true
	}

	return false
}

// SetComplexityScore gets a reference to the given NullableFloat32 and assigns it to the ComplexityScore field.
func (o *CodebaseChunkDetailResponse) SetComplexityScore(v float32) {
	o.ComplexityScore.Set(&v)
}
// SetComplexityScoreNil sets the value for ComplexityScore to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetComplexityScoreNil() {
	o.ComplexityScore.Set(nil)
}

// UnsetComplexityScore ensures that no value is present for ComplexityScore, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetComplexityScore() {
	o.ComplexityScore.Unset()
}

// GetSafetyTags returns the SafetyTags field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetSafetyTags() []string {
	if o == nil || IsNil(o.SafetyTags) {
		var ret []string
		return ret
	}
	return o.SafetyTags
}

// GetSafetyTagsOk returns a tuple with the SafetyTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetSafetyTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.SafetyTags) {
		return nil, false
	}
	return o.SafetyTags, true
}

// HasSafetyTags returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasSafetyTags() bool {
	if o != nil && !IsNil(o.SafetyTags) {
		return true
	}

	return false
}

// SetSafetyTags gets a reference to the given []string and assigns it to the SafetyTags field.
func (o *CodebaseChunkDetailResponse) SetSafetyTags(v []string) {
	o.SafetyTags = v
}

// GetPagerankCentrality returns the PagerankCentrality field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseChunkDetailResponse) GetPagerankCentrality() float32 {
	if o == nil || IsNil(o.PagerankCentrality.Get()) {
		var ret float32
		return ret
	}
	return *o.PagerankCentrality.Get()
}

// GetPagerankCentralityOk returns a tuple with the PagerankCentrality field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseChunkDetailResponse) GetPagerankCentralityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PagerankCentrality.Get(), o.PagerankCentrality.IsSet()
}

// HasPagerankCentrality returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasPagerankCentrality() bool {
	if o != nil && o.PagerankCentrality.IsSet() {
		return true
	}

	return false
}

// SetPagerankCentrality gets a reference to the given NullableFloat32 and assigns it to the PagerankCentrality field.
func (o *CodebaseChunkDetailResponse) SetPagerankCentrality(v float32) {
	o.PagerankCentrality.Set(&v)
}
// SetPagerankCentralityNil sets the value for PagerankCentrality to be an explicit nil
func (o *CodebaseChunkDetailResponse) SetPagerankCentralityNil() {
	o.PagerankCentrality.Set(nil)
}

// UnsetPagerankCentrality ensures that no value is present for PagerankCentrality, not even an explicit nil
func (o *CodebaseChunkDetailResponse) UnsetPagerankCentrality() {
	o.PagerankCentrality.Unset()
}

// GetFaninCount returns the FaninCount field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetFaninCount() int32 {
	if o == nil || IsNil(o.FaninCount) {
		var ret int32
		return ret
	}
	return *o.FaninCount
}

// GetFaninCountOk returns a tuple with the FaninCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetFaninCountOk() (*int32, bool) {
	if o == nil || IsNil(o.FaninCount) {
		return nil, false
	}
	return o.FaninCount, true
}

// HasFaninCount returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasFaninCount() bool {
	if o != nil && !IsNil(o.FaninCount) {
		return true
	}

	return false
}

// SetFaninCount gets a reference to the given int32 and assigns it to the FaninCount field.
func (o *CodebaseChunkDetailResponse) SetFaninCount(v int32) {
	o.FaninCount = &v
}

// GetSnapshotId returns the SnapshotId field value
func (o *CodebaseChunkDetailResponse) GetSnapshotId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SnapshotId
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnapshotId, true
}

// SetSnapshotId sets field value
func (o *CodebaseChunkDetailResponse) SetSnapshotId(v string) {
	o.SnapshotId = v
}

// GetContentText returns the ContentText field value
func (o *CodebaseChunkDetailResponse) GetContentText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentText
}

// GetContentTextOk returns a tuple with the ContentText field value
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetContentTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentText, true
}

// SetContentText sets field value
func (o *CodebaseChunkDetailResponse) SetContentText(v string) {
	o.ContentText = v
}

// GetRelatedChunks returns the RelatedChunks field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetRelatedChunks() []CodebaseChunkRelatedItemResponse {
	if o == nil || IsNil(o.RelatedChunks) {
		var ret []CodebaseChunkRelatedItemResponse
		return ret
	}
	return o.RelatedChunks
}

// GetRelatedChunksOk returns a tuple with the RelatedChunks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetRelatedChunksOk() ([]CodebaseChunkRelatedItemResponse, bool) {
	if o == nil || IsNil(o.RelatedChunks) {
		return nil, false
	}
	return o.RelatedChunks, true
}

// HasRelatedChunks returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasRelatedChunks() bool {
	if o != nil && !IsNil(o.RelatedChunks) {
		return true
	}

	return false
}

// SetRelatedChunks gets a reference to the given []CodebaseChunkRelatedItemResponse and assigns it to the RelatedChunks field.
func (o *CodebaseChunkDetailResponse) SetRelatedChunks(v []CodebaseChunkRelatedItemResponse) {
	o.RelatedChunks = v
}

// GetSymbols returns the Symbols field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetSymbols() []CodebaseSymbolMatchResponse {
	if o == nil || IsNil(o.Symbols) {
		var ret []CodebaseSymbolMatchResponse
		return ret
	}
	return o.Symbols
}

// GetSymbolsOk returns a tuple with the Symbols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetSymbolsOk() ([]CodebaseSymbolMatchResponse, bool) {
	if o == nil || IsNil(o.Symbols) {
		return nil, false
	}
	return o.Symbols, true
}

// HasSymbols returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasSymbols() bool {
	if o != nil && !IsNil(o.Symbols) {
		return true
	}

	return false
}

// SetSymbols gets a reference to the given []CodebaseSymbolMatchResponse and assigns it to the Symbols field.
func (o *CodebaseChunkDetailResponse) SetSymbols(v []CodebaseSymbolMatchResponse) {
	o.Symbols = v
}

// GetImpactEdges returns the ImpactEdges field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetImpactEdges() []CodebaseImpactEdgeResponse {
	if o == nil || IsNil(o.ImpactEdges) {
		var ret []CodebaseImpactEdgeResponse
		return ret
	}
	return o.ImpactEdges
}

// GetImpactEdgesOk returns a tuple with the ImpactEdges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetImpactEdgesOk() ([]CodebaseImpactEdgeResponse, bool) {
	if o == nil || IsNil(o.ImpactEdges) {
		return nil, false
	}
	return o.ImpactEdges, true
}

// HasImpactEdges returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasImpactEdges() bool {
	if o != nil && !IsNil(o.ImpactEdges) {
		return true
	}

	return false
}

// SetImpactEdges gets a reference to the given []CodebaseImpactEdgeResponse and assigns it to the ImpactEdges field.
func (o *CodebaseChunkDetailResponse) SetImpactEdges(v []CodebaseImpactEdgeResponse) {
	o.ImpactEdges = v
}

// GetClusterMembers returns the ClusterMembers field value if set, zero value otherwise.
func (o *CodebaseChunkDetailResponse) GetClusterMembers() []CodebaseChunkRelatedItemResponse {
	if o == nil || IsNil(o.ClusterMembers) {
		var ret []CodebaseChunkRelatedItemResponse
		return ret
	}
	return o.ClusterMembers
}

// GetClusterMembersOk returns a tuple with the ClusterMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseChunkDetailResponse) GetClusterMembersOk() ([]CodebaseChunkRelatedItemResponse, bool) {
	if o == nil || IsNil(o.ClusterMembers) {
		return nil, false
	}
	return o.ClusterMembers, true
}

// HasClusterMembers returns a boolean if a field has been set.
func (o *CodebaseChunkDetailResponse) HasClusterMembers() bool {
	if o != nil && !IsNil(o.ClusterMembers) {
		return true
	}

	return false
}

// SetClusterMembers gets a reference to the given []CodebaseChunkRelatedItemResponse and assigns it to the ClusterMembers field.
func (o *CodebaseChunkDetailResponse) SetClusterMembers(v []CodebaseChunkRelatedItemResponse) {
	o.ClusterMembers = v
}

func (o CodebaseChunkDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseChunkDetailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["chunk_key"] = o.ChunkKey
	toSerialize["path"] = o.Path
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	toSerialize["kind"] = o.Kind
	toSerialize["label"] = o.Label
	toSerialize["preview_text"] = o.PreviewText
	toSerialize["start_line"] = o.StartLine
	toSerialize["end_line"] = o.EndLine
	if o.Container.IsSet() {
		toSerialize["container"] = o.Container.Get()
	}
	if o.ParentSymbol.IsSet() {
		toSerialize["parent_symbol"] = o.ParentSymbol.Get()
	}
	if o.ParentFqName.IsSet() {
		toSerialize["parent_fq_name"] = o.ParentFqName.Get()
	}
	if !IsNil(o.ParseConfidence) {
		toSerialize["parse_confidence"] = o.ParseConfidence
	}
	if o.ClusterId.IsSet() {
		toSerialize["cluster_id"] = o.ClusterId.Get()
	}
	if o.ClusterLabel.IsSet() {
		toSerialize["cluster_label"] = o.ClusterLabel.Get()
	}
	toSerialize["route_target"] = o.RouteTarget
	if o.RouteSource.IsSet() {
		toSerialize["route_source"] = o.RouteSource.Get()
	}
	toSerialize["change_kind"] = o.ChangeKind
	if !IsNil(o.RelatedCount) {
		toSerialize["related_count"] = o.RelatedCount
	}
	if o.DocumentId.IsSet() {
		toSerialize["document_id"] = o.DocumentId.Get()
	}
	if !IsNil(o.SignificanceScore) {
		toSerialize["significance_score"] = o.SignificanceScore
	}
	if o.SignificanceComponents != nil {
		toSerialize["significance_components"] = o.SignificanceComponents
	}
	if o.FileRole.IsSet() {
		toSerialize["file_role"] = o.FileRole.Get()
	}
	if o.AutoRouteReason.IsSet() {
		toSerialize["auto_route_reason"] = o.AutoRouteReason.Get()
	}
	if o.ComplexityScore.IsSet() {
		toSerialize["complexity_score"] = o.ComplexityScore.Get()
	}
	if !IsNil(o.SafetyTags) {
		toSerialize["safety_tags"] = o.SafetyTags
	}
	if o.PagerankCentrality.IsSet() {
		toSerialize["pagerank_centrality"] = o.PagerankCentrality.Get()
	}
	if !IsNil(o.FaninCount) {
		toSerialize["fanin_count"] = o.FaninCount
	}
	toSerialize["snapshot_id"] = o.SnapshotId
	toSerialize["content_text"] = o.ContentText
	if !IsNil(o.RelatedChunks) {
		toSerialize["related_chunks"] = o.RelatedChunks
	}
	if !IsNil(o.Symbols) {
		toSerialize["symbols"] = o.Symbols
	}
	if !IsNil(o.ImpactEdges) {
		toSerialize["impact_edges"] = o.ImpactEdges
	}
	if !IsNil(o.ClusterMembers) {
		toSerialize["cluster_members"] = o.ClusterMembers
	}
	return toSerialize, nil
}

func (o *CodebaseChunkDetailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"chunk_key",
		"path",
		"kind",
		"label",
		"preview_text",
		"start_line",
		"end_line",
		"route_target",
		"change_kind",
		"snapshot_id",
		"content_text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseChunkDetailResponse := _CodebaseChunkDetailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseChunkDetailResponse)

	if err != nil {
		return err
	}

	*o = CodebaseChunkDetailResponse(varCodebaseChunkDetailResponse)

	return err
}

type NullableCodebaseChunkDetailResponse struct {
	value *CodebaseChunkDetailResponse
	isSet bool
}

func (v NullableCodebaseChunkDetailResponse) Get() *CodebaseChunkDetailResponse {
	return v.value
}

func (v *NullableCodebaseChunkDetailResponse) Set(val *CodebaseChunkDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseChunkDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseChunkDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseChunkDetailResponse(val *CodebaseChunkDetailResponse) *NullableCodebaseChunkDetailResponse {
	return &NullableCodebaseChunkDetailResponse{value: val, isSet: true}
}

func (v NullableCodebaseChunkDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseChunkDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


