/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMRequestRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMRequestRow{}

// LLMRequestRow A single row in an LLM request trace.
type LLMRequestRow struct {
	Id string `json:"id"`
	BankId NullableString `json:"bank_id,omitempty"`
	Operation NullableString `json:"operation,omitempty"`
	Scope NullableString `json:"scope,omitempty"`
	TraceId NullableString `json:"trace_id,omitempty"`
	SpanId NullableString `json:"span_id,omitempty"`
	ParentSpanId NullableString `json:"parent_span_id,omitempty"`
	Provider NullableString `json:"provider,omitempty"`
	Model NullableString `json:"model,omitempty"`
	Status string `json:"status"`
	StartedAt string `json:"started_at"`
	EndedAt NullableString `json:"ended_at,omitempty"`
	DurationMs NullableInt32 `json:"duration_ms,omitempty"`
	InputTokens NullableInt32 `json:"input_tokens,omitempty"`
	OutputTokens NullableInt32 `json:"output_tokens,omitempty"`
	CachedTokens NullableInt32 `json:"cached_tokens,omitempty"`
	TotalTokens NullableInt32 `json:"total_tokens,omitempty"`
	Input map[string]interface{} `json:"input,omitempty"`
	Output map[string]interface{} `json:"output,omitempty"`
	Error map[string]interface{} `json:"error,omitempty"`
	LlmInfo map[string]interface{} `json:"llm_info,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _LLMRequestRow LLMRequestRow

// NewLLMRequestRow instantiates a new LLMRequestRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMRequestRow(id string, status string, startedAt string) *LLMRequestRow {
	this := LLMRequestRow{}
	this.Id = id
	this.Status = status
	this.StartedAt = startedAt
	return &this
}

// NewLLMRequestRowWithDefaults instantiates a new LLMRequestRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMRequestRowWithDefaults() *LLMRequestRow {
	this := LLMRequestRow{}
	return &this
}

// GetId returns the Id field value
func (o *LLMRequestRow) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LLMRequestRow) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LLMRequestRow) SetId(v string) {
	o.Id = v
}

// GetBankId returns the BankId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetBankId() string {
	if o == nil || IsNil(o.BankId.Get()) {
		var ret string
		return ret
	}
	return *o.BankId.Get()
}

// GetBankIdOk returns a tuple with the BankId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BankId.Get(), o.BankId.IsSet()
}

// HasBankId returns a boolean if a field has been set.
func (o *LLMRequestRow) HasBankId() bool {
	if o != nil && o.BankId.IsSet() {
		return true
	}

	return false
}

// SetBankId gets a reference to the given NullableString and assigns it to the BankId field.
func (o *LLMRequestRow) SetBankId(v string) {
	o.BankId.Set(&v)
}
// SetBankIdNil sets the value for BankId to be an explicit nil
func (o *LLMRequestRow) SetBankIdNil() {
	o.BankId.Set(nil)
}

// UnsetBankId ensures that no value is present for BankId, not even an explicit nil
func (o *LLMRequestRow) UnsetBankId() {
	o.BankId.Unset()
}

// GetOperation returns the Operation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetOperation() string {
	if o == nil || IsNil(o.Operation.Get()) {
		var ret string
		return ret
	}
	return *o.Operation.Get()
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operation.Get(), o.Operation.IsSet()
}

// HasOperation returns a boolean if a field has been set.
func (o *LLMRequestRow) HasOperation() bool {
	if o != nil && o.Operation.IsSet() {
		return true
	}

	return false
}

// SetOperation gets a reference to the given NullableString and assigns it to the Operation field.
func (o *LLMRequestRow) SetOperation(v string) {
	o.Operation.Set(&v)
}
// SetOperationNil sets the value for Operation to be an explicit nil
func (o *LLMRequestRow) SetOperationNil() {
	o.Operation.Set(nil)
}

// UnsetOperation ensures that no value is present for Operation, not even an explicit nil
func (o *LLMRequestRow) UnsetOperation() {
	o.Operation.Unset()
}

// GetScope returns the Scope field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetScope() string {
	if o == nil || IsNil(o.Scope.Get()) {
		var ret string
		return ret
	}
	return *o.Scope.Get()
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope.Get(), o.Scope.IsSet()
}

// HasScope returns a boolean if a field has been set.
func (o *LLMRequestRow) HasScope() bool {
	if o != nil && o.Scope.IsSet() {
		return true
	}

	return false
}

// SetScope gets a reference to the given NullableString and assigns it to the Scope field.
func (o *LLMRequestRow) SetScope(v string) {
	o.Scope.Set(&v)
}
// SetScopeNil sets the value for Scope to be an explicit nil
func (o *LLMRequestRow) SetScopeNil() {
	o.Scope.Set(nil)
}

// UnsetScope ensures that no value is present for Scope, not even an explicit nil
func (o *LLMRequestRow) UnsetScope() {
	o.Scope.Unset()
}

// GetTraceId returns the TraceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetTraceId() string {
	if o == nil || IsNil(o.TraceId.Get()) {
		var ret string
		return ret
	}
	return *o.TraceId.Get()
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TraceId.Get(), o.TraceId.IsSet()
}

// HasTraceId returns a boolean if a field has been set.
func (o *LLMRequestRow) HasTraceId() bool {
	if o != nil && o.TraceId.IsSet() {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given NullableString and assigns it to the TraceId field.
func (o *LLMRequestRow) SetTraceId(v string) {
	o.TraceId.Set(&v)
}
// SetTraceIdNil sets the value for TraceId to be an explicit nil
func (o *LLMRequestRow) SetTraceIdNil() {
	o.TraceId.Set(nil)
}

// UnsetTraceId ensures that no value is present for TraceId, not even an explicit nil
func (o *LLMRequestRow) UnsetTraceId() {
	o.TraceId.Unset()
}

// GetSpanId returns the SpanId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetSpanId() string {
	if o == nil || IsNil(o.SpanId.Get()) {
		var ret string
		return ret
	}
	return *o.SpanId.Get()
}

// GetSpanIdOk returns a tuple with the SpanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetSpanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpanId.Get(), o.SpanId.IsSet()
}

// HasSpanId returns a boolean if a field has been set.
func (o *LLMRequestRow) HasSpanId() bool {
	if o != nil && o.SpanId.IsSet() {
		return true
	}

	return false
}

// SetSpanId gets a reference to the given NullableString and assigns it to the SpanId field.
func (o *LLMRequestRow) SetSpanId(v string) {
	o.SpanId.Set(&v)
}
// SetSpanIdNil sets the value for SpanId to be an explicit nil
func (o *LLMRequestRow) SetSpanIdNil() {
	o.SpanId.Set(nil)
}

// UnsetSpanId ensures that no value is present for SpanId, not even an explicit nil
func (o *LLMRequestRow) UnsetSpanId() {
	o.SpanId.Unset()
}

// GetParentSpanId returns the ParentSpanId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetParentSpanId() string {
	if o == nil || IsNil(o.ParentSpanId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentSpanId.Get()
}

// GetParentSpanIdOk returns a tuple with the ParentSpanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetParentSpanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentSpanId.Get(), o.ParentSpanId.IsSet()
}

// HasParentSpanId returns a boolean if a field has been set.
func (o *LLMRequestRow) HasParentSpanId() bool {
	if o != nil && o.ParentSpanId.IsSet() {
		return true
	}

	return false
}

// SetParentSpanId gets a reference to the given NullableString and assigns it to the ParentSpanId field.
func (o *LLMRequestRow) SetParentSpanId(v string) {
	o.ParentSpanId.Set(&v)
}
// SetParentSpanIdNil sets the value for ParentSpanId to be an explicit nil
func (o *LLMRequestRow) SetParentSpanIdNil() {
	o.ParentSpanId.Set(nil)
}

// UnsetParentSpanId ensures that no value is present for ParentSpanId, not even an explicit nil
func (o *LLMRequestRow) UnsetParentSpanId() {
	o.ParentSpanId.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *LLMRequestRow) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *LLMRequestRow) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *LLMRequestRow) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *LLMRequestRow) UnsetProvider() {
	o.Provider.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *LLMRequestRow) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *LLMRequestRow) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *LLMRequestRow) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *LLMRequestRow) UnsetModel() {
	o.Model.Unset()
}

// GetStatus returns the Status field value
func (o *LLMRequestRow) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LLMRequestRow) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LLMRequestRow) SetStatus(v string) {
	o.Status = v
}

// GetStartedAt returns the StartedAt field value
func (o *LLMRequestRow) GetStartedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *LLMRequestRow) GetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *LLMRequestRow) SetStartedAt(v string) {
	o.StartedAt = v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetEndedAt() string {
	if o == nil || IsNil(o.EndedAt.Get()) {
		var ret string
		return ret
	}
	return *o.EndedAt.Get()
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetEndedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndedAt.Get(), o.EndedAt.IsSet()
}

// HasEndedAt returns a boolean if a field has been set.
func (o *LLMRequestRow) HasEndedAt() bool {
	if o != nil && o.EndedAt.IsSet() {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given NullableString and assigns it to the EndedAt field.
func (o *LLMRequestRow) SetEndedAt(v string) {
	o.EndedAt.Set(&v)
}
// SetEndedAtNil sets the value for EndedAt to be an explicit nil
func (o *LLMRequestRow) SetEndedAtNil() {
	o.EndedAt.Set(nil)
}

// UnsetEndedAt ensures that no value is present for EndedAt, not even an explicit nil
func (o *LLMRequestRow) UnsetEndedAt() {
	o.EndedAt.Unset()
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs.Get()) {
		var ret int32
		return ret
	}
	return *o.DurationMs.Get()
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationMs.Get(), o.DurationMs.IsSet()
}

// HasDurationMs returns a boolean if a field has been set.
func (o *LLMRequestRow) HasDurationMs() bool {
	if o != nil && o.DurationMs.IsSet() {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given NullableInt32 and assigns it to the DurationMs field.
func (o *LLMRequestRow) SetDurationMs(v int32) {
	o.DurationMs.Set(&v)
}
// SetDurationMsNil sets the value for DurationMs to be an explicit nil
func (o *LLMRequestRow) SetDurationMsNil() {
	o.DurationMs.Set(nil)
}

// UnsetDurationMs ensures that no value is present for DurationMs, not even an explicit nil
func (o *LLMRequestRow) UnsetDurationMs() {
	o.DurationMs.Unset()
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetInputTokens() int32 {
	if o == nil || IsNil(o.InputTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.InputTokens.Get()
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetInputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputTokens.Get(), o.InputTokens.IsSet()
}

// HasInputTokens returns a boolean if a field has been set.
func (o *LLMRequestRow) HasInputTokens() bool {
	if o != nil && o.InputTokens.IsSet() {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given NullableInt32 and assigns it to the InputTokens field.
func (o *LLMRequestRow) SetInputTokens(v int32) {
	o.InputTokens.Set(&v)
}
// SetInputTokensNil sets the value for InputTokens to be an explicit nil
func (o *LLMRequestRow) SetInputTokensNil() {
	o.InputTokens.Set(nil)
}

// UnsetInputTokens ensures that no value is present for InputTokens, not even an explicit nil
func (o *LLMRequestRow) UnsetInputTokens() {
	o.InputTokens.Unset()
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetOutputTokens() int32 {
	if o == nil || IsNil(o.OutputTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.OutputTokens.Get()
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetOutputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputTokens.Get(), o.OutputTokens.IsSet()
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *LLMRequestRow) HasOutputTokens() bool {
	if o != nil && o.OutputTokens.IsSet() {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given NullableInt32 and assigns it to the OutputTokens field.
func (o *LLMRequestRow) SetOutputTokens(v int32) {
	o.OutputTokens.Set(&v)
}
// SetOutputTokensNil sets the value for OutputTokens to be an explicit nil
func (o *LLMRequestRow) SetOutputTokensNil() {
	o.OutputTokens.Set(nil)
}

// UnsetOutputTokens ensures that no value is present for OutputTokens, not even an explicit nil
func (o *LLMRequestRow) UnsetOutputTokens() {
	o.OutputTokens.Unset()
}

// GetCachedTokens returns the CachedTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetCachedTokens() int32 {
	if o == nil || IsNil(o.CachedTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.CachedTokens.Get()
}

// GetCachedTokensOk returns a tuple with the CachedTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetCachedTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CachedTokens.Get(), o.CachedTokens.IsSet()
}

// HasCachedTokens returns a boolean if a field has been set.
func (o *LLMRequestRow) HasCachedTokens() bool {
	if o != nil && o.CachedTokens.IsSet() {
		return true
	}

	return false
}

// SetCachedTokens gets a reference to the given NullableInt32 and assigns it to the CachedTokens field.
func (o *LLMRequestRow) SetCachedTokens(v int32) {
	o.CachedTokens.Set(&v)
}
// SetCachedTokensNil sets the value for CachedTokens to be an explicit nil
func (o *LLMRequestRow) SetCachedTokensNil() {
	o.CachedTokens.Set(nil)
}

// UnsetCachedTokens ensures that no value is present for CachedTokens, not even an explicit nil
func (o *LLMRequestRow) UnsetCachedTokens() {
	o.CachedTokens.Unset()
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetTotalTokens() int32 {
	if o == nil || IsNil(o.TotalTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalTokens.Get()
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetTotalTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalTokens.Get(), o.TotalTokens.IsSet()
}

// HasTotalTokens returns a boolean if a field has been set.
func (o *LLMRequestRow) HasTotalTokens() bool {
	if o != nil && o.TotalTokens.IsSet() {
		return true
	}

	return false
}

// SetTotalTokens gets a reference to the given NullableInt32 and assigns it to the TotalTokens field.
func (o *LLMRequestRow) SetTotalTokens(v int32) {
	o.TotalTokens.Set(&v)
}
// SetTotalTokensNil sets the value for TotalTokens to be an explicit nil
func (o *LLMRequestRow) SetTotalTokensNil() {
	o.TotalTokens.Set(nil)
}

// UnsetTotalTokens ensures that no value is present for TotalTokens, not even an explicit nil
func (o *LLMRequestRow) UnsetTotalTokens() {
	o.TotalTokens.Unset()
}

// GetInput returns the Input field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetInput() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetInputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Input) {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *LLMRequestRow) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given map[string]interface{} and assigns it to the Input field.
func (o *LLMRequestRow) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetOutput returns the Output field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetOutput() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetOutputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Output) {
		return map[string]interface{}{}, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *LLMRequestRow) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given map[string]interface{} and assigns it to the Output field.
func (o *LLMRequestRow) SetOutput(v map[string]interface{}) {
	o.Output = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetError() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetErrorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Error) {
		return map[string]interface{}{}, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *LLMRequestRow) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given map[string]interface{} and assigns it to the Error field.
func (o *LLMRequestRow) SetError(v map[string]interface{}) {
	o.Error = v
}

// GetLlmInfo returns the LlmInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetLlmInfo() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.LlmInfo
}

// GetLlmInfoOk returns a tuple with the LlmInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetLlmInfoOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.LlmInfo) {
		return map[string]interface{}{}, false
	}
	return o.LlmInfo, true
}

// HasLlmInfo returns a boolean if a field has been set.
func (o *LLMRequestRow) HasLlmInfo() bool {
	if o != nil && !IsNil(o.LlmInfo) {
		return true
	}

	return false
}

// SetLlmInfo gets a reference to the given map[string]interface{} and assigns it to the LlmInfo field.
func (o *LLMRequestRow) SetLlmInfo(v map[string]interface{}) {
	o.LlmInfo = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LLMRequestRow) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LLMRequestRow) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *LLMRequestRow) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *LLMRequestRow) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o LLMRequestRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMRequestRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.BankId.IsSet() {
		toSerialize["bank_id"] = o.BankId.Get()
	}
	if o.Operation.IsSet() {
		toSerialize["operation"] = o.Operation.Get()
	}
	if o.Scope.IsSet() {
		toSerialize["scope"] = o.Scope.Get()
	}
	if o.TraceId.IsSet() {
		toSerialize["trace_id"] = o.TraceId.Get()
	}
	if o.SpanId.IsSet() {
		toSerialize["span_id"] = o.SpanId.Get()
	}
	if o.ParentSpanId.IsSet() {
		toSerialize["parent_span_id"] = o.ParentSpanId.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["started_at"] = o.StartedAt
	if o.EndedAt.IsSet() {
		toSerialize["ended_at"] = o.EndedAt.Get()
	}
	if o.DurationMs.IsSet() {
		toSerialize["duration_ms"] = o.DurationMs.Get()
	}
	if o.InputTokens.IsSet() {
		toSerialize["input_tokens"] = o.InputTokens.Get()
	}
	if o.OutputTokens.IsSet() {
		toSerialize["output_tokens"] = o.OutputTokens.Get()
	}
	if o.CachedTokens.IsSet() {
		toSerialize["cached_tokens"] = o.CachedTokens.Get()
	}
	if o.TotalTokens.IsSet() {
		toSerialize["total_tokens"] = o.TotalTokens.Get()
	}
	if o.Input != nil {
		toSerialize["input"] = o.Input
	}
	if o.Output != nil {
		toSerialize["output"] = o.Output
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.LlmInfo != nil {
		toSerialize["llm_info"] = o.LlmInfo
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *LLMRequestRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"started_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMRequestRow := _LLMRequestRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMRequestRow)

	if err != nil {
		return err
	}

	*o = LLMRequestRow(varLLMRequestRow)

	return err
}

type NullableLLMRequestRow struct {
	value *LLMRequestRow
	isSet bool
}

func (v NullableLLMRequestRow) Get() *LLMRequestRow {
	return v.value
}

func (v *NullableLLMRequestRow) Set(val *LLMRequestRow) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMRequestRow) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMRequestRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMRequestRow(val *LLMRequestRow) *NullableLLMRequestRow {
	return &NullableLLMRequestRow{value: val, isSet: true}
}

func (v NullableLLMRequestRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMRequestRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


