/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
)

// checks if the ServiceAccountUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceAccountUpdateRequest{}

// ServiceAccountUpdateRequest struct for ServiceAccountUpdateRequest
type ServiceAccountUpdateRequest struct {
	Name    NullableString `json:"name,omitempty"`
	RoleId  NullableString `json:"role_id,omitempty"`
	Status  NullableString `json:"status,omitempty"`
	BankIds []string       `json:"bank_ids,omitempty"`
}

// NewServiceAccountUpdateRequest instantiates a new ServiceAccountUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountUpdateRequest() *ServiceAccountUpdateRequest {
	this := ServiceAccountUpdateRequest{}
	return &this
}

// NewServiceAccountUpdateRequestWithDefaults instantiates a new ServiceAccountUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountUpdateRequestWithDefaults() *ServiceAccountUpdateRequest {
	this := ServiceAccountUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceAccountUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceAccountUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ServiceAccountUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ServiceAccountUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ServiceAccountUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ServiceAccountUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetRoleId returns the RoleId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceAccountUpdateRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId.Get()) {
		var ret string
		return ret
	}
	return *o.RoleId.Get()
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceAccountUpdateRequest) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoleId.Get(), o.RoleId.IsSet()
}

// HasRoleId returns a boolean if a field has been set.
func (o *ServiceAccountUpdateRequest) HasRoleId() bool {
	if o != nil && o.RoleId.IsSet() {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given NullableString and assigns it to the RoleId field.
func (o *ServiceAccountUpdateRequest) SetRoleId(v string) {
	o.RoleId.Set(&v)
}

// SetRoleIdNil sets the value for RoleId to be an explicit nil
func (o *ServiceAccountUpdateRequest) SetRoleIdNil() {
	o.RoleId.Set(nil)
}

// UnsetRoleId ensures that no value is present for RoleId, not even an explicit nil
func (o *ServiceAccountUpdateRequest) UnsetRoleId() {
	o.RoleId.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceAccountUpdateRequest) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceAccountUpdateRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *ServiceAccountUpdateRequest) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *ServiceAccountUpdateRequest) SetStatus(v string) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *ServiceAccountUpdateRequest) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *ServiceAccountUpdateRequest) UnsetStatus() {
	o.Status.Unset()
}

// GetBankIds returns the BankIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceAccountUpdateRequest) GetBankIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.BankIds
}

// GetBankIdsOk returns a tuple with the BankIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceAccountUpdateRequest) GetBankIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.BankIds) {
		return nil, false
	}
	return o.BankIds, true
}

// HasBankIds returns a boolean if a field has been set.
func (o *ServiceAccountUpdateRequest) HasBankIds() bool {
	if o != nil && !IsNil(o.BankIds) {
		return true
	}

	return false
}

// SetBankIds gets a reference to the given []string and assigns it to the BankIds field.
func (o *ServiceAccountUpdateRequest) SetBankIds(v []string) {
	o.BankIds = v
}

func (o ServiceAccountUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceAccountUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.RoleId.IsSet() {
		toSerialize["role_id"] = o.RoleId.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.BankIds != nil {
		toSerialize["bank_ids"] = o.BankIds
	}
	return toSerialize, nil
}

type NullableServiceAccountUpdateRequest struct {
	value *ServiceAccountUpdateRequest
	isSet bool
}

func (v NullableServiceAccountUpdateRequest) Get() *ServiceAccountUpdateRequest {
	return v.value
}

func (v *NullableServiceAccountUpdateRequest) Set(val *ServiceAccountUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountUpdateRequest(val *ServiceAccountUpdateRequest) *NullableServiceAccountUpdateRequest {
	return &NullableServiceAccountUpdateRequest{value: val, isSet: true}
}

func (v NullableServiceAccountUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
