/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimelineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineResponse{}

// TimelineResponse struct for TimelineResponse
type TimelineResponse struct {
	Items []TimelineItemResponse `json:"items,omitempty"`
	Edges []TimelineEdgeResponse `json:"edges,omitempty"`
	TotalItems int32 `json:"total_items"`
	Limit int32 `json:"limit"`
}

type _TimelineResponse TimelineResponse

// NewTimelineResponse instantiates a new TimelineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineResponse(totalItems int32, limit int32) *TimelineResponse {
	this := TimelineResponse{}
	this.TotalItems = totalItems
	this.Limit = limit
	return &this
}

// NewTimelineResponseWithDefaults instantiates a new TimelineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineResponseWithDefaults() *TimelineResponse {
	this := TimelineResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *TimelineResponse) GetItems() []TimelineItemResponse {
	if o == nil || IsNil(o.Items) {
		var ret []TimelineItemResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponse) GetItemsOk() ([]TimelineItemResponse, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *TimelineResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TimelineItemResponse and assigns it to the Items field.
func (o *TimelineResponse) SetItems(v []TimelineItemResponse) {
	o.Items = v
}

// GetEdges returns the Edges field value if set, zero value otherwise.
func (o *TimelineResponse) GetEdges() []TimelineEdgeResponse {
	if o == nil || IsNil(o.Edges) {
		var ret []TimelineEdgeResponse
		return ret
	}
	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponse) GetEdgesOk() ([]TimelineEdgeResponse, bool) {
	if o == nil || IsNil(o.Edges) {
		return nil, false
	}
	return o.Edges, true
}

// HasEdges returns a boolean if a field has been set.
func (o *TimelineResponse) HasEdges() bool {
	if o != nil && !IsNil(o.Edges) {
		return true
	}

	return false
}

// SetEdges gets a reference to the given []TimelineEdgeResponse and assigns it to the Edges field.
func (o *TimelineResponse) SetEdges(v []TimelineEdgeResponse) {
	o.Edges = v
}

// GetTotalItems returns the TotalItems field value
func (o *TimelineResponse) GetTotalItems() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value
// and a boolean to check if the value has been set.
func (o *TimelineResponse) GetTotalItemsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalItems, true
}

// SetTotalItems sets field value
func (o *TimelineResponse) SetTotalItems(v int32) {
	o.TotalItems = v
}

// GetLimit returns the Limit field value
func (o *TimelineResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *TimelineResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *TimelineResponse) SetLimit(v int32) {
	o.Limit = v
}

func (o TimelineResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Edges) {
		toSerialize["edges"] = o.Edges
	}
	toSerialize["total_items"] = o.TotalItems
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

func (o *TimelineResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_items",
		"limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimelineResponse := _TimelineResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimelineResponse)

	if err != nil {
		return err
	}

	*o = TimelineResponse(varTimelineResponse)

	return err
}

type NullableTimelineResponse struct {
	value *TimelineResponse
	isSet bool
}

func (v NullableTimelineResponse) Get() *TimelineResponse {
	return v.value
}

func (v *NullableTimelineResponse) Set(val *TimelineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineResponse(val *TimelineResponse) *NullableTimelineResponse {
	return &NullableTimelineResponse{value: val, isSet: true}
}

func (v NullableTimelineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


