/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseImportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseImportResponse{}

// CodebaseImportResponse Queued codebase import response.
type CodebaseImportResponse struct {
	CodebaseId string `json:"codebase_id"`
	SnapshotId string `json:"snapshot_id"`
	OperationId string `json:"operation_id"`
	Status string `json:"status"`
}

type _CodebaseImportResponse CodebaseImportResponse

// NewCodebaseImportResponse instantiates a new CodebaseImportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseImportResponse(codebaseId string, snapshotId string, operationId string, status string) *CodebaseImportResponse {
	this := CodebaseImportResponse{}
	this.CodebaseId = codebaseId
	this.SnapshotId = snapshotId
	this.OperationId = operationId
	this.Status = status
	return &this
}

// NewCodebaseImportResponseWithDefaults instantiates a new CodebaseImportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseImportResponseWithDefaults() *CodebaseImportResponse {
	this := CodebaseImportResponse{}
	return &this
}

// GetCodebaseId returns the CodebaseId field value
func (o *CodebaseImportResponse) GetCodebaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodebaseId
}

// GetCodebaseIdOk returns a tuple with the CodebaseId field value
// and a boolean to check if the value has been set.
func (o *CodebaseImportResponse) GetCodebaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodebaseId, true
}

// SetCodebaseId sets field value
func (o *CodebaseImportResponse) SetCodebaseId(v string) {
	o.CodebaseId = v
}

// GetSnapshotId returns the SnapshotId field value
func (o *CodebaseImportResponse) GetSnapshotId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SnapshotId
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value
// and a boolean to check if the value has been set.
func (o *CodebaseImportResponse) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnapshotId, true
}

// SetSnapshotId sets field value
func (o *CodebaseImportResponse) SetSnapshotId(v string) {
	o.SnapshotId = v
}

// GetOperationId returns the OperationId field value
func (o *CodebaseImportResponse) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *CodebaseImportResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *CodebaseImportResponse) SetOperationId(v string) {
	o.OperationId = v
}

// GetStatus returns the Status field value
func (o *CodebaseImportResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CodebaseImportResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CodebaseImportResponse) SetStatus(v string) {
	o.Status = v
}

func (o CodebaseImportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseImportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codebase_id"] = o.CodebaseId
	toSerialize["snapshot_id"] = o.SnapshotId
	toSerialize["operation_id"] = o.OperationId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *CodebaseImportResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codebase_id",
		"snapshot_id",
		"operation_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseImportResponse := _CodebaseImportResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseImportResponse)

	if err != nil {
		return err
	}

	*o = CodebaseImportResponse(varCodebaseImportResponse)

	return err
}

type NullableCodebaseImportResponse struct {
	value *CodebaseImportResponse
	isSet bool
}

func (v NullableCodebaseImportResponse) Get() *CodebaseImportResponse {
	return v.value
}

func (v *NullableCodebaseImportResponse) Set(val *CodebaseImportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseImportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseImportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseImportResponse(val *CodebaseImportResponse) *NullableCodebaseImportResponse {
	return &NullableCodebaseImportResponse{value: val, isSet: true}
}

func (v NullableCodebaseImportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseImportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


