/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TasteRetainSubmitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasteRetainSubmitRequest{}

// TasteRetainSubmitRequest struct for TasteRetainSubmitRequest
type TasteRetainSubmitRequest struct {
	SetIds []string `json:"set_ids"`
}

type _TasteRetainSubmitRequest TasteRetainSubmitRequest

// NewTasteRetainSubmitRequest instantiates a new TasteRetainSubmitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasteRetainSubmitRequest(setIds []string) *TasteRetainSubmitRequest {
	this := TasteRetainSubmitRequest{}
	this.SetIds = setIds
	return &this
}

// NewTasteRetainSubmitRequestWithDefaults instantiates a new TasteRetainSubmitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasteRetainSubmitRequestWithDefaults() *TasteRetainSubmitRequest {
	this := TasteRetainSubmitRequest{}
	return &this
}

// GetSetIds returns the SetIds field value
func (o *TasteRetainSubmitRequest) GetSetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SetIds
}

// GetSetIdsOk returns a tuple with the SetIds field value
// and a boolean to check if the value has been set.
func (o *TasteRetainSubmitRequest) GetSetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SetIds, true
}

// SetSetIds sets field value
func (o *TasteRetainSubmitRequest) SetSetIds(v []string) {
	o.SetIds = v
}

func (o TasteRetainSubmitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasteRetainSubmitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["set_ids"] = o.SetIds
	return toSerialize, nil
}

func (o *TasteRetainSubmitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"set_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTasteRetainSubmitRequest := _TasteRetainSubmitRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTasteRetainSubmitRequest)

	if err != nil {
		return err
	}

	*o = TasteRetainSubmitRequest(varTasteRetainSubmitRequest)

	return err
}

type NullableTasteRetainSubmitRequest struct {
	value *TasteRetainSubmitRequest
	isSet bool
}

func (v NullableTasteRetainSubmitRequest) Get() *TasteRetainSubmitRequest {
	return v.value
}

func (v *NullableTasteRetainSubmitRequest) Set(val *TasteRetainSubmitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTasteRetainSubmitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTasteRetainSubmitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasteRetainSubmitRequest(val *TasteRetainSubmitRequest) *NullableTasteRetainSubmitRequest {
	return &NullableTasteRetainSubmitRequest{value: val, isSet: true}
}

func (v NullableTasteRetainSubmitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasteRetainSubmitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


