/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
)

// checks if the CodebaseSourceConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseSourceConfigResponse{}

// CodebaseSourceConfigResponse Normalized source configuration for a codebase.
type CodebaseSourceConfigResponse struct {
	Owner NullableString `json:"owner,omitempty"`
	Repo NullableString `json:"repo,omitempty"`
	RepoUrl NullableString `json:"repo_url,omitempty"`
	Ref NullableString `json:"ref,omitempty"`
	RootPath NullableString `json:"root_path,omitempty"`
	IncludeGlobs []string `json:"include_globs,omitempty"`
	ExcludeGlobs []string `json:"exclude_globs,omitempty"`
}

// NewCodebaseSourceConfigResponse instantiates a new CodebaseSourceConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseSourceConfigResponse() *CodebaseSourceConfigResponse {
	this := CodebaseSourceConfigResponse{}
	return &this
}

// NewCodebaseSourceConfigResponseWithDefaults instantiates a new CodebaseSourceConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseSourceConfigResponseWithDefaults() *CodebaseSourceConfigResponse {
	this := CodebaseSourceConfigResponse{}
	return &this
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseSourceConfigResponse) GetOwner() string {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret string
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseSourceConfigResponse) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableString and assigns it to the Owner field.
func (o *CodebaseSourceConfigResponse) SetOwner(v string) {
	o.Owner.Set(&v)
}
// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *CodebaseSourceConfigResponse) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *CodebaseSourceConfigResponse) UnsetOwner() {
	o.Owner.Unset()
}

// GetRepo returns the Repo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseSourceConfigResponse) GetRepo() string {
	if o == nil || IsNil(o.Repo.Get()) {
		var ret string
		return ret
	}
	return *o.Repo.Get()
}

// GetRepoOk returns a tuple with the Repo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseSourceConfigResponse) GetRepoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Repo.Get(), o.Repo.IsSet()
}

// HasRepo returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasRepo() bool {
	if o != nil && o.Repo.IsSet() {
		return true
	}

	return false
}

// SetRepo gets a reference to the given NullableString and assigns it to the Repo field.
func (o *CodebaseSourceConfigResponse) SetRepo(v string) {
	o.Repo.Set(&v)
}
// SetRepoNil sets the value for Repo to be an explicit nil
func (o *CodebaseSourceConfigResponse) SetRepoNil() {
	o.Repo.Set(nil)
}

// UnsetRepo ensures that no value is present for Repo, not even an explicit nil
func (o *CodebaseSourceConfigResponse) UnsetRepo() {
	o.Repo.Unset()
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseSourceConfigResponse) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.RepoUrl.Get()
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseSourceConfigResponse) GetRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RepoUrl.Get(), o.RepoUrl.IsSet()
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasRepoUrl() bool {
	if o != nil && o.RepoUrl.IsSet() {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given NullableString and assigns it to the RepoUrl field.
func (o *CodebaseSourceConfigResponse) SetRepoUrl(v string) {
	o.RepoUrl.Set(&v)
}
// SetRepoUrlNil sets the value for RepoUrl to be an explicit nil
func (o *CodebaseSourceConfigResponse) SetRepoUrlNil() {
	o.RepoUrl.Set(nil)
}

// UnsetRepoUrl ensures that no value is present for RepoUrl, not even an explicit nil
func (o *CodebaseSourceConfigResponse) UnsetRepoUrl() {
	o.RepoUrl.Unset()
}

// GetRef returns the Ref field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseSourceConfigResponse) GetRef() string {
	if o == nil || IsNil(o.Ref.Get()) {
		var ret string
		return ret
	}
	return *o.Ref.Get()
}

// GetRefOk returns a tuple with the Ref field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseSourceConfigResponse) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ref.Get(), o.Ref.IsSet()
}

// HasRef returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasRef() bool {
	if o != nil && o.Ref.IsSet() {
		return true
	}

	return false
}

// SetRef gets a reference to the given NullableString and assigns it to the Ref field.
func (o *CodebaseSourceConfigResponse) SetRef(v string) {
	o.Ref.Set(&v)
}
// SetRefNil sets the value for Ref to be an explicit nil
func (o *CodebaseSourceConfigResponse) SetRefNil() {
	o.Ref.Set(nil)
}

// UnsetRef ensures that no value is present for Ref, not even an explicit nil
func (o *CodebaseSourceConfigResponse) UnsetRef() {
	o.Ref.Unset()
}

// GetRootPath returns the RootPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseSourceConfigResponse) GetRootPath() string {
	if o == nil || IsNil(o.RootPath.Get()) {
		var ret string
		return ret
	}
	return *o.RootPath.Get()
}

// GetRootPathOk returns a tuple with the RootPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseSourceConfigResponse) GetRootPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RootPath.Get(), o.RootPath.IsSet()
}

// HasRootPath returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasRootPath() bool {
	if o != nil && o.RootPath.IsSet() {
		return true
	}

	return false
}

// SetRootPath gets a reference to the given NullableString and assigns it to the RootPath field.
func (o *CodebaseSourceConfigResponse) SetRootPath(v string) {
	o.RootPath.Set(&v)
}
// SetRootPathNil sets the value for RootPath to be an explicit nil
func (o *CodebaseSourceConfigResponse) SetRootPathNil() {
	o.RootPath.Set(nil)
}

// UnsetRootPath ensures that no value is present for RootPath, not even an explicit nil
func (o *CodebaseSourceConfigResponse) UnsetRootPath() {
	o.RootPath.Unset()
}

// GetIncludeGlobs returns the IncludeGlobs field value if set, zero value otherwise.
func (o *CodebaseSourceConfigResponse) GetIncludeGlobs() []string {
	if o == nil || IsNil(o.IncludeGlobs) {
		var ret []string
		return ret
	}
	return o.IncludeGlobs
}

// GetIncludeGlobsOk returns a tuple with the IncludeGlobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseSourceConfigResponse) GetIncludeGlobsOk() ([]string, bool) {
	if o == nil || IsNil(o.IncludeGlobs) {
		return nil, false
	}
	return o.IncludeGlobs, true
}

// HasIncludeGlobs returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasIncludeGlobs() bool {
	if o != nil && !IsNil(o.IncludeGlobs) {
		return true
	}

	return false
}

// SetIncludeGlobs gets a reference to the given []string and assigns it to the IncludeGlobs field.
func (o *CodebaseSourceConfigResponse) SetIncludeGlobs(v []string) {
	o.IncludeGlobs = v
}

// GetExcludeGlobs returns the ExcludeGlobs field value if set, zero value otherwise.
func (o *CodebaseSourceConfigResponse) GetExcludeGlobs() []string {
	if o == nil || IsNil(o.ExcludeGlobs) {
		var ret []string
		return ret
	}
	return o.ExcludeGlobs
}

// GetExcludeGlobsOk returns a tuple with the ExcludeGlobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseSourceConfigResponse) GetExcludeGlobsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeGlobs) {
		return nil, false
	}
	return o.ExcludeGlobs, true
}

// HasExcludeGlobs returns a boolean if a field has been set.
func (o *CodebaseSourceConfigResponse) HasExcludeGlobs() bool {
	if o != nil && !IsNil(o.ExcludeGlobs) {
		return true
	}

	return false
}

// SetExcludeGlobs gets a reference to the given []string and assigns it to the ExcludeGlobs field.
func (o *CodebaseSourceConfigResponse) SetExcludeGlobs(v []string) {
	o.ExcludeGlobs = v
}

func (o CodebaseSourceConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseSourceConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if o.Repo.IsSet() {
		toSerialize["repo"] = o.Repo.Get()
	}
	if o.RepoUrl.IsSet() {
		toSerialize["repo_url"] = o.RepoUrl.Get()
	}
	if o.Ref.IsSet() {
		toSerialize["ref"] = o.Ref.Get()
	}
	if o.RootPath.IsSet() {
		toSerialize["root_path"] = o.RootPath.Get()
	}
	if !IsNil(o.IncludeGlobs) {
		toSerialize["include_globs"] = o.IncludeGlobs
	}
	if !IsNil(o.ExcludeGlobs) {
		toSerialize["exclude_globs"] = o.ExcludeGlobs
	}
	return toSerialize, nil
}

type NullableCodebaseSourceConfigResponse struct {
	value *CodebaseSourceConfigResponse
	isSet bool
}

func (v NullableCodebaseSourceConfigResponse) Get() *CodebaseSourceConfigResponse {
	return v.value
}

func (v *NullableCodebaseSourceConfigResponse) Set(val *CodebaseSourceConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseSourceConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseSourceConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseSourceConfigResponse(val *CodebaseSourceConfigResponse) *NullableCodebaseSourceConfigResponse {
	return &NullableCodebaseSourceConfigResponse{value: val, isSet: true}
}

func (v NullableCodebaseSourceConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseSourceConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


