/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InfluenceHeatmapPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfluenceHeatmapPoint{}

// InfluenceHeatmapPoint struct for InfluenceHeatmapPoint
type InfluenceHeatmapPoint struct {
	Weekday int32 `json:"weekday"`
	HourUtc int32 `json:"hour_utc"`
	Count int32 `json:"count"`
	Score float32 `json:"score"`
}

type _InfluenceHeatmapPoint InfluenceHeatmapPoint

// NewInfluenceHeatmapPoint instantiates a new InfluenceHeatmapPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfluenceHeatmapPoint(weekday int32, hourUtc int32, count int32, score float32) *InfluenceHeatmapPoint {
	this := InfluenceHeatmapPoint{}
	this.Weekday = weekday
	this.HourUtc = hourUtc
	this.Count = count
	this.Score = score
	return &this
}

// NewInfluenceHeatmapPointWithDefaults instantiates a new InfluenceHeatmapPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfluenceHeatmapPointWithDefaults() *InfluenceHeatmapPoint {
	this := InfluenceHeatmapPoint{}
	return &this
}

// GetWeekday returns the Weekday field value
func (o *InfluenceHeatmapPoint) GetWeekday() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Weekday
}

// GetWeekdayOk returns a tuple with the Weekday field value
// and a boolean to check if the value has been set.
func (o *InfluenceHeatmapPoint) GetWeekdayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weekday, true
}

// SetWeekday sets field value
func (o *InfluenceHeatmapPoint) SetWeekday(v int32) {
	o.Weekday = v
}

// GetHourUtc returns the HourUtc field value
func (o *InfluenceHeatmapPoint) GetHourUtc() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HourUtc
}

// GetHourUtcOk returns a tuple with the HourUtc field value
// and a boolean to check if the value has been set.
func (o *InfluenceHeatmapPoint) GetHourUtcOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HourUtc, true
}

// SetHourUtc sets field value
func (o *InfluenceHeatmapPoint) SetHourUtc(v int32) {
	o.HourUtc = v
}

// GetCount returns the Count field value
func (o *InfluenceHeatmapPoint) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *InfluenceHeatmapPoint) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *InfluenceHeatmapPoint) SetCount(v int32) {
	o.Count = v
}

// GetScore returns the Score field value
func (o *InfluenceHeatmapPoint) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *InfluenceHeatmapPoint) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *InfluenceHeatmapPoint) SetScore(v float32) {
	o.Score = v
}

func (o InfluenceHeatmapPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfluenceHeatmapPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["weekday"] = o.Weekday
	toSerialize["hour_utc"] = o.HourUtc
	toSerialize["count"] = o.Count
	toSerialize["score"] = o.Score
	return toSerialize, nil
}

func (o *InfluenceHeatmapPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"weekday",
		"hour_utc",
		"count",
		"score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInfluenceHeatmapPoint := _InfluenceHeatmapPoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInfluenceHeatmapPoint)

	if err != nil {
		return err
	}

	*o = InfluenceHeatmapPoint(varInfluenceHeatmapPoint)

	return err
}

type NullableInfluenceHeatmapPoint struct {
	value *InfluenceHeatmapPoint
	isSet bool
}

func (v NullableInfluenceHeatmapPoint) Get() *InfluenceHeatmapPoint {
	return v.value
}

func (v *NullableInfluenceHeatmapPoint) Set(val *InfluenceHeatmapPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableInfluenceHeatmapPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableInfluenceHeatmapPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfluenceHeatmapPoint(val *InfluenceHeatmapPoint) *NullableInfluenceHeatmapPoint {
	return &NullableInfluenceHeatmapPoint{value: val, isSet: true}
}

func (v NullableInfluenceHeatmapPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfluenceHeatmapPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


