/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
)

// checks if the MemoryRepoLookupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryRepoLookupResponse{}

// MemoryRepoLookupResponse struct for MemoryRepoLookupResponse
type MemoryRepoLookupResponse struct {
	Repo NullableMemoryRepoSummaryResponse `json:"repo,omitempty"`
}

// NewMemoryRepoLookupResponse instantiates a new MemoryRepoLookupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryRepoLookupResponse() *MemoryRepoLookupResponse {
	this := MemoryRepoLookupResponse{}
	return &this
}

// NewMemoryRepoLookupResponseWithDefaults instantiates a new MemoryRepoLookupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryRepoLookupResponseWithDefaults() *MemoryRepoLookupResponse {
	this := MemoryRepoLookupResponse{}
	return &this
}

// GetRepo returns the Repo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryRepoLookupResponse) GetRepo() MemoryRepoSummaryResponse {
	if o == nil || IsNil(o.Repo.Get()) {
		var ret MemoryRepoSummaryResponse
		return ret
	}
	return *o.Repo.Get()
}

// GetRepoOk returns a tuple with the Repo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRepoLookupResponse) GetRepoOk() (*MemoryRepoSummaryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Repo.Get(), o.Repo.IsSet()
}

// HasRepo returns a boolean if a field has been set.
func (o *MemoryRepoLookupResponse) HasRepo() bool {
	if o != nil && o.Repo.IsSet() {
		return true
	}

	return false
}

// SetRepo gets a reference to the given NullableMemoryRepoSummaryResponse and assigns it to the Repo field.
func (o *MemoryRepoLookupResponse) SetRepo(v MemoryRepoSummaryResponse) {
	o.Repo.Set(&v)
}

// SetRepoNil sets the value for Repo to be an explicit nil
func (o *MemoryRepoLookupResponse) SetRepoNil() {
	o.Repo.Set(nil)
}

// UnsetRepo ensures that no value is present for Repo, not even an explicit nil
func (o *MemoryRepoLookupResponse) UnsetRepo() {
	o.Repo.Unset()
}

func (o MemoryRepoLookupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryRepoLookupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Repo.IsSet() {
		toSerialize["repo"] = o.Repo.Get()
	}
	return toSerialize, nil
}

type NullableMemoryRepoLookupResponse struct {
	value *MemoryRepoLookupResponse
	isSet bool
}

func (v NullableMemoryRepoLookupResponse) Get() *MemoryRepoLookupResponse {
	return v.value
}

func (v *NullableMemoryRepoLookupResponse) Set(val *MemoryRepoLookupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryRepoLookupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryRepoLookupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryRepoLookupResponse(val *MemoryRepoLookupResponse) *NullableMemoryRepoLookupResponse {
	return &NullableMemoryRepoLookupResponse{value: val, isSet: true}
}

func (v NullableMemoryRepoLookupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryRepoLookupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
