/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseFilesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseFilesResponse{}

// CodebaseFilesResponse Codebase file listing response.
type CodebaseFilesResponse struct {
	CodebaseId string `json:"codebase_id"`
	SnapshotId NullableString `json:"snapshot_id,omitempty"`
	SourceRef NullableString `json:"source_ref,omitempty"`
	SourceCommitSha NullableString `json:"source_commit_sha,omitempty"`
	SnapshotStatus NullableString `json:"snapshot_status,omitempty"`
	Items []CodebaseFileItemResponse `json:"items"`
}

type _CodebaseFilesResponse CodebaseFilesResponse

// NewCodebaseFilesResponse instantiates a new CodebaseFilesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseFilesResponse(codebaseId string, items []CodebaseFileItemResponse) *CodebaseFilesResponse {
	this := CodebaseFilesResponse{}
	this.CodebaseId = codebaseId
	this.Items = items
	return &this
}

// NewCodebaseFilesResponseWithDefaults instantiates a new CodebaseFilesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseFilesResponseWithDefaults() *CodebaseFilesResponse {
	this := CodebaseFilesResponse{}
	return &this
}

// GetCodebaseId returns the CodebaseId field value
func (o *CodebaseFilesResponse) GetCodebaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodebaseId
}

// GetCodebaseIdOk returns a tuple with the CodebaseId field value
// and a boolean to check if the value has been set.
func (o *CodebaseFilesResponse) GetCodebaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodebaseId, true
}

// SetCodebaseId sets field value
func (o *CodebaseFilesResponse) SetCodebaseId(v string) {
	o.CodebaseId = v
}

// GetSnapshotId returns the SnapshotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseFilesResponse) GetSnapshotId() string {
	if o == nil || IsNil(o.SnapshotId.Get()) {
		var ret string
		return ret
	}
	return *o.SnapshotId.Get()
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseFilesResponse) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotId.Get(), o.SnapshotId.IsSet()
}

// HasSnapshotId returns a boolean if a field has been set.
func (o *CodebaseFilesResponse) HasSnapshotId() bool {
	if o != nil && o.SnapshotId.IsSet() {
		return true
	}

	return false
}

// SetSnapshotId gets a reference to the given NullableString and assigns it to the SnapshotId field.
func (o *CodebaseFilesResponse) SetSnapshotId(v string) {
	o.SnapshotId.Set(&v)
}
// SetSnapshotIdNil sets the value for SnapshotId to be an explicit nil
func (o *CodebaseFilesResponse) SetSnapshotIdNil() {
	o.SnapshotId.Set(nil)
}

// UnsetSnapshotId ensures that no value is present for SnapshotId, not even an explicit nil
func (o *CodebaseFilesResponse) UnsetSnapshotId() {
	o.SnapshotId.Unset()
}

// GetSourceRef returns the SourceRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseFilesResponse) GetSourceRef() string {
	if o == nil || IsNil(o.SourceRef.Get()) {
		var ret string
		return ret
	}
	return *o.SourceRef.Get()
}

// GetSourceRefOk returns a tuple with the SourceRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseFilesResponse) GetSourceRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceRef.Get(), o.SourceRef.IsSet()
}

// HasSourceRef returns a boolean if a field has been set.
func (o *CodebaseFilesResponse) HasSourceRef() bool {
	if o != nil && o.SourceRef.IsSet() {
		return true
	}

	return false
}

// SetSourceRef gets a reference to the given NullableString and assigns it to the SourceRef field.
func (o *CodebaseFilesResponse) SetSourceRef(v string) {
	o.SourceRef.Set(&v)
}
// SetSourceRefNil sets the value for SourceRef to be an explicit nil
func (o *CodebaseFilesResponse) SetSourceRefNil() {
	o.SourceRef.Set(nil)
}

// UnsetSourceRef ensures that no value is present for SourceRef, not even an explicit nil
func (o *CodebaseFilesResponse) UnsetSourceRef() {
	o.SourceRef.Unset()
}

// GetSourceCommitSha returns the SourceCommitSha field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseFilesResponse) GetSourceCommitSha() string {
	if o == nil || IsNil(o.SourceCommitSha.Get()) {
		var ret string
		return ret
	}
	return *o.SourceCommitSha.Get()
}

// GetSourceCommitShaOk returns a tuple with the SourceCommitSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseFilesResponse) GetSourceCommitShaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceCommitSha.Get(), o.SourceCommitSha.IsSet()
}

// HasSourceCommitSha returns a boolean if a field has been set.
func (o *CodebaseFilesResponse) HasSourceCommitSha() bool {
	if o != nil && o.SourceCommitSha.IsSet() {
		return true
	}

	return false
}

// SetSourceCommitSha gets a reference to the given NullableString and assigns it to the SourceCommitSha field.
func (o *CodebaseFilesResponse) SetSourceCommitSha(v string) {
	o.SourceCommitSha.Set(&v)
}
// SetSourceCommitShaNil sets the value for SourceCommitSha to be an explicit nil
func (o *CodebaseFilesResponse) SetSourceCommitShaNil() {
	o.SourceCommitSha.Set(nil)
}

// UnsetSourceCommitSha ensures that no value is present for SourceCommitSha, not even an explicit nil
func (o *CodebaseFilesResponse) UnsetSourceCommitSha() {
	o.SourceCommitSha.Unset()
}

// GetSnapshotStatus returns the SnapshotStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseFilesResponse) GetSnapshotStatus() string {
	if o == nil || IsNil(o.SnapshotStatus.Get()) {
		var ret string
		return ret
	}
	return *o.SnapshotStatus.Get()
}

// GetSnapshotStatusOk returns a tuple with the SnapshotStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseFilesResponse) GetSnapshotStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotStatus.Get(), o.SnapshotStatus.IsSet()
}

// HasSnapshotStatus returns a boolean if a field has been set.
func (o *CodebaseFilesResponse) HasSnapshotStatus() bool {
	if o != nil && o.SnapshotStatus.IsSet() {
		return true
	}

	return false
}

// SetSnapshotStatus gets a reference to the given NullableString and assigns it to the SnapshotStatus field.
func (o *CodebaseFilesResponse) SetSnapshotStatus(v string) {
	o.SnapshotStatus.Set(&v)
}
// SetSnapshotStatusNil sets the value for SnapshotStatus to be an explicit nil
func (o *CodebaseFilesResponse) SetSnapshotStatusNil() {
	o.SnapshotStatus.Set(nil)
}

// UnsetSnapshotStatus ensures that no value is present for SnapshotStatus, not even an explicit nil
func (o *CodebaseFilesResponse) UnsetSnapshotStatus() {
	o.SnapshotStatus.Unset()
}

// GetItems returns the Items field value
func (o *CodebaseFilesResponse) GetItems() []CodebaseFileItemResponse {
	if o == nil {
		var ret []CodebaseFileItemResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CodebaseFilesResponse) GetItemsOk() ([]CodebaseFileItemResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CodebaseFilesResponse) SetItems(v []CodebaseFileItemResponse) {
	o.Items = v
}

func (o CodebaseFilesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseFilesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codebase_id"] = o.CodebaseId
	if o.SnapshotId.IsSet() {
		toSerialize["snapshot_id"] = o.SnapshotId.Get()
	}
	if o.SourceRef.IsSet() {
		toSerialize["source_ref"] = o.SourceRef.Get()
	}
	if o.SourceCommitSha.IsSet() {
		toSerialize["source_commit_sha"] = o.SourceCommitSha.Get()
	}
	if o.SnapshotStatus.IsSet() {
		toSerialize["snapshot_status"] = o.SnapshotStatus.Get()
	}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *CodebaseFilesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codebase_id",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseFilesResponse := _CodebaseFilesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseFilesResponse)

	if err != nil {
		return err
	}

	*o = CodebaseFilesResponse(varCodebaseFilesResponse)

	return err
}

type NullableCodebaseFilesResponse struct {
	value *CodebaseFilesResponse
	isSet bool
}

func (v NullableCodebaseFilesResponse) Get() *CodebaseFilesResponse {
	return v.value
}

func (v *NullableCodebaseFilesResponse) Set(val *CodebaseFilesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseFilesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseFilesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseFilesResponse(val *CodebaseFilesResponse) *NullableCodebaseFilesResponse {
	return &NullableCodebaseFilesResponse{value: val, isSet: true}
}

func (v NullableCodebaseFilesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseFilesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


