/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseCurateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseCurateResponse{}

// CodebaseCurateResponse Intent-driven curation response.
type CodebaseCurateResponse struct {
	CodebaseId string `json:"codebase_id"`
	SnapshotId NullableString `json:"snapshot_id,omitempty"`
	Intent string `json:"intent"`
	ScopeHint NullableString `json:"scope_hint,omitempty"`
	Clusters []CodebaseCurateClusterResponse `json:"clusters,omitempty"`
	SymbolCards []map[string]interface{} `json:"symbol_cards,omitempty"`
	Unclustered []map[string]interface{} `json:"unclustered,omitempty"`
	TotalCandidates *int32 `json:"total_candidates,omitempty"`
}

type _CodebaseCurateResponse CodebaseCurateResponse

// NewCodebaseCurateResponse instantiates a new CodebaseCurateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseCurateResponse(codebaseId string, intent string) *CodebaseCurateResponse {
	this := CodebaseCurateResponse{}
	this.CodebaseId = codebaseId
	this.Intent = intent
	var totalCandidates int32 = 0
	this.TotalCandidates = &totalCandidates
	return &this
}

// NewCodebaseCurateResponseWithDefaults instantiates a new CodebaseCurateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseCurateResponseWithDefaults() *CodebaseCurateResponse {
	this := CodebaseCurateResponse{}
	var totalCandidates int32 = 0
	this.TotalCandidates = &totalCandidates
	return &this
}

// GetCodebaseId returns the CodebaseId field value
func (o *CodebaseCurateResponse) GetCodebaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodebaseId
}

// GetCodebaseIdOk returns a tuple with the CodebaseId field value
// and a boolean to check if the value has been set.
func (o *CodebaseCurateResponse) GetCodebaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodebaseId, true
}

// SetCodebaseId sets field value
func (o *CodebaseCurateResponse) SetCodebaseId(v string) {
	o.CodebaseId = v
}

// GetSnapshotId returns the SnapshotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseCurateResponse) GetSnapshotId() string {
	if o == nil || IsNil(o.SnapshotId.Get()) {
		var ret string
		return ret
	}
	return *o.SnapshotId.Get()
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseCurateResponse) GetSnapshotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotId.Get(), o.SnapshotId.IsSet()
}

// HasSnapshotId returns a boolean if a field has been set.
func (o *CodebaseCurateResponse) HasSnapshotId() bool {
	if o != nil && o.SnapshotId.IsSet() {
		return true
	}

	return false
}

// SetSnapshotId gets a reference to the given NullableString and assigns it to the SnapshotId field.
func (o *CodebaseCurateResponse) SetSnapshotId(v string) {
	o.SnapshotId.Set(&v)
}
// SetSnapshotIdNil sets the value for SnapshotId to be an explicit nil
func (o *CodebaseCurateResponse) SetSnapshotIdNil() {
	o.SnapshotId.Set(nil)
}

// UnsetSnapshotId ensures that no value is present for SnapshotId, not even an explicit nil
func (o *CodebaseCurateResponse) UnsetSnapshotId() {
	o.SnapshotId.Unset()
}

// GetIntent returns the Intent field value
func (o *CodebaseCurateResponse) GetIntent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Intent
}

// GetIntentOk returns a tuple with the Intent field value
// and a boolean to check if the value has been set.
func (o *CodebaseCurateResponse) GetIntentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Intent, true
}

// SetIntent sets field value
func (o *CodebaseCurateResponse) SetIntent(v string) {
	o.Intent = v
}

// GetScopeHint returns the ScopeHint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CodebaseCurateResponse) GetScopeHint() string {
	if o == nil || IsNil(o.ScopeHint.Get()) {
		var ret string
		return ret
	}
	return *o.ScopeHint.Get()
}

// GetScopeHintOk returns a tuple with the ScopeHint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodebaseCurateResponse) GetScopeHintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScopeHint.Get(), o.ScopeHint.IsSet()
}

// HasScopeHint returns a boolean if a field has been set.
func (o *CodebaseCurateResponse) HasScopeHint() bool {
	if o != nil && o.ScopeHint.IsSet() {
		return true
	}

	return false
}

// SetScopeHint gets a reference to the given NullableString and assigns it to the ScopeHint field.
func (o *CodebaseCurateResponse) SetScopeHint(v string) {
	o.ScopeHint.Set(&v)
}
// SetScopeHintNil sets the value for ScopeHint to be an explicit nil
func (o *CodebaseCurateResponse) SetScopeHintNil() {
	o.ScopeHint.Set(nil)
}

// UnsetScopeHint ensures that no value is present for ScopeHint, not even an explicit nil
func (o *CodebaseCurateResponse) UnsetScopeHint() {
	o.ScopeHint.Unset()
}

// GetClusters returns the Clusters field value if set, zero value otherwise.
func (o *CodebaseCurateResponse) GetClusters() []CodebaseCurateClusterResponse {
	if o == nil || IsNil(o.Clusters) {
		var ret []CodebaseCurateClusterResponse
		return ret
	}
	return o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseCurateResponse) GetClustersOk() ([]CodebaseCurateClusterResponse, bool) {
	if o == nil || IsNil(o.Clusters) {
		return nil, false
	}
	return o.Clusters, true
}

// HasClusters returns a boolean if a field has been set.
func (o *CodebaseCurateResponse) HasClusters() bool {
	if o != nil && !IsNil(o.Clusters) {
		return true
	}

	return false
}

// SetClusters gets a reference to the given []CodebaseCurateClusterResponse and assigns it to the Clusters field.
func (o *CodebaseCurateResponse) SetClusters(v []CodebaseCurateClusterResponse) {
	o.Clusters = v
}

// GetSymbolCards returns the SymbolCards field value if set, zero value otherwise.
func (o *CodebaseCurateResponse) GetSymbolCards() []map[string]interface{} {
	if o == nil || IsNil(o.SymbolCards) {
		var ret []map[string]interface{}
		return ret
	}
	return o.SymbolCards
}

// GetSymbolCardsOk returns a tuple with the SymbolCards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseCurateResponse) GetSymbolCardsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.SymbolCards) {
		return nil, false
	}
	return o.SymbolCards, true
}

// HasSymbolCards returns a boolean if a field has been set.
func (o *CodebaseCurateResponse) HasSymbolCards() bool {
	if o != nil && !IsNil(o.SymbolCards) {
		return true
	}

	return false
}

// SetSymbolCards gets a reference to the given []map[string]interface{} and assigns it to the SymbolCards field.
func (o *CodebaseCurateResponse) SetSymbolCards(v []map[string]interface{}) {
	o.SymbolCards = v
}

// GetUnclustered returns the Unclustered field value if set, zero value otherwise.
func (o *CodebaseCurateResponse) GetUnclustered() []map[string]interface{} {
	if o == nil || IsNil(o.Unclustered) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Unclustered
}

// GetUnclusteredOk returns a tuple with the Unclustered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseCurateResponse) GetUnclusteredOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Unclustered) {
		return nil, false
	}
	return o.Unclustered, true
}

// HasUnclustered returns a boolean if a field has been set.
func (o *CodebaseCurateResponse) HasUnclustered() bool {
	if o != nil && !IsNil(o.Unclustered) {
		return true
	}

	return false
}

// SetUnclustered gets a reference to the given []map[string]interface{} and assigns it to the Unclustered field.
func (o *CodebaseCurateResponse) SetUnclustered(v []map[string]interface{}) {
	o.Unclustered = v
}

// GetTotalCandidates returns the TotalCandidates field value if set, zero value otherwise.
func (o *CodebaseCurateResponse) GetTotalCandidates() int32 {
	if o == nil || IsNil(o.TotalCandidates) {
		var ret int32
		return ret
	}
	return *o.TotalCandidates
}

// GetTotalCandidatesOk returns a tuple with the TotalCandidates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CodebaseCurateResponse) GetTotalCandidatesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCandidates) {
		return nil, false
	}
	return o.TotalCandidates, true
}

// HasTotalCandidates returns a boolean if a field has been set.
func (o *CodebaseCurateResponse) HasTotalCandidates() bool {
	if o != nil && !IsNil(o.TotalCandidates) {
		return true
	}

	return false
}

// SetTotalCandidates gets a reference to the given int32 and assigns it to the TotalCandidates field.
func (o *CodebaseCurateResponse) SetTotalCandidates(v int32) {
	o.TotalCandidates = &v
}

func (o CodebaseCurateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseCurateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codebase_id"] = o.CodebaseId
	if o.SnapshotId.IsSet() {
		toSerialize["snapshot_id"] = o.SnapshotId.Get()
	}
	toSerialize["intent"] = o.Intent
	if o.ScopeHint.IsSet() {
		toSerialize["scope_hint"] = o.ScopeHint.Get()
	}
	if !IsNil(o.Clusters) {
		toSerialize["clusters"] = o.Clusters
	}
	if !IsNil(o.SymbolCards) {
		toSerialize["symbol_cards"] = o.SymbolCards
	}
	if !IsNil(o.Unclustered) {
		toSerialize["unclustered"] = o.Unclustered
	}
	if !IsNil(o.TotalCandidates) {
		toSerialize["total_candidates"] = o.TotalCandidates
	}
	return toSerialize, nil
}

func (o *CodebaseCurateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codebase_id",
		"intent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseCurateResponse := _CodebaseCurateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseCurateResponse)

	if err != nil {
		return err
	}

	*o = CodebaseCurateResponse(varCodebaseCurateResponse)

	return err
}

type NullableCodebaseCurateResponse struct {
	value *CodebaseCurateResponse
	isSet bool
}

func (v NullableCodebaseCurateResponse) Get() *CodebaseCurateResponse {
	return v.value
}

func (v *NullableCodebaseCurateResponse) Set(val *CodebaseCurateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseCurateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseCurateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseCurateResponse(val *CodebaseCurateResponse) *NullableCodebaseCurateResponse {
	return &NullableCodebaseCurateResponse{value: val, isSet: true}
}

func (v NullableCodebaseCurateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseCurateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


