/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OperationProgressResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationProgressResponse{}

// OperationProgressResponse Typed progress payload for async operations when totals are known.
type OperationProgressResponse struct {
	Current int32          `json:"current"`
	Total   int32          `json:"total"`
	Unit    NullableString `json:"unit,omitempty"`
	Label   NullableString `json:"label,omitempty"`
	Failed  NullableInt32  `json:"failed,omitempty"`
}

type _OperationProgressResponse OperationProgressResponse

// NewOperationProgressResponse instantiates a new OperationProgressResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationProgressResponse(current int32, total int32) *OperationProgressResponse {
	this := OperationProgressResponse{}
	this.Current = current
	this.Total = total
	return &this
}

// NewOperationProgressResponseWithDefaults instantiates a new OperationProgressResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationProgressResponseWithDefaults() *OperationProgressResponse {
	this := OperationProgressResponse{}
	return &this
}

// GetCurrent returns the Current field value
func (o *OperationProgressResponse) GetCurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *OperationProgressResponse) GetCurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *OperationProgressResponse) SetCurrent(v int32) {
	o.Current = v
}

// GetTotal returns the Total field value
func (o *OperationProgressResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *OperationProgressResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *OperationProgressResponse) SetTotal(v int32) {
	o.Total = v
}

// GetUnit returns the Unit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperationProgressResponse) GetUnit() string {
	if o == nil || IsNil(o.Unit.Get()) {
		var ret string
		return ret
	}
	return *o.Unit.Get()
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperationProgressResponse) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unit.Get(), o.Unit.IsSet()
}

// HasUnit returns a boolean if a field has been set.
func (o *OperationProgressResponse) HasUnit() bool {
	if o != nil && o.Unit.IsSet() {
		return true
	}

	return false
}

// SetUnit gets a reference to the given NullableString and assigns it to the Unit field.
func (o *OperationProgressResponse) SetUnit(v string) {
	o.Unit.Set(&v)
}

// SetUnitNil sets the value for Unit to be an explicit nil
func (o *OperationProgressResponse) SetUnitNil() {
	o.Unit.Set(nil)
}

// UnsetUnit ensures that no value is present for Unit, not even an explicit nil
func (o *OperationProgressResponse) UnsetUnit() {
	o.Unit.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperationProgressResponse) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperationProgressResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *OperationProgressResponse) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *OperationProgressResponse) SetLabel(v string) {
	o.Label.Set(&v)
}

// SetLabelNil sets the value for Label to be an explicit nil
func (o *OperationProgressResponse) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *OperationProgressResponse) UnsetLabel() {
	o.Label.Unset()
}

// GetFailed returns the Failed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperationProgressResponse) GetFailed() int32 {
	if o == nil || IsNil(o.Failed.Get()) {
		var ret int32
		return ret
	}
	return *o.Failed.Get()
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperationProgressResponse) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Failed.Get(), o.Failed.IsSet()
}

// HasFailed returns a boolean if a field has been set.
func (o *OperationProgressResponse) HasFailed() bool {
	if o != nil && o.Failed.IsSet() {
		return true
	}

	return false
}

// SetFailed gets a reference to the given NullableInt32 and assigns it to the Failed field.
func (o *OperationProgressResponse) SetFailed(v int32) {
	o.Failed.Set(&v)
}

// SetFailedNil sets the value for Failed to be an explicit nil
func (o *OperationProgressResponse) SetFailedNil() {
	o.Failed.Set(nil)
}

// UnsetFailed ensures that no value is present for Failed, not even an explicit nil
func (o *OperationProgressResponse) UnsetFailed() {
	o.Failed.Unset()
}

func (o OperationProgressResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationProgressResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current
	toSerialize["total"] = o.Total
	if o.Unit.IsSet() {
		toSerialize["unit"] = o.Unit.Get()
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.Failed.IsSet() {
		toSerialize["failed"] = o.Failed.Get()
	}
	return toSerialize, nil
}

func (o *OperationProgressResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationProgressResponse := _OperationProgressResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationProgressResponse)

	if err != nil {
		return err
	}

	*o = OperationProgressResponse(varOperationProgressResponse)

	return err
}

type NullableOperationProgressResponse struct {
	value *OperationProgressResponse
	isSet bool
}

func (v NullableOperationProgressResponse) Get() *OperationProgressResponse {
	return v.value
}

func (v *NullableOperationProgressResponse) Set(val *OperationProgressResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationProgressResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationProgressResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationProgressResponse(val *OperationProgressResponse) *NullableOperationProgressResponse {
	return &NullableOperationProgressResponse{value: val, isSet: true}
}

func (v NullableOperationProgressResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationProgressResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
