/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseReviewDiagnosticResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseReviewDiagnosticResponse{}

// CodebaseReviewDiagnosticResponse A deterministic review diagnostic bucket.
type CodebaseReviewDiagnosticResponse struct {
	Reason string `json:"reason"`
	Count int32 `json:"count"`
}

type _CodebaseReviewDiagnosticResponse CodebaseReviewDiagnosticResponse

// NewCodebaseReviewDiagnosticResponse instantiates a new CodebaseReviewDiagnosticResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseReviewDiagnosticResponse(reason string, count int32) *CodebaseReviewDiagnosticResponse {
	this := CodebaseReviewDiagnosticResponse{}
	this.Reason = reason
	this.Count = count
	return &this
}

// NewCodebaseReviewDiagnosticResponseWithDefaults instantiates a new CodebaseReviewDiagnosticResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseReviewDiagnosticResponseWithDefaults() *CodebaseReviewDiagnosticResponse {
	this := CodebaseReviewDiagnosticResponse{}
	return &this
}

// GetReason returns the Reason field value
func (o *CodebaseReviewDiagnosticResponse) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CodebaseReviewDiagnosticResponse) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CodebaseReviewDiagnosticResponse) SetReason(v string) {
	o.Reason = v
}

// GetCount returns the Count field value
func (o *CodebaseReviewDiagnosticResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *CodebaseReviewDiagnosticResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *CodebaseReviewDiagnosticResponse) SetCount(v int32) {
	o.Count = v
}

func (o CodebaseReviewDiagnosticResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseReviewDiagnosticResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *CodebaseReviewDiagnosticResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseReviewDiagnosticResponse := _CodebaseReviewDiagnosticResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseReviewDiagnosticResponse)

	if err != nil {
		return err
	}

	*o = CodebaseReviewDiagnosticResponse(varCodebaseReviewDiagnosticResponse)

	return err
}

type NullableCodebaseReviewDiagnosticResponse struct {
	value *CodebaseReviewDiagnosticResponse
	isSet bool
}

func (v NullableCodebaseReviewDiagnosticResponse) Get() *CodebaseReviewDiagnosticResponse {
	return v.value
}

func (v *NullableCodebaseReviewDiagnosticResponse) Set(val *CodebaseReviewDiagnosticResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseReviewDiagnosticResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseReviewDiagnosticResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseReviewDiagnosticResponse(val *CodebaseReviewDiagnosticResponse) *NullableCodebaseReviewDiagnosticResponse {
	return &NullableCodebaseReviewDiagnosticResponse{value: val, isSet: true}
}

func (v NullableCodebaseReviewDiagnosticResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseReviewDiagnosticResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


