/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyResponse{}

// ApiKeyResponse struct for ApiKeyResponse
type ApiKeyResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
	SchemaName string `json:"schema_name"`
	AllowedBankIds []string `json:"allowed_bank_ids"`
	CreatedAt string `json:"created_at"`
	ExpiresAt NullableString `json:"expires_at"`
	RevokedAt NullableString `json:"revoked_at"`
	RawKey NullableString `json:"raw_key,omitempty"`
}

type _ApiKeyResponse ApiKeyResponse

// NewApiKeyResponse instantiates a new ApiKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyResponse(id string, name string, role string, schemaName string, allowedBankIds []string, createdAt string, expiresAt NullableString, revokedAt NullableString) *ApiKeyResponse {
	this := ApiKeyResponse{}
	this.Id = id
	this.Name = name
	this.Role = role
	this.SchemaName = schemaName
	this.AllowedBankIds = allowedBankIds
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	this.RevokedAt = revokedAt
	return &this
}

// NewApiKeyResponseWithDefaults instantiates a new ApiKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyResponseWithDefaults() *ApiKeyResponse {
	this := ApiKeyResponse{}
	return &this
}

// GetId returns the Id field value
func (o *ApiKeyResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiKeyResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiKeyResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ApiKeyResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiKeyResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiKeyResponse) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *ApiKeyResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ApiKeyResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ApiKeyResponse) SetRole(v string) {
	o.Role = v
}

// GetSchemaName returns the SchemaName field value
func (o *ApiKeyResponse) GetSchemaName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaName
}

// GetSchemaNameOk returns a tuple with the SchemaName field value
// and a boolean to check if the value has been set.
func (o *ApiKeyResponse) GetSchemaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaName, true
}

// SetSchemaName sets field value
func (o *ApiKeyResponse) SetSchemaName(v string) {
	o.SchemaName = v
}

// GetAllowedBankIds returns the AllowedBankIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ApiKeyResponse) GetAllowedBankIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedBankIds
}

// GetAllowedBankIdsOk returns a tuple with the AllowedBankIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyResponse) GetAllowedBankIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedBankIds) {
		return nil, false
	}
	return o.AllowedBankIds, true
}

// SetAllowedBankIds sets field value
func (o *ApiKeyResponse) SetAllowedBankIds(v []string) {
	o.AllowedBankIds = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApiKeyResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiKeyResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApiKeyResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiKeyResponse) GetExpiresAt() string {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// SetExpiresAt sets field value
func (o *ApiKeyResponse) SetExpiresAt(v string) {
	o.ExpiresAt.Set(&v)
}

// GetRevokedAt returns the RevokedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApiKeyResponse) GetRevokedAt() string {
	if o == nil || o.RevokedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyResponse) GetRevokedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// SetRevokedAt sets field value
func (o *ApiKeyResponse) SetRevokedAt(v string) {
	o.RevokedAt.Set(&v)
}

// GetRawKey returns the RawKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKeyResponse) GetRawKey() string {
	if o == nil || IsNil(o.RawKey.Get()) {
		var ret string
		return ret
	}
	return *o.RawKey.Get()
}

// GetRawKeyOk returns a tuple with the RawKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKeyResponse) GetRawKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawKey.Get(), o.RawKey.IsSet()
}

// HasRawKey returns a boolean if a field has been set.
func (o *ApiKeyResponse) HasRawKey() bool {
	if o != nil && o.RawKey.IsSet() {
		return true
	}

	return false
}

// SetRawKey gets a reference to the given NullableString and assigns it to the RawKey field.
func (o *ApiKeyResponse) SetRawKey(v string) {
	o.RawKey.Set(&v)
}
// SetRawKeyNil sets the value for RawKey to be an explicit nil
func (o *ApiKeyResponse) SetRawKeyNil() {
	o.RawKey.Set(nil)
}

// UnsetRawKey ensures that no value is present for RawKey, not even an explicit nil
func (o *ApiKeyResponse) UnsetRawKey() {
	o.RawKey.Unset()
}

func (o ApiKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["schema_name"] = o.SchemaName
	if o.AllowedBankIds != nil {
		toSerialize["allowed_bank_ids"] = o.AllowedBankIds
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["expires_at"] = o.ExpiresAt.Get()
	toSerialize["revoked_at"] = o.RevokedAt.Get()
	if o.RawKey.IsSet() {
		toSerialize["raw_key"] = o.RawKey.Get()
	}
	return toSerialize, nil
}

func (o *ApiKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"role",
		"schema_name",
		"allowed_bank_ids",
		"created_at",
		"expires_at",
		"revoked_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiKeyResponse := _ApiKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiKeyResponse)

	if err != nil {
		return err
	}

	*o = ApiKeyResponse(varApiKeyResponse)

	return err
}

type NullableApiKeyResponse struct {
	value *ApiKeyResponse
	isSet bool
}

func (v NullableApiKeyResponse) Get() *ApiKeyResponse {
	return v.value
}

func (v *NullableApiKeyResponse) Set(val *ApiKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyResponse(val *ApiKeyResponse) *NullableApiKeyResponse {
	return &NullableApiKeyResponse{value: val, isSet: true}
}

func (v NullableApiKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


