/*
Atulya HTTP API

HTTP API for Atulya

API version: 0.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package atulya

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodebaseImpactSeedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodebaseImpactSeedResponse{}

// CodebaseImpactSeedResponse Seed used to start deterministic impact analysis.
type CodebaseImpactSeedResponse struct {
	Type string `json:"type"`
	Value string `json:"value"`
}

type _CodebaseImpactSeedResponse CodebaseImpactSeedResponse

// NewCodebaseImpactSeedResponse instantiates a new CodebaseImpactSeedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodebaseImpactSeedResponse(type_ string, value string) *CodebaseImpactSeedResponse {
	this := CodebaseImpactSeedResponse{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewCodebaseImpactSeedResponseWithDefaults instantiates a new CodebaseImpactSeedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodebaseImpactSeedResponseWithDefaults() *CodebaseImpactSeedResponse {
	this := CodebaseImpactSeedResponse{}
	return &this
}

// GetType returns the Type field value
func (o *CodebaseImpactSeedResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CodebaseImpactSeedResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CodebaseImpactSeedResponse) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *CodebaseImpactSeedResponse) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CodebaseImpactSeedResponse) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CodebaseImpactSeedResponse) SetValue(v string) {
	o.Value = v
}

func (o CodebaseImpactSeedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodebaseImpactSeedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *CodebaseImpactSeedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodebaseImpactSeedResponse := _CodebaseImpactSeedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodebaseImpactSeedResponse)

	if err != nil {
		return err
	}

	*o = CodebaseImpactSeedResponse(varCodebaseImpactSeedResponse)

	return err
}

type NullableCodebaseImpactSeedResponse struct {
	value *CodebaseImpactSeedResponse
	isSet bool
}

func (v NullableCodebaseImpactSeedResponse) Get() *CodebaseImpactSeedResponse {
	return v.value
}

func (v *NullableCodebaseImpactSeedResponse) Set(val *CodebaseImpactSeedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodebaseImpactSeedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodebaseImpactSeedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodebaseImpactSeedResponse(val *CodebaseImpactSeedResponse) *NullableCodebaseImpactSeedResponse {
	return &NullableCodebaseImpactSeedResponse{value: val, isSet: true}
}

func (v NullableCodebaseImpactSeedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodebaseImpactSeedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


