# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from atulya_client_api.models.anomaly_correction_response import AnomalyCorrectionResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AnomalyEventResponse(BaseModel):
    """
    AnomalyEventResponse
    """ # noqa: E501
    id: StrictStr
    bank_id: StrictStr
    anomaly_type: StrictStr
    severity: Union[StrictFloat, StrictInt]
    status: StrictStr
    unit_ids: Optional[List[StrictStr]] = None
    entity_ids: Optional[List[StrictStr]] = None
    description: StrictStr
    metadata: Optional[Dict[str, Any]] = None
    detected_at: Optional[StrictStr] = None
    resolved_at: Optional[StrictStr] = None
    resolved_by: Optional[StrictStr] = None
    corrections: Optional[List[AnomalyCorrectionResponse]] = None
    __properties: ClassVar[List[str]] = ["id", "bank_id", "anomaly_type", "severity", "status", "unit_ids", "entity_ids", "description", "metadata", "detected_at", "resolved_at", "resolved_by", "corrections"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['open', 'acknowledged', 'resolved', 'suppressed']):
            raise ValueError("must be one of enum values ('open', 'acknowledged', 'resolved', 'suppressed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnomalyEventResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in corrections (list)
        _items = []
        if self.corrections:
            for _item_corrections in self.corrections:
                if _item_corrections:
                    _items.append(_item_corrections.to_dict())
            _dict['corrections'] = _items
        # set to None if detected_at (nullable) is None
        # and model_fields_set contains the field
        if self.detected_at is None and "detected_at" in self.model_fields_set:
            _dict['detected_at'] = None

        # set to None if resolved_at (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_at is None and "resolved_at" in self.model_fields_set:
            _dict['resolved_at'] = None

        # set to None if resolved_by (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_by is None and "resolved_by" in self.model_fields_set:
            _dict['resolved_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnomalyEventResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "bank_id": obj.get("bank_id"),
            "anomaly_type": obj.get("anomaly_type"),
            "severity": obj.get("severity"),
            "status": obj.get("status"),
            "unit_ids": obj.get("unit_ids"),
            "entity_ids": obj.get("entity_ids"),
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "detected_at": obj.get("detected_at"),
            "resolved_at": obj.get("resolved_at"),
            "resolved_by": obj.get("resolved_by"),
            "corrections": [AnomalyCorrectionResponse.from_dict(_item) for _item in obj["corrections"]] if obj.get("corrections") is not None else None
        })
        return _obj


