# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrainLearnRequest(BaseModel):
    """
    BrainLearnRequest
    """ # noqa: E501
    remote_endpoint: StrictStr = Field(description="URL of the remote Atulya API (e.g. http://host:8888)")
    remote_bank_id: StrictStr = Field(description="Bank ID on the remote instance to learn from")
    remote_api_key: Optional[StrictStr] = Field(default=None, description="Optional API key for the remote instance")
    learning_type: Optional[StrictStr] = None
    mode: Optional[StrictStr] = None
    horizon_hours: Optional[Annotated[int, Field(le=168, strict=True, ge=1)]] = None
    __properties: ClassVar[List[str]] = ["remote_endpoint", "remote_bank_id", "remote_api_key", "learning_type", "mode", "horizon_hours"]

    @field_validator('learning_type')
    def learning_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'distilled', 'structured', 'raw_mirror']):
            raise ValueError("must be one of enum values ('auto', 'distilled', 'structured', 'raw_mirror')")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['incremental', 'full_copy']):
            raise ValueError("must be one of enum values ('incremental', 'full_copy')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrainLearnRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrainLearnRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "remote_endpoint": obj.get("remote_endpoint"),
            "remote_bank_id": obj.get("remote_bank_id"),
            "remote_api_key": obj.get("remote_api_key"),
            "learning_type": obj.get("learning_type"),
            "mode": obj.get("mode"),
            "horizon_hours": obj.get("horizon_hours")
        })
        return _obj


