# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from atulya_client_api.models.codebase_chunk_related_item_response import CodebaseChunkRelatedItemResponse
from atulya_client_api.models.codebase_impact_edge_response import CodebaseImpactEdgeResponse
from atulya_client_api.models.codebase_symbol_match_response import CodebaseSymbolMatchResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CodebaseChunkDetailResponse(BaseModel):
    """
    Detailed chunk review payload.
    """ # noqa: E501
    id: StrictStr
    chunk_key: StrictStr
    path: StrictStr
    language: Optional[StrictStr] = None
    kind: StrictStr
    label: StrictStr
    preview_text: StrictStr
    start_line: StrictInt
    end_line: StrictInt
    container: Optional[StrictStr] = None
    parent_symbol: Optional[StrictStr] = None
    parent_fq_name: Optional[StrictStr] = None
    parse_confidence: Optional[Union[StrictFloat, StrictInt]] = None
    cluster_id: Optional[StrictStr] = None
    cluster_label: Optional[StrictStr] = None
    route_target: StrictStr
    route_source: Optional[StrictStr] = None
    change_kind: StrictStr
    related_count: Optional[StrictInt] = None
    document_id: Optional[StrictStr] = None
    snapshot_id: StrictStr
    content_text: StrictStr
    related_chunks: Optional[List[CodebaseChunkRelatedItemResponse]] = None
    symbols: Optional[List[CodebaseSymbolMatchResponse]] = None
    impact_edges: Optional[List[CodebaseImpactEdgeResponse]] = None
    cluster_members: Optional[List[CodebaseChunkRelatedItemResponse]] = None
    __properties: ClassVar[List[str]] = ["id", "chunk_key", "path", "language", "kind", "label", "preview_text", "start_line", "end_line", "container", "parent_symbol", "parent_fq_name", "parse_confidence", "cluster_id", "cluster_label", "route_target", "route_source", "change_kind", "related_count", "document_id", "snapshot_id", "content_text", "related_chunks", "symbols", "impact_edges", "cluster_members"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodebaseChunkDetailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in related_chunks (list)
        _items = []
        if self.related_chunks:
            for _item_related_chunks in self.related_chunks:
                if _item_related_chunks:
                    _items.append(_item_related_chunks.to_dict())
            _dict['related_chunks'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in symbols (list)
        _items = []
        if self.symbols:
            for _item_symbols in self.symbols:
                if _item_symbols:
                    _items.append(_item_symbols.to_dict())
            _dict['symbols'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in impact_edges (list)
        _items = []
        if self.impact_edges:
            for _item_impact_edges in self.impact_edges:
                if _item_impact_edges:
                    _items.append(_item_impact_edges.to_dict())
            _dict['impact_edges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cluster_members (list)
        _items = []
        if self.cluster_members:
            for _item_cluster_members in self.cluster_members:
                if _item_cluster_members:
                    _items.append(_item_cluster_members.to_dict())
            _dict['cluster_members'] = _items
        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if container (nullable) is None
        # and model_fields_set contains the field
        if self.container is None and "container" in self.model_fields_set:
            _dict['container'] = None

        # set to None if parent_symbol (nullable) is None
        # and model_fields_set contains the field
        if self.parent_symbol is None and "parent_symbol" in self.model_fields_set:
            _dict['parent_symbol'] = None

        # set to None if parent_fq_name (nullable) is None
        # and model_fields_set contains the field
        if self.parent_fq_name is None and "parent_fq_name" in self.model_fields_set:
            _dict['parent_fq_name'] = None

        # set to None if cluster_id (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_id is None and "cluster_id" in self.model_fields_set:
            _dict['cluster_id'] = None

        # set to None if cluster_label (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_label is None and "cluster_label" in self.model_fields_set:
            _dict['cluster_label'] = None

        # set to None if route_source (nullable) is None
        # and model_fields_set contains the field
        if self.route_source is None and "route_source" in self.model_fields_set:
            _dict['route_source'] = None

        # set to None if document_id (nullable) is None
        # and model_fields_set contains the field
        if self.document_id is None and "document_id" in self.model_fields_set:
            _dict['document_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodebaseChunkDetailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "chunk_key": obj.get("chunk_key"),
            "path": obj.get("path"),
            "language": obj.get("language"),
            "kind": obj.get("kind"),
            "label": obj.get("label"),
            "preview_text": obj.get("preview_text"),
            "start_line": obj.get("start_line"),
            "end_line": obj.get("end_line"),
            "container": obj.get("container"),
            "parent_symbol": obj.get("parent_symbol"),
            "parent_fq_name": obj.get("parent_fq_name"),
            "parse_confidence": obj.get("parse_confidence"),
            "cluster_id": obj.get("cluster_id"),
            "cluster_label": obj.get("cluster_label"),
            "route_target": obj.get("route_target"),
            "route_source": obj.get("route_source"),
            "change_kind": obj.get("change_kind"),
            "related_count": obj.get("related_count"),
            "document_id": obj.get("document_id"),
            "snapshot_id": obj.get("snapshot_id"),
            "content_text": obj.get("content_text"),
            "related_chunks": [CodebaseChunkRelatedItemResponse.from_dict(_item) for _item in obj["related_chunks"]] if obj.get("related_chunks") is not None else None,
            "symbols": [CodebaseSymbolMatchResponse.from_dict(_item) for _item in obj["symbols"]] if obj.get("symbols") is not None else None,
            "impact_edges": [CodebaseImpactEdgeResponse.from_dict(_item) for _item in obj["impact_edges"]] if obj.get("impact_edges") is not None else None,
            "cluster_members": [CodebaseChunkRelatedItemResponse.from_dict(_item) for _item in obj["cluster_members"]] if obj.get("cluster_members") is not None else None
        })
        return _obj


