# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CodebaseTriageSettings(BaseModel):
    """
    Per-codebase triage thresholds and provider toggles.
    """ # noqa: E501
    score_threshold_high: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = 0.62
    centrality_threshold: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = 0.35
    safety_threshold: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = 0.25
    embedding_provider: Optional[StrictStr] = 'jina_local'
    enable_safety_scan: Optional[StrictBool] = True
    enable_semgrep: Optional[StrictBool] = False
    semgrep_rulepack: Optional[StrictStr] = None
    scip_index_path: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["score_threshold_high", "centrality_threshold", "safety_threshold", "embedding_provider", "enable_safety_scan", "enable_semgrep", "semgrep_rulepack", "scip_index_path"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodebaseTriageSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if semgrep_rulepack (nullable) is None
        # and model_fields_set contains the field
        if self.semgrep_rulepack is None and "semgrep_rulepack" in self.model_fields_set:
            _dict['semgrep_rulepack'] = None

        # set to None if scip_index_path (nullable) is None
        # and model_fields_set contains the field
        if self.scip_index_path is None and "scip_index_path" in self.model_fields_set:
            _dict['scip_index_path'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodebaseTriageSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "score_threshold_high": obj.get("score_threshold_high") if obj.get("score_threshold_high") is not None else 0.62,
            "centrality_threshold": obj.get("centrality_threshold") if obj.get("centrality_threshold") is not None else 0.35,
            "safety_threshold": obj.get("safety_threshold") if obj.get("safety_threshold") is not None else 0.25,
            "embedding_provider": obj.get("embedding_provider") if obj.get("embedding_provider") is not None else 'jina_local',
            "enable_safety_scan": obj.get("enable_safety_scan") if obj.get("enable_safety_scan") is not None else True,
            "enable_semgrep": obj.get("enable_semgrep") if obj.get("enable_semgrep") is not None else False,
            "semgrep_rulepack": obj.get("semgrep_rulepack"),
            "scip_index_path": obj.get("scip_index_path")
        })
        return _obj


