# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CodebaseCurateRequest(BaseModel):
    """
    Intent-driven curation request body.
    """ # noqa: E501
    intent: StrictStr
    scope_hint: Optional[StrictStr] = None
    snapshot_id: Optional[StrictStr] = None
    top_k_clusters: Optional[Annotated[int, Field(le=50, strict=True, ge=1)]] = None
    top_k_symbols: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None
    include_dismissed: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["intent", "scope_hint", "snapshot_id", "top_k_clusters", "top_k_symbols", "include_dismissed"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodebaseCurateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if scope_hint (nullable) is None
        # and model_fields_set contains the field
        if self.scope_hint is None and "scope_hint" in self.model_fields_set:
            _dict['scope_hint'] = None

        # set to None if snapshot_id (nullable) is None
        # and model_fields_set contains the field
        if self.snapshot_id is None and "snapshot_id" in self.model_fields_set:
            _dict['snapshot_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodebaseCurateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "intent": obj.get("intent"),
            "scope_hint": obj.get("scope_hint"),
            "snapshot_id": obj.get("snapshot_id"),
            "top_k_clusters": obj.get("top_k_clusters"),
            "top_k_symbols": obj.get("top_k_symbols"),
            "include_dismissed": obj.get("include_dismissed")
        })
        return _obj


