# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from atulya_client_api.models.codebase_review_counts_response import CodebaseReviewCountsResponse
from typing import Optional, Set
from typing_extensions import Self

class CodebaseSnapshotStatsResponse(BaseModel):
    """
    Snapshot-level deterministic indexing stats.
    """ # noqa: E501
    total_files: Optional[StrictInt] = 0
    indexed_files: Optional[StrictInt] = 0
    retained_files: Optional[StrictInt] = 0
    manifest_only_files: Optional[StrictInt] = 0
    excluded_files: Optional[StrictInt] = 0
    symbol_count: Optional[StrictInt] = 0
    edge_count: Optional[StrictInt] = 0
    added_files: Optional[StrictInt] = 0
    changed_files: Optional[StrictInt] = 0
    unchanged_files: Optional[StrictInt] = 0
    deleted_files: Optional[StrictInt] = 0
    chunk_count: Optional[StrictInt] = 0
    cluster_count: Optional[StrictInt] = 0
    related_chunk_count: Optional[StrictInt] = 0
    parse_coverage: Optional[Union[StrictFloat, StrictInt]] = 0.0
    review_counts: Optional[CodebaseReviewCountsResponse] = None
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["total_files", "indexed_files", "retained_files", "manifest_only_files", "excluded_files", "symbol_count", "edge_count", "added_files", "changed_files", "unchanged_files", "deleted_files", "chunk_count", "cluster_count", "related_chunk_count", "parse_coverage", "review_counts", "error"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodebaseSnapshotStatsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of review_counts
        if self.review_counts:
            _dict['review_counts'] = self.review_counts.to_dict()
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodebaseSnapshotStatsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_files": obj.get("total_files") if obj.get("total_files") is not None else 0,
            "indexed_files": obj.get("indexed_files") if obj.get("indexed_files") is not None else 0,
            "retained_files": obj.get("retained_files") if obj.get("retained_files") is not None else 0,
            "manifest_only_files": obj.get("manifest_only_files") if obj.get("manifest_only_files") is not None else 0,
            "excluded_files": obj.get("excluded_files") if obj.get("excluded_files") is not None else 0,
            "symbol_count": obj.get("symbol_count") if obj.get("symbol_count") is not None else 0,
            "edge_count": obj.get("edge_count") if obj.get("edge_count") is not None else 0,
            "added_files": obj.get("added_files") if obj.get("added_files") is not None else 0,
            "changed_files": obj.get("changed_files") if obj.get("changed_files") is not None else 0,
            "unchanged_files": obj.get("unchanged_files") if obj.get("unchanged_files") is not None else 0,
            "deleted_files": obj.get("deleted_files") if obj.get("deleted_files") is not None else 0,
            "chunk_count": obj.get("chunk_count") if obj.get("chunk_count") is not None else 0,
            "cluster_count": obj.get("cluster_count") if obj.get("cluster_count") is not None else 0,
            "related_chunk_count": obj.get("related_chunk_count") if obj.get("related_chunk_count") is not None else 0,
            "parse_coverage": obj.get("parse_coverage") if obj.get("parse_coverage") is not None else 0.0,
            "review_counts": CodebaseReviewCountsResponse.from_dict(obj["review_counts"]) if obj.get("review_counts") is not None else None,
            "error": obj.get("error")
        })
        return _obj


