# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CodebaseApproveResponse(BaseModel):
    """
    Queued codebase approval response.
    """ # noqa: E501
    codebase_id: StrictStr
    snapshot_id: StrictStr
    operation_id: StrictStr
    status: StrictStr
    memory_ingest_mode: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["codebase_id", "snapshot_id", "operation_id", "status", "memory_ingest_mode"]

    @field_validator('memory_ingest_mode')
    def memory_ingest_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['direct', 'retain']):
            raise ValueError("must be one of enum values ('direct', 'retain')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodebaseApproveResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodebaseApproveResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "codebase_id": obj.get("codebase_id"),
            "snapshot_id": obj.get("snapshot_id"),
            "operation_id": obj.get("operation_id"),
            "status": obj.get("status"),
            "memory_ingest_mode": obj.get("memory_ingest_mode")
        })
        return _obj


