# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class DreamStatsResponse(BaseModel):
    """
    DreamStatsResponse
    """ # noqa: E501
    bank_id: StrictStr
    total_runs: StrictInt
    last_run_at: Optional[StrictStr]
    avg_quality: Union[StrictFloat, StrictInt]
    avg_tokens: Union[StrictFloat, StrictInt]
    avg_output_tokens: Union[StrictFloat, StrictInt]
    distillation_pass_rate: Union[StrictFloat, StrictInt]
    distilled_count: StrictInt
    validation_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    avg_novelty: Optional[Union[StrictFloat, StrictInt]] = 0.0
    failed_run_count: Optional[StrictInt] = 0
    duplicate_suppression_count: Optional[StrictInt] = 0
    prediction_confirmation_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    unresolved_prediction_backlog: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["bank_id", "total_runs", "last_run_at", "avg_quality", "avg_tokens", "avg_output_tokens", "distillation_pass_rate", "distilled_count", "validation_rate", "avg_novelty", "failed_run_count", "duplicate_suppression_count", "prediction_confirmation_rate", "unresolved_prediction_backlog"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DreamStatsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_run_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_run_at is None and "last_run_at" in self.model_fields_set:
            _dict['last_run_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DreamStatsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bank_id": obj.get("bank_id"),
            "total_runs": obj.get("total_runs"),
            "last_run_at": obj.get("last_run_at"),
            "avg_quality": obj.get("avg_quality"),
            "avg_tokens": obj.get("avg_tokens"),
            "avg_output_tokens": obj.get("avg_output_tokens"),
            "distillation_pass_rate": obj.get("distillation_pass_rate"),
            "distilled_count": obj.get("distilled_count"),
            "validation_rate": obj.get("validation_rate") if obj.get("validation_rate") is not None else 0.0,
            "avg_novelty": obj.get("avg_novelty") if obj.get("avg_novelty") is not None else 0.0,
            "failed_run_count": obj.get("failed_run_count") if obj.get("failed_run_count") is not None else 0,
            "duplicate_suppression_count": obj.get("duplicate_suppression_count") if obj.get("duplicate_suppression_count") is not None else 0,
            "prediction_confirmation_rate": obj.get("prediction_confirmation_rate") if obj.get("prediction_confirmation_rate") is not None else 0.0,
            "unresolved_prediction_backlog": obj.get("unresolved_prediction_backlog") if obj.get("unresolved_prediction_backlog") is not None else 0
        })
        return _obj


