# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntityIntelligenceResponse(BaseModel):
    """
    Latest bank-level entity intelligence snapshot.
    """ # noqa: E501
    bank_id: StrictStr
    computed_at: Optional[StrictStr] = None
    entity_count: StrictInt
    source_entity_count: StrictInt
    entity_snapshot_hash: Optional[StrictStr] = ''
    content: StrictStr
    structured_content: Optional[Dict[str, Any]] = None
    entity_context: Optional[Dict[str, Any]] = None
    delta_metadata: Optional[Dict[str, Any]] = None
    llm_model: Optional[StrictStr] = ''
    prompt_version: Optional[StrictStr] = ''
    __properties: ClassVar[List[str]] = ["bank_id", "computed_at", "entity_count", "source_entity_count", "entity_snapshot_hash", "content", "structured_content", "entity_context", "delta_metadata", "llm_model", "prompt_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityIntelligenceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if computed_at (nullable) is None
        # and model_fields_set contains the field
        if self.computed_at is None and "computed_at" in self.model_fields_set:
            _dict['computed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityIntelligenceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bank_id": obj.get("bank_id"),
            "computed_at": obj.get("computed_at"),
            "entity_count": obj.get("entity_count"),
            "source_entity_count": obj.get("source_entity_count"),
            "entity_snapshot_hash": obj.get("entity_snapshot_hash") if obj.get("entity_snapshot_hash") is not None else '',
            "content": obj.get("content"),
            "structured_content": obj.get("structured_content"),
            "entity_context": obj.get("entity_context"),
            "delta_metadata": obj.get("delta_metadata"),
            "llm_model": obj.get("llm_model") if obj.get("llm_model") is not None else '',
            "prompt_version": obj.get("prompt_version") if obj.get("prompt_version") is not None else ''
        })
        return _obj


