# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from atulya_client_api.models.graph_change_event_response import GraphChangeEventResponse
from atulya_client_api.models.graph_relation_edge_response import GraphRelationEdgeResponse
from atulya_client_api.models.graph_state_node_response import GraphStateNodeResponse
from typing import Optional, Set
from typing_extensions import Self

class GraphIntelligenceResponse(BaseModel):
    """
    GraphIntelligenceResponse
    """ # noqa: E501
    nodes: List[GraphStateNodeResponse]
    edges: List[GraphRelationEdgeResponse]
    change_events: List[GraphChangeEventResponse]
    total_nodes: StrictInt
    generated_at: StrictStr
    cached: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["nodes", "edges", "change_events", "total_nodes", "generated_at", "cached"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphIntelligenceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                if _item_nodes:
                    _items.append(_item_nodes.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item_edges in self.edges:
                if _item_edges:
                    _items.append(_item_edges.to_dict())
            _dict['edges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in change_events (list)
        _items = []
        if self.change_events:
            for _item_change_events in self.change_events:
                if _item_change_events:
                    _items.append(_item_change_events.to_dict())
            _dict['change_events'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphIntelligenceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodes": [GraphStateNodeResponse.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "edges": [GraphRelationEdgeResponse.from_dict(_item) for _item in obj["edges"]] if obj.get("edges") is not None else None,
            "change_events": [GraphChangeEventResponse.from_dict(_item) for _item in obj["change_events"]] if obj.get("change_events") is not None else None,
            "total_nodes": obj.get("total_nodes"),
            "generated_at": obj.get("generated_at"),
            "cached": obj.get("cached") if obj.get("cached") is not None else False
        })
        return _obj


