# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GraphNeighborhoodNodeResponse(BaseModel):
    """
    GraphNeighborhoodNodeResponse
    """ # noqa: E501
    id: StrictStr
    node_type: StrictStr
    title: StrictStr
    subtitle: Optional[StrictStr] = None
    preview: Optional[StrictStr] = None
    status_label: Optional[StrictStr] = None
    status_tone: Optional[StrictStr] = None
    confidence: Optional[Union[StrictFloat, StrictInt]] = None
    evidence_count: Optional[StrictInt] = None
    kind_label: Optional[StrictStr] = None
    meta: Optional[StrictStr] = None
    timestamp_label: Optional[StrictStr] = None
    reason: Optional[StrictStr] = None
    accent_color: Optional[StrictStr] = None
    display_priority: Optional[Union[StrictFloat, StrictInt]] = None
    node_density_hint: Optional[Union[StrictFloat, StrictInt]] = None
    cluster_membership: Optional[StrictStr] = None
    render_mode_hint: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "node_type", "title", "subtitle", "preview", "status_label", "status_tone", "confidence", "evidence_count", "kind_label", "meta", "timestamp_label", "reason", "accent_color", "display_priority", "node_density_hint", "cluster_membership", "render_mode_hint"]

    @field_validator('node_type')
    def node_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['state', 'event', 'evidence']):
            raise ValueError("must be one of enum values ('state', 'event', 'evidence')")
        return value

    @field_validator('status_tone')
    def status_tone_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['stable', 'changed', 'contradictory', 'stale', 'neutral']):
            raise ValueError("must be one of enum values ('stable', 'changed', 'contradictory', 'stale', 'neutral')")
        return value

    @field_validator('render_mode_hint')
    def render_mode_hint_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['detail', 'compact', 'overview']):
            raise ValueError("must be one of enum values ('detail', 'compact', 'overview')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphNeighborhoodNodeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if subtitle (nullable) is None
        # and model_fields_set contains the field
        if self.subtitle is None and "subtitle" in self.model_fields_set:
            _dict['subtitle'] = None

        # set to None if preview (nullable) is None
        # and model_fields_set contains the field
        if self.preview is None and "preview" in self.model_fields_set:
            _dict['preview'] = None

        # set to None if status_label (nullable) is None
        # and model_fields_set contains the field
        if self.status_label is None and "status_label" in self.model_fields_set:
            _dict['status_label'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        # set to None if evidence_count (nullable) is None
        # and model_fields_set contains the field
        if self.evidence_count is None and "evidence_count" in self.model_fields_set:
            _dict['evidence_count'] = None

        # set to None if kind_label (nullable) is None
        # and model_fields_set contains the field
        if self.kind_label is None and "kind_label" in self.model_fields_set:
            _dict['kind_label'] = None

        # set to None if meta (nullable) is None
        # and model_fields_set contains the field
        if self.meta is None and "meta" in self.model_fields_set:
            _dict['meta'] = None

        # set to None if timestamp_label (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_label is None and "timestamp_label" in self.model_fields_set:
            _dict['timestamp_label'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if accent_color (nullable) is None
        # and model_fields_set contains the field
        if self.accent_color is None and "accent_color" in self.model_fields_set:
            _dict['accent_color'] = None

        # set to None if cluster_membership (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_membership is None and "cluster_membership" in self.model_fields_set:
            _dict['cluster_membership'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphNeighborhoodNodeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "node_type": obj.get("node_type"),
            "title": obj.get("title"),
            "subtitle": obj.get("subtitle"),
            "preview": obj.get("preview"),
            "status_label": obj.get("status_label"),
            "status_tone": obj.get("status_tone"),
            "confidence": obj.get("confidence"),
            "evidence_count": obj.get("evidence_count"),
            "kind_label": obj.get("kind_label"),
            "meta": obj.get("meta"),
            "timestamp_label": obj.get("timestamp_label"),
            "reason": obj.get("reason"),
            "accent_color": obj.get("accent_color"),
            "display_priority": obj.get("display_priority"),
            "node_density_hint": obj.get("node_density_hint"),
            "cluster_membership": obj.get("cluster_membership"),
            "render_mode_hint": obj.get("render_mode_hint")
        })
        return _obj


