# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from atulya_client_api.models.budget import Budget
from atulya_client_api.models.reflect_include_options import ReflectIncludeOptions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InternetResearchRequest(BaseModel):
    """
    Request live-web research (optional SearXNG + Firecrawl stack). Does not use bank memory as context.
    """ # noqa: E501
    query: StrictStr = Field(description="Question to answer using the public web only")
    budget: Optional[Budget] = None
    max_tokens: Optional[StrictInt] = Field(default=None, description="Max completion tokens for each LLM step where supported")
    include: Optional[ReflectIncludeOptions] = Field(default=None, description="Optional tool trace (include.facts is ignored).")
    __properties: ClassVar[List[str]] = ["query", "budget", "max_tokens", "include"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternetResearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of include
        if self.include:
            _dict['include'] = self.include.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternetResearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "budget": obj.get("budget"),
            "max_tokens": obj.get("max_tokens"),
            "include": ReflectIncludeOptions.from_dict(obj["include"]) if obj.get("include") is not None else None
        })
        return _obj


