# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LLMRequestRow(BaseModel):
    """
    A single row in an LLM request trace.
    """ # noqa: E501
    id: StrictStr
    bank_id: Optional[StrictStr] = None
    operation: Optional[StrictStr] = None
    scope: Optional[StrictStr] = None
    trace_id: Optional[StrictStr] = None
    span_id: Optional[StrictStr] = None
    parent_span_id: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    model: Optional[StrictStr] = None
    status: StrictStr
    started_at: StrictStr
    ended_at: Optional[StrictStr] = None
    duration_ms: Optional[StrictInt] = None
    input_tokens: Optional[StrictInt] = None
    output_tokens: Optional[StrictInt] = None
    cached_tokens: Optional[StrictInt] = None
    total_tokens: Optional[StrictInt] = None
    input: Optional[Dict[str, Any]] = None
    output: Optional[Dict[str, Any]] = None
    error: Optional[Dict[str, Any]] = None
    llm_info: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "bank_id", "operation", "scope", "trace_id", "span_id", "parent_span_id", "provider", "model", "status", "started_at", "ended_at", "duration_ms", "input_tokens", "output_tokens", "cached_tokens", "total_tokens", "input", "output", "error", "llm_info", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LLMRequestRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bank_id (nullable) is None
        # and model_fields_set contains the field
        if self.bank_id is None and "bank_id" in self.model_fields_set:
            _dict['bank_id'] = None

        # set to None if operation (nullable) is None
        # and model_fields_set contains the field
        if self.operation is None and "operation" in self.model_fields_set:
            _dict['operation'] = None

        # set to None if scope (nullable) is None
        # and model_fields_set contains the field
        if self.scope is None and "scope" in self.model_fields_set:
            _dict['scope'] = None

        # set to None if trace_id (nullable) is None
        # and model_fields_set contains the field
        if self.trace_id is None and "trace_id" in self.model_fields_set:
            _dict['trace_id'] = None

        # set to None if span_id (nullable) is None
        # and model_fields_set contains the field
        if self.span_id is None and "span_id" in self.model_fields_set:
            _dict['span_id'] = None

        # set to None if parent_span_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_span_id is None and "parent_span_id" in self.model_fields_set:
            _dict['parent_span_id'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.ended_at is None and "ended_at" in self.model_fields_set:
            _dict['ended_at'] = None

        # set to None if duration_ms (nullable) is None
        # and model_fields_set contains the field
        if self.duration_ms is None and "duration_ms" in self.model_fields_set:
            _dict['duration_ms'] = None

        # set to None if input_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.input_tokens is None and "input_tokens" in self.model_fields_set:
            _dict['input_tokens'] = None

        # set to None if output_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.output_tokens is None and "output_tokens" in self.model_fields_set:
            _dict['output_tokens'] = None

        # set to None if cached_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cached_tokens is None and "cached_tokens" in self.model_fields_set:
            _dict['cached_tokens'] = None

        # set to None if total_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.total_tokens is None and "total_tokens" in self.model_fields_set:
            _dict['total_tokens'] = None

        # set to None if input (nullable) is None
        # and model_fields_set contains the field
        if self.input is None and "input" in self.model_fields_set:
            _dict['input'] = None

        # set to None if output (nullable) is None
        # and model_fields_set contains the field
        if self.output is None and "output" in self.model_fields_set:
            _dict['output'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if llm_info (nullable) is None
        # and model_fields_set contains the field
        if self.llm_info is None and "llm_info" in self.model_fields_set:
            _dict['llm_info'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LLMRequestRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "bank_id": obj.get("bank_id"),
            "operation": obj.get("operation"),
            "scope": obj.get("scope"),
            "trace_id": obj.get("trace_id"),
            "span_id": obj.get("span_id"),
            "parent_span_id": obj.get("parent_span_id"),
            "provider": obj.get("provider"),
            "model": obj.get("model"),
            "status": obj.get("status"),
            "started_at": obj.get("started_at"),
            "ended_at": obj.get("ended_at"),
            "duration_ms": obj.get("duration_ms"),
            "input_tokens": obj.get("input_tokens"),
            "output_tokens": obj.get("output_tokens"),
            "cached_tokens": obj.get("cached_tokens"),
            "total_tokens": obj.get("total_tokens"),
            "input": obj.get("input"),
            "output": obj.get("output"),
            "error": obj.get("error"),
            "llm_info": obj.get("llm_info"),
            "metadata": obj.get("metadata")
        })
        return _obj


