# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from atulya_client_api.models.prediction_point import PredictionPoint
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubRoutineHistogramResponse(BaseModel):
    """
    SubRoutineHistogramResponse
    """ # noqa: E501
    bank_id: StrictStr
    histogram: List[PredictionPoint]
    sample_count: Optional[StrictInt] = None
    source_snapshot_id: Optional[StrictStr] = None
    model_signature: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["bank_id", "histogram", "sample_count", "source_snapshot_id", "model_signature"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubRoutineHistogramResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in histogram (list)
        _items = []
        if self.histogram:
            for _item_histogram in self.histogram:
                if _item_histogram:
                    _items.append(_item_histogram.to_dict())
            _dict['histogram'] = _items
        # set to None if source_snapshot_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_snapshot_id is None and "source_snapshot_id" in self.model_fields_set:
            _dict['source_snapshot_id'] = None

        # set to None if model_signature (nullable) is None
        # and model_fields_set contains the field
        if self.model_signature is None and "model_signature" in self.model_fields_set:
            _dict['model_signature'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubRoutineHistogramResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bank_id": obj.get("bank_id"),
            "histogram": [PredictionPoint.from_dict(_item) for _item in obj["histogram"]] if obj.get("histogram") is not None else None,
            "sample_count": obj.get("sample_count"),
            "source_snapshot_id": obj.get("source_snapshot_id"),
            "model_signature": obj.get("model_signature")
        })
        return _obj


