# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TasteImportSetsRequest(BaseModel):
    """
    TasteImportSetsRequest
    """ # noqa: E501
    sets: Optional[List[Dict[str, Any]]] = None
    jsonl: Optional[StrictStr] = None
    taste_tags: Optional[List[StrictStr]] = None
    set_key_prefix: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["sets", "jsonl", "taste_tags", "set_key_prefix"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TasteImportSetsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if jsonl (nullable) is None
        # and model_fields_set contains the field
        if self.jsonl is None and "jsonl" in self.model_fields_set:
            _dict['jsonl'] = None

        # set to None if set_key_prefix (nullable) is None
        # and model_fields_set contains the field
        if self.set_key_prefix is None and "set_key_prefix" in self.model_fields_set:
            _dict['set_key_prefix'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TasteImportSetsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sets": obj.get("sets"),
            "jsonl": obj.get("jsonl"),
            "taste_tags": obj.get("taste_tags"),
            "set_key_prefix": obj.get("set_key_prefix")
        })
        return _obj
