# coding: utf-8

"""
    Atulya HTTP API

    HTTP API for Atulya

    The version of the OpenAPI document: 0.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TimelineTemporalResponse(BaseModel):
    """
    TimelineTemporalResponse
    """ # noqa: E501
    anchor_at: Optional[StrictStr] = None
    anchor_kind: StrictStr
    recorded_at: Optional[StrictStr] = None
    direction: StrictStr
    confidence: Optional[Union[StrictFloat, StrictInt]] = None
    reference_text: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["anchor_at", "anchor_kind", "recorded_at", "direction", "confidence", "reference_text"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimelineTemporalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if anchor_at (nullable) is None
        # and model_fields_set contains the field
        if self.anchor_at is None and "anchor_at" in self.model_fields_set:
            _dict['anchor_at'] = None

        # set to None if recorded_at (nullable) is None
        # and model_fields_set contains the field
        if self.recorded_at is None and "recorded_at" in self.model_fields_set:
            _dict['recorded_at'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        # set to None if reference_text (nullable) is None
        # and model_fields_set contains the field
        if self.reference_text is None and "reference_text" in self.model_fields_set:
            _dict['reference_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimelineTemporalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "anchor_at": obj.get("anchor_at"),
            "anchor_kind": obj.get("anchor_kind"),
            "recorded_at": obj.get("recorded_at"),
            "direction": obj.get("direction"),
            "confidence": obj.get("confidence"),
            "reference_text": obj.get("reference_text")
        })
        return _obj


